### ISSUE TITLE
Copy to clipboard functionality on website copies name of file as well

### ISSUE THREAD

**Issue by minac** [kubernetes/website#10221]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
Copy to clipboard functionality on website code snippets copies name of file at the top as well as the code itself.

**Proposed Solution:**
Fix javascript that does that to not include the name of the file? :)

**Page to Update:**
Any page with a code snippet on the website. Example:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/

Example from page above:

```
pods/storage/redis.yaml  
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}
```
