### ISSUE TITLE
The "Learn Kubernetes Basics" Button on The Menu Looks Cramped

### ISSUE THREAD

**Issue by aligoren** [kubernetes/website#10309]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Hi, I'm using Firefox Quantum 61.0.1. Today, I visited the Kubernetes' website. When I was scrolling the page, I saw the "**Learn Kubernetes Basics**" button on the menu. It looked cramped. There is an example in below screenshot.

![image](https://user-images.githubusercontent.com/4205423/45595629-7b161a80-b9b7-11e8-9686-868d7504787c.png)

**Proposed Solution:**

I opened the developer tools on the Firefox. I changed the button's CSS code like that;

```css
.open-nav #tryKubernetes, .y-enough #tryKubernetes {
    width: auto;
    background-color: #3371e3;
    border-color: #3371e3;
    padding: 0 10px;
}
```

The old CSS code was like that;

```css
.open-nav #tryKubernetes, .y-enough #tryKubernetes {
    width: 150px;
    background-color: #3371e3;
    border-color: #3371e3;
}
```

Anyway, the first CSS code worked for me. You can see in the below screenshot.

![image](https://user-images.githubusercontent.com/4205423/45595665-ff689d80-b9b7-11e8-9409-6b11f4fc8dc2.png)

**Page to Update:**

This issue only for the index page. The other pages don't have a button like that.

https://kubernetes.io/

**Additional Information:**

These are my browser's details with my operating system

```text
Browser: Firefox Quantum 61.0.1.
Operating system: Ubuntu
Browser size: 1911 x 929
Screen size: 1920 x 1080
```
