### ISSUE TITLE
Update ReplicaSet concept topic

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#12081]
**This is a...** 

- [ x] Feature Request
- [ ] Bug Report

**Proposed Solution:**
Update the ReplicaSets concept topic.

* Remove time-sensitive phrases like "is the next-generation".
* Bring text and code examples into alignment with our style guide.
* Add an explanation of how a Pod has an ownerReference, and a ReplicaSet can be the owner of a 
  Pod.
* Explain in detail how the ReplicaSet controller bases its actions on both Pod labels and Pod 
  ownerReference.
* Possibly simplify code examples. For example, why does the main example have both matchLabels 
  and matchExpressions?

```
selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
```

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-selector
