### ISSUE TITLE
Issue with k8s.io/docs/tasks/inject-data-application/distribute-credentials-secure/

### ISSUE THREAD

**Issue by dennisg** [kubernetes/website#12117]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
The kubectl command given below the yaml for creating a secret results in a different secret.
`wget https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/inject/secret.yaml`
```
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi
```
is listed on the page, versus:

`wget https://k8s.io/docs/tasks/inject-data-application/secret.yaml` in the kubectl command
```apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bXktYXBwCg==
  password: Mzk1MjgkdmRnN0piCg==
```
the latter yaml is filled with output from:
`echo 'my-app' | base64` and `echo '39528$vdg7Jb' | base64`

**Proposed Solution:**
Update `https://k8s.io/docs/tasks/inject-data-application/secret.yaml`

**Page to Update:**
https://k8s.io/docs/tasks/inject-data-application/secret.yaml

Thanks!
