### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/dns-debugging-resolution/

### ISSUE THREAD

**Issue by daohu527** [kubernetes/website#12156]
**This is a** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Because the busybox's "nslookup" issue in the lastest version [issue](https://github.com/docker-library/busybox/issues/48). Can't use "nslookup" in busybox pod to find the service by dns service.

**Proposed Solution:**
Use the busybox version  1.28 will solve the problem.
Change the "busybox.yaml" as:
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
I see the [link](https://github.com/kubernetes/website/blob/master/content/en/examples/admin/dns/busybox.yaml) has already been updated but I don't know why this [link](https://k8smeetup.github.io/docs/tasks/administer-cluster/dns-debugging-resolution/) is not.

**Page to Update:**
https://k8smeetup.github.io/docs/tasks/administer-cluster/dns-debugging-resolution/

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
