### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/cloud-providers/

### ISSUE THREAD

**Issue by darthcabs** [kubernetes/website#12538]
**This is a Bug Report** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The documentation shows wrong code (tested with kubeadm 1.13.3). It shows a YAML config file for kubeadm, but the block in this code for passing extra args to apiServer and controllerManager doesn't pass the arg --cloud-provider to apiServer or controllerManager.

**Proposed Solution:**

Replace the block of code for passing extra args from:

apiServer:
  extraArgs:
    cloud-provider: "openstack"
    cloud-config: "/etc/kubernetes/cloud.conf"
    (...)
controllerManager:
  extraArgs:
    cloud-provider: "openstack"
    cloud-config: "/etc/kubernetes/cloud.conf"

to:

apiServerExtraArgs:
    cloud-provider: "openstack"
    cloud-config: "/etc/kubernetes/cloud.conf"
    (...)
controllerManagerExtraArgs:
    cloud-provider: "openstack"
    cloud-config: "/etc/kubernetes/cloud.conf"

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers

**Comment by neolit123** [comment]
if i go to this page:
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers

i see this:
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "openstack"
    cloud-config: "/etc/kubernetes/cloud.conf"
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.0
apiServer:
  extraArgs:
    cloud-provider: "openstack"
    cloud-config: "/etc/kubernetes/cloud.conf"
  extraVolumes:
  - name: cloud
    hostPath: "/etc/kubernetes/cloud.conf"
    mountPath: "/etc/kubernetes/cloud.conf"
controllerManager:
  extraArgs:
    cloud-provider: "openstack"
    cloud-config: "/etc/kubernetes/cloud.conf"
  extraVolumes:
  - name: cloud
    hostPath: "/etc/kubernetes/cloud.conf"
    mountPath: "/etc/kubernetes/cloud.conf"
```

which is the valid v1beta1.

where are you seeing this config:
```
apiServer:
extraArgs:
cloud-provider: "openstack"
cloud-config: "/etc/kubernetes/cloud.conf"
(...)
controllerManager:
extraArgs:
cloud-provider: "openstack"
cloud-config: "/etc/kubernetes/cloud.conf"
```
?

/priority awaiting-more-evidence
