### ISSUE TITLE
Feature request : ConfigMap in Ingress

### ISSUE THREAD

**Issue by fungiboletus** [kubernetes/website#12655]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

I would like to deploy an Ingress with configurations settings stored inside a ConfigMap.

**Proposed Solution:**

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host:
    valueFrom:
      configMapKeyRef:
        name: ingress-config
        key: INGRESS_HOST
  - http:
      paths:
      - path:
        valueFrom:
          configMapKeyRef:
            name: ingress-config
            key: INGRESS_PATH
        backend:
          serviceName: test
          servicePort: 80
```
