### ISSUE TITLE
Fix wrong content

### ISSUE THREAD

**Issue by daixiang0** [kubernetes/website#13528]
Bug Report

**Problem:**
![image](https://user-images.githubusercontent.com/26538619/55228120-50552a80-5254-11e9-80a6-b427c362d3e2.png)

**Proposed Solution:**
it should be
```
ports:
- name: liveness-port
  containerPort: 8080
  hostPort: 8080

livenessProbe:
  httpGet:
     path: /healthz
     port: liveness-port
```

**Page to Update:**
https://k8smeetup.github.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

I want to update it but do not know how to,

When i click `Edit this page`, jump to https://k8smeetup.github.io/editdocs/#docs/tasks/configure-pod-container/configure-liveness-readiness-probes.md, but those urls are all 404.
![image](https://user-images.githubusercontent.com/26538619/55228337-d3768080-5254-11e9-9865-6fb37682a0da.png)
