### ISSUE TITLE
.github/ISSUE_TEMPLATE/bug-report.md has an invalid yaml

### ISSUE THREAD

**Issue by fejta** [kubernetes/website#13615]
https://raw.githubusercontent.com/kubernetes/website/master/.github/ISSUE_TEMPLATE/bug-report.md

has a
```yaml
name: Bug Report
about: Report a bug encountered with Kubernetes Website
labels: kind/bug
```

document, however the labels should be a list of strings, not a string (aka `labels: ["kind/bug"]`)

```yaml
jsonPayload: {
  base:  "master"   
  client:  "repoowners"   
  component:  "hook"   
  error:  "error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field SimpleConfig.labels of type []string"   
  level:  "error"   
  msg:  "Error decoding OWNERS config from '*.md' file."   
  org:  "kubernetes"   
  path:  "/tmp/git817500724/.github/ISSUE_TEMPLATE/bug-report.md"   
  repo:  "website"   
 }
```

/assign @zacharysarah @mistyhacks @daminisatya

**Comment by daminisatya** [comment]
This is a good first-time issue like @zacharysarah tagged 😄

**Comment by rahulkrishnanfs** [comment]
Please let me know if I can help to fix this issue

**Comment by rahulkrishnanfs** [comment]
@fejta Please let me know how can I replicate this issue?

**Comment by mistyhacks** [comment]
I think the line just needs to be modified to the following:

```
label: ["kind/bug"]
```

In YAML, strings are quoted (as opposed to other types of variables like integers or booleans), and lists of strings are enclosed in square brackets and separated by commas.

**Comment by rahulkrishnanfs** [comment]
@mistyhacks But I could see that ISSUE_TEMPLATE/bug-report.md is using smilar format for other projects

**Comment by fejta** [comment]
Yeah does seem a bit mysterious... I'm filing this because I keep seeing the following errors:

```yaml
 insertId:  "p9594yf26wp2t"  
 jsonPayload: {
  base:  "master"   
  client:  "repoowners"   
  component:  "hook"   
  error:  "error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field SimpleConfig.labels of type []string"   
  level:  "error"   
  msg:  "Error decoding OWNERS config from '*.md' file."   
  org:  "kubernetes"   
  path:  "/tmp/git061330400/.github/ISSUE_TEMPLATE/bug-report.md"   
  repo:  "website"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/hook"  
 receiveTimestamp:  "2019-04-08T20:35:46.411924311Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-04-08T20:35:42Z"  

```

**Comment by kbhawkey** [comment]
Hello. Which program parses this markdown file?
Should the YAML in the markdown file look like:
```yaml
name: Bug Report
about: Report a bug ...
labels:
- kind/bug
```
