### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-stateless-application-deployment/

### ISSUE THREAD

**Issue by ashishth09** [kubernetes/website#14329]
**This is a Bug Report**

**Problem:**

This file is malformed  https://k8s.io/examples/application/deployment.yaml

```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
9
        ports:
        - containerPort: 80
```
There is a `9` appearing in the file

**Proposed Solution:**
Remove 9

**Page to Update:**
https://kubernetes.io/...
