### ISSUE TITLE
error: unable to recognize "example-ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by visch** [kubernetes/website#14322]
**This is a Bug Report**

**Problem:** Tried using the interactive minikube website and ran into issues. Specefically when running kubectl apply -f example-ingress.yaml . I am following https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

I received 

```
$ kubectl apply -f example-ingress.yaml
error: unable to recognize "example-ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```
**Proposed Solution:**

The solution that worked for me was to use the old api version of `apiVersion: extensions/v1beta1`

My full example-ingress.yaml file is

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: hello-world.info
   http:
     paths:
     - path: /*
       backend:
         serviceName: web
         servicePort: 8080
```

Maybe there's a better solution, but this worked for me. 

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
