### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

### ISSUE THREAD

**Issue by oz123** [kubernetes/website#14380]
Please provide a clarification on the effect of  `pv.beta.kubernetes.io/gid: "1234"`  or      `pv.beta.kubernetes.io/gid: "1234"`.

I followed the examples in this task, and added the annotation to the PV:

```
$ cat pv-volume.yml 
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  annotations:
    pv.beta.kubernetes.io/uid: 123
    pv.beta.kubernetes.io/gid: 123
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

$cat pv-pod.yml 
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  securityContext:
    #runAsUser: 1000
    #runAsGroup: 3000
    #fsGroup: 2000
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: alpine
      command:
       - "sleep"
      args:
       - "3600"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage

$ cat pv-claim.yml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

Now, the docs say: 
> Note: When a Pod consumes a PersistentVolume, the GIDs associated with the PersistentVolume are not present on the Pod resource itself.

So where are they?
```
$ kubectl apply -f .
persistentvolumeclaim/task-pv-claim created
pod/task-pv-pod created
persistentvolume/task-pv-volume created
```

Inside the container, the first process is still run as root with id 0. 
```
$ kubectl exec -it task-pv-pod -- ps
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 3600
   15 root      0:00 ps

$ kubectl exec -it task-pv-pod -- stat -c "%u %g" /proc/1
0 0
```

Also, all the directories belong just to root
```
$ kubectl exec -it task-pv-pod -- ls -ld {/usr,/usr/share/,/usr/share/nginx,/usr/share/nginx/html}
drwxr-xr-x    1 root     root          4096 May  9 20:49 /usr
drwxr-xr-x    1 root     root          4096 May 17 12:51 /usr/share/
drwxr-xr-x    3 root     root          4096 May 17 12:51 /usr/share/nginx
drwxr-xr-x    2 root     root          4096 May 17 12:03 /usr/share/nginx/html
```

I would really appreciate a clarification of what one should expect from this annotation.

**Comment by oz123** [comment]
After searching for a long time I think I found the problem.
`hostPath` seems not to offer this capability at all. I might be wrong about it.
Maybe there is a need for explicit clarification of which volume types support this annotations.

**Comment by oz123** [comment]
It seems that even with NFS it's not clear what this feature is supposed to do:


Here is a container which mounts NFS with beta annotation on the Volume
```
$ kubectl exec -it nfs-demo2-5bd5df656c-9487v sh
# mount | grep nfs
192.168.0.5:/share on /usr/share/nginx/html type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.0.6,local_lock=none,addr=192.168.0.5)
```
The directories are still owned by root:
```
root@nfs-demo2-5bd5df656c-9487v:/usr/share/nginx/html# ls -ld
drwxrwxrwx 2 root root 4096 Apr 23 08:02 .
root@nfs-demo2-5bd5df656c-9487v:/usr/share/nginx/html# ls -ld ..
drwxr-xr-x 3 root root 4096 Apr 30  2018 ..
```
PID 1 is still root:root
```
$ stat /proc/1/
  File: '/proc/1/'
  Size: 0         	Blocks: 0          IO Block: 1024   directory
Device: 4h/4d	Inode: 1032        Links: 9
Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
```

Here are my k8s manifests:
```
ubuntu@master-1-test:~/nfs-server-k8s/claims$ cat new-nfs-claim.yml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  creationTimestamp: null
  name: new-nfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  dataSource: null
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-pv2
status: {}
ubuntu@master-1-test:~/nfs-server-k8s/claims$ cat new-nfs.yml 
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  name: nfs-pv2
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /share/
    server: master-2-test
  persistentVolumeReclaimPolicy: Retain
ubuntu@master-1-test:~/nfs-server-k8s/claims$ cat nfs-deployment.yml 
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  generation: 1
  labels:
    app: nfs
  name: nfs-demo2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs
    spec:
      containers:
      - image: nginx:1.12.2
        imagePullPolicy: IfNotPresent
        name: nfs
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nfsvol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfsvol
        persistentVolumeClaim:
          claimName: new-nfs-pvc
status: {}
```
