### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-stateless-application-deployment/

### ISSUE THREAD

**Issue by itobey** [kubernetes/website#14514]
**This is a Bug Report**

**Problem:**
The tutorial mentions to create a deployment with nginx version 1.7.9 - doing so will result in a CrashLoopBackoff of the pods.

**Proposed Solution:**
Using a different version, e.g. 1.15 will result in a running pod.

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/

**Comment by zhangqx2010** [comment]
/triage needs-information
@itobey I tried in my enviroment but seems everything works fine.

```
[root@k8s-master1 issue-test]# cat deployment.yaml 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
[root@k8s-master1 issue-test]# kubectl get deployments.apps nginx-deployment 
NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment   2         2         2            2           5m10s
[root@k8s-master1 issue-test]# kubectl get po |grep  nginx-deployment
nginx-deployment-5c689d88bb-9z69c         1/1     Running   0          5m48s
nginx-deployment-5c689d88bb-tn2ld         1/1     Running   0          5m48s
[root@k8s-master1 issue-test]# kubectl version 
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

Could you provide more information about the CrashLoopBackoff pod?
Maybe run `kubectl describe po nginx-deployment-xxx-xxx` will help.
