### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by konectia** [kubernetes/website#14559]
**This is a Bug Report**

**Problem:**
Ingress apiVersion is incorrect.
If you try to create an Ingress as indicated in the documentation

```yml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```
code you'll get the following error:
´´´
no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
´´´
**Proposed Solution:**
Change _apiVersion: networking.k8s.io/v1beta1_ for _apiVersion: extensions/v1beta1_
**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/

Kubernetes version 1.12+
