### ISSUE TITLE
Document default value for RoleBinding ServiceAccount Subject namespace

### ISSUE THREAD

**Issue by jroper** [kubernetes/website#14624]
Let's say I create the following `RoleBinding`:

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```

Note, there is no `namespace` configured for the `ServiceAccount`. I can't find anywhere in the reference documentation or the guides that say what should happen in this case, every example has the `namespace` configured, and the reference documentation says only that the `namespace` is only valid for `ServiceAccount` subjects, it doesn't say what happens if not specified for `ServiceAccount` subjects. Yet, the role binding appears to be valid (it deploys with no errors) and meaningful (it gives my `default` service account the `pod-reader` role), as best as I can work out through experimentation, the namespace defaults to the namespace that the role binding is created in.
