### ISSUE TITLE
Issue with k8s.io/docs/concepts/containers/images/

### ISSUE THREAD

**Issue by kkoralsky** [kubernetes/website#14703]
**This is a Bug Report**

**Problem:**

referred at: https://kubernetes.io/docs/concepts/containers/images/#creating-a-secret-with-a-docker-config way of creating pullSecret declaratively using kustomize:
```
secretGenerator:
- name: myregistrykey
  type: docker-registry
  literals:
  - docker-server=DOCKER_REGISTRY_SERVER
  - docker-username=DOCKER_USER
  - docker-password=DOCKER_PASSWORD
  - docker-email=DOCKER_EMAIL
```
does not work neither with service account nor when specified in pod explicitly.

**Proposed Solution:**

Describe imperative way:
```
kubectl create secret docker-registry <name> --docker-server=... --docker-usernam=...
```

**Page to Update:**

https://kubernetes.io/docs/concepts/containers/images/#creating-a-secret-with-a-docker-config

kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
docker registry: gitlab-ce 11.9
