### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

### ISSUE THREAD

**Issue by chadmcrowell** [kubernetes/website#15534]
**This is a Bug Report**

**Problem:**
Parts of this page are missing. The "annotation-second-scheduler" pod remains in a pending state forever, even after the scheduler is deployed. Also, the wording at the bottom of the article is confusing, making the reader think that there is a way to resolve the pending state, when in fact there is not.

**Proposed Solution:**
Include steps to create role, rolebinding, clusterrole, clusterrolbinding, and modify the existing kube-scheduler clusterrole.  The following worked for me:

Creating the following clusterrole:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: csinodes-admin
rules:
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["get", "watch", "list"]
```

Creating the following clusterrolebinding:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-csinodes-global
subjects:
- kind: ServiceAccount
  name: my-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csinodes-admin
  apiGroup: rbac.authorization.k8s.io
```

Creating the following role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:serviceaccount:kube-system:my-scheduler
  namespace: kube-system
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
```

Creating the following rolebinding:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-csinodes
  namespace: kube-system
subjects:
- kind: User
  name: kubernetes-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: system:serviceaccount:kube-system:my-scheduler
  apiGroup: rbac.authorization.k8s.io
```

editing the `kube-scheduler` cluster role to include:
```
- apiGroups:
  - ""
  resourceNames:
  - kube-scheduler
  - my-scheduler
  resources:
  - endpoints
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - watch
  - list
  - get
```

Only after creating these resources (above) could I successfully schedule the pod using the secondary scheduler.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

Kubernetes Version:
1.15.1
