### ISSUE TITLE
Can't access my cluster

### ISSUE THREAD

**Issue by lucasSzavara** [kubernetes/website#16158]
**This is a Bug Report**

**Problem:**
I have a cluster running on gcp with a static address. I can see the cluster logs using `kubectl logs` and I when I run `kubectl get service` I get:
```
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)        AGE
backend-faltta   LoadBalancer   10.xxx.xxx.xxx   35.xxx.xxx.xxx   80:31250/TCP   15m
kubernetes       ClusterIP      10.xxx.xxx.xxx     <none>           443/TCP        20m
```
But when trying to make a request to 35.xxx.xxx.xxx I get: ERR_CONNECTION_REFUSED
My kubernetes.yaml is:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: $imageURL
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
      
---
kind: Service
apiVersion: v1
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "35.xxx.xxx.xxx"

```
