### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

### ISSUE THREAD

**Issue by yeouchien** [kubernetes/website#16262]
**This is a Bug Report**

**Problem:**
```
failureThreshold: ... Giving up in case of liveness probe means restarting the **Pod**. ...
```
The `Pod` here is incorrect. I have the following `livenessProbe`
```
livenessProbe:
  httpGet:
    host: 'www.grugruuuu.com' # site does not exist
    scheme: HTTPS
    port: 80
  initialDelaySeconds: 5
  timeoutSeconds: 5
  periodSeconds: 5
  failureThreshold: 1
```
It failed to probe 1 time and restart the `Container` and not `Pod`

**Proposed Solution:**
```
failureThreshold: ...Giving up in case of liveness probe means restarting the Container. ...
```

**Page to Update:**
https://kubernetes.io/...
