### ISSUE TITLE
Issue with k8s.io/zh/docs/home/

### ISSUE THREAD

**Issue by 1-step** [kubernetes/website#16541]
**This is a Bug Report**
远端主机访问kube proxy暴露的接口，会导致token输入无反应！

**Problem:**
我想要通过node port配合aws alb ingress controller的方式暴露dashboard的服务，因为有token验证，相对安全，但可能由于官方dashboard中https使用的是自动生成的证书，导致我ingress使用443端口关联service时，页面无法正常显示（访问nodeip:port没有内容）。部分配置如下：
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/certificate-arn:  xxxx
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
```
```
spec:
  # tls:
  # - secretName: kubernetes-dashboard-certs
  rules:
  - host: db8s.ops.taprnd.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
```
planB：考虑将servicePort改为80端口，使用1.10.1版本镜像，可以访问dashboard但是无法进行token验证，不安全。
planC：使用kube proxy的方式访问dashboard，使用命令
kubectl proxy --address='0.0.0.0'  --accept-hosts='^*$' 
开放远程访问，token页面可以正常打开，输入token之后却无响应。
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...
