### ISSUE TITLE
Does the default reclaim policy change to “Retain” ?

### ISSUE THREAD

**Issue by diguage** [kubernetes/website#16546]
I read the documentation: [Change the Reclaim Policy of a PersistentVolume - Kubernetes](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/).
It says that `For dynamically provisioned PersistentVolumes, the default reclaim policy is “Delete”.`.

But I check the result of a PersistentVolume object which I created. Its reclaim policy is `Retain`.

```shell
kubectl get pv

NAME             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                   STORAGECLASS   REASON   AGE
task-pv-volume   5Gi        RWO            Retain           Bound    default/task-pv-claim   manual                  119s
```

I follow the documentation to create the PersistentVolume:

1. [Configure a Pod to Use a Volume for Storage - Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/)
1. [Configure a Pod to Use a PersistentVolume for Storage - Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/)

**The PersistentVolume YAML** is:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
    name: task-pv-volume
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/data"
```

**The PersistentVolumeClaim YAML** is:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: task-pv-claim
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
```

**The Kubernetes version** is:

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

And I user Kubespray to install the Kubernetes cluster on bare metal(Ubuntu 18.04.3 LTS): [Readme - Kubespray - Deploy a Production Ready Kubernetes Cluster](https://kubespray.io/#/)

----

I do the experiment: [Change the Reclaim Policy of a PersistentVolume - Kubernetes](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/). 

I change the reclaim policy to `Delete`, but it can not be change:
```
kubectl patch pv task-pv-volume -p '{"spec":{"persistenVolumeReclaimPolicy":"Delete"}}'

persistentvolume/task-pv-volume patched (no change)

// ---

kubectl get pv

NAME             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                   STORAGECLASS   REASON   AGE
task-pv-volume   5Gi        RWO            Retain           Bound    default/task-pv-claim   manual                  29m
```
