### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/cassandra/

### ISSUE THREAD

**Issue by zealzhangz** [kubernetes/website#16582]
**This is a Bug Report**

**Problem:**
In this case how can I connect the cassandra cluster by cqlsh tool from an external IP?

**Proposed Solution:**
I tried this setting，I'm not sure if this is the best graceful way.:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  type: NodePort
  ports:
  - port: 9042
  selector:
    app: cassandra
```

**Page to Update:**
