### ISSUE TITLE
Issue with /docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap

### ISSUE THREAD

**Issue by manishbansal8843** [kubernetes/website#16803]
**Problem:**
It says `The command section references the special.level item stored in the ConfigMap.`
**Proposed Solution:**
This is wrong. The command used in command section is `ls` command which lists the files in directory which got populated by a config map. Where as the config map has 2 entries as below.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
```
