### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/storage-classes/

### ISSUE THREAD

**Issue by cgthayer** [kubernetes/website#17153]
**This is a Bug Report**

**Problem:**

The example for "GCE PD" returns errors on Google Kubernetes Engine

```
error validating data: [ValidationError(PersistentVolumeClaim): unknown field "parameters" in io.k8s.api.core.v1.PersistentVolumeClaim, ValidationError(PersistentVolumeClaim): unknown field "provisioner" in io.k8s.api.core.v1.PersistentVolumeClaim]; if you choose to ignore these errors, turn validation off with --validate=false
```
My file was:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
 provisioner: kubernetes.io/gce-pd
 parameters:
   type: pd-standard
   replication-type: none
```

**Proposed Solution:**
Unknown

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by lojies** [comment]
It seems like your yaml with a bad indent in lines provisioner and parameters .
Is this ok?
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:  slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
```
