### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/reconfigure-kubelet/ "Set the Node to use the new configuration" not working

### ISSUE THREAD

**Issue by leon0707** [kubernetes/website#17663]
**This is a Bug Report**

**Problem:**
I followed the instruction to create the node config and generate the ConfigMap.
add `"allowedUnsafeSysctls": ["net.core.somaxconn"]` in ConfigMap `my-node-config-47h456d2dc`
Then I edited the Node’s reference to point to the new ConfigMap
```yaml
spec:
  configSource:
    configMap:
      kubeletConfigKey: kubelet
      name: my-node-config-47h456d2dc
      namespace: kube-system
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
```
`kubectl get no ${NODE_NAME} -o json | jq '.status.config'` returned nothing.
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...
