### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/cron-jobs/

### ISSUE THREAD

**Issue by JakubOboza** [kubernetes/website#18196]
**This is a Bug Report**

**Problem:**
This is the first one you get when searching docs for CronJob.  I know this is a small suggestion but i think it would help a lot in reducing time searching / exploring kubectl explain.

**Proposed Solution:**

It should imho contain a example just like on the page: https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/ this would help to speed up search if needed fast.

This example one: (copy paste from url)

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
