### ISSUE TITLE
Deployment v1 apps kubectl example should have selector field

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#18477]
**This is a Bug Report**

**Problem:**
![deployment](https://user-images.githubusercontent.com/4710215/71782551-a1355300-301e-11ea-8659-b4671bfa92bd.png)

This sample yaml fails to create a deployment resource.
> error: error validating "deployment.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Proposed Solution:**

`selector` filed should be added.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: deployment-example
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nginx
    spec:
      containers:
      - name: nginx
        # Run this image
        image: nginx:1.10
```

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#deployment-v1-apps
