### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

### ISSUE THREAD

**Issue by sys-ops** [kubernetes/website#18724]
**This is a Bug Report**

**Problem:**
I followed the steps in https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/ tutorial.

At the end of it the annotation-second-scheduler POD got into **the pending state**.

Client Version: v1.17.0
Server Version: v1.17.0

Errors visible in my-scheduler POD:

```
E0116 10:02:07.858430       1 reflector.go:166] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:209: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E0116 10:02:08.824540       1 reflector.go:166] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope
```

**Proposed Solution:**
Remove lock-object-namespace and lock-object-name from https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/.
There is no lock-object-namespace namespace, hence my-scheduler won't not work properly.
```
--lock-object-namespace=lock-object-namespace
--lock-object-name=lock-object-name
```

In addition to that, add the following lines to clusterrole system:kube-scheduler:

```
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
```

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
