### ISSUE TITLE
hostPath volume description should mention and recommend readOnly field

### ISSUE THREAD

**Issue by php-coder** [kubernetes/website#18850]
**This is a Feature Request**
The chapter that describes `hostPath` volume should mention `readOnly` field and recommend to use it when possible.

**What would you like to be added**
https://kubernetes.io/docs/concepts/storage/volumes/#hostpath should mention `readOnly` field

**Why is this needed**
This improves cluster security and should be always used when possible. Without a warning users might not know or just forget to specify this flag.

**Comments**
We might use a warning from https://kubernetes.io/docs/concepts/policy/pod-security-policy/#volumes-and-file-systems as a draft and modify it accordingly.

/sig auth
/kind documentation

**Comment by tengqm** [comment]
/remove-lifecycle rotten
@McCoyAle Still working on this?

**Comment by hugoprudente** [comment]
Adding the PSS as is the future as K8S 1.21 is deprecating PSP. 

All Documentation for mention Read Only should also be covered in this docf from now on. 
https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline

**Comment by sgandon** [comment]
does this mean that readonly for hostpath is allowed and working but just not documented  ?

**Comment by php-coder** [comment]
@sgandon yes, exactly

**Comment by sgandon** [comment]
that is ownsome I was just going to rule out this solution because of the security issue. Thanks for your answer I'll test it right away.

**Comment by sgandon** [comment]
well, 
I am using this manifest
```
      volumes:
      - name: connectors
        hostPath:
          readOnly: true
          # directory location on host
          path: /somedir
          # this field is optional
          type: DirectoryOrCreate   
```
but I get this error
```
k apply -f my-manifest.yaml
error: error validating "my-manifest.yaml": error validating data: ValidationError(Job.spec.template.spec.volumes[0].hostPath): unknown field "readOnly" in io.k8s.api.core.v1.HostPathVolumeSource; if you choose to ignore these errors, turn validation off with --validate=false
```
