### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/network-policies/

### ISSUE THREAD

**Issue by andrea-tortosa** [kubernetes/website#19047]
**This is a Bug Report**

**Problem:**
In section 'Default deny all ingress and all egress traffic' the associated example is the same of 'Default deny all egress traffic' that is

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
spec:
  podSelector: {}
  policyTypes:
  - Egress

**Proposed Solution:**
I think is missing 
  policyTypes:
  - Ingress

based on what I've read before but I could be wrong since I'm just learning these days

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by sujaypillai** [comment]
I would like to take this up. Thanks.

**Comment by sftim** [comment]
It's possible that PR #18091 introduced a regression here.

**Comment by sftim** [comment]
https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic looks correct to me though.

**Comment by sujaypillai** [comment]
https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-ingress-and-all-egress-traffic
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
spec:
  podSelector: {}
  policyTypes:
  - Egress
```

which should be 
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-ingress-egress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

Also I would like to update the name to `default-deny-all-ingress-egress`

Let me know if that is appropriate.
