### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/service/

### ISSUE THREAD

**Issue by dominikzorgnotti** [kubernetes/website#19176]
**This is a Bug Report**

**Problem:**
The section about `LoadbalancerIP` is a somewhat vague for k8s beginners like me. I was thrown off by the example above the section in question and couldn't immediately identify how to make use of that information. 

**Proposed Solution:**
I suggest some re-phrasing and adding an example. This would be my suggestion for the content:

A user-specified address for a load balancer can be set with the optional field `loadBalancerIP`. If `loadBalancerIP` is not specified or your cloud provider does not support the feature then an ephemeral IP address is assigned.  
Here is an example for assigning a user-specified address (192.0.2.10) when using the type `LoadBalancer`:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.0.2.10
  selector:
    app: example
  ports:
  - port: 1234
    targetPort: 1234
```

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
