### ISSUE TITLE
indentation error in  k8s.io/docs/tasks/administer-cluster/kms-provider/

### ISSUE THREAD

**Issue by clumsy456** [kubernetes/website#19337]
**This is a Bug Report**

**Problem:**
There are indentation errors in the yaml files of EncryptionConfiguration. For example in the following yaml, lines after "- secrets" should indent two to the right.
![pic](https://user-images.githubusercontent.com/19684295/75445835-301c7700-59a1-11ea-958b-bb68ab4738e8.PNG)

**Proposed Solution:**
Correct the indentation errors.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/

**Comment by sftim** [comment]
Is it right to have
```yaml
resources:
  - resources:
```
in the fixed page?

**Comment by clumsy456** [comment]
> Is it right to have
> 
> ```yaml
> resources:
>   - resources:
> ```
> 
> in the fixed page?

I checked the preview page, and it's still wrong. I've close my PR.

**Comment by clumsy456** [comment]
It should looks like this
```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- resources:
  - secrets
  providers:
  - kms:
      name: myKmsPlugin
      endpoint: unix:///tmp/socketfile.sock
      cachesize: 100
      timeout: 3s
  - identity: {}
```
or
```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - kms:
          name: myKmsPlugin
          endpoint: unix:///tmp/socketfile.sock
          cachesize: 100
          timeout: 3s
      - identity: {}
```
"secrets" is the subcontent of the second "resources", and "providers" is with the same level of the second "resources".
Although I modified the markdown, the rendered webpage is still wrong.
