### ISSUE TITLE
Why default toleration in DS example k8s.io/docs/concepts/workloads/controllers/daemonset/

### ISSUE THREAD

**Issue by sam-sla** [kubernetes/website#19512]
**This is a Bug Report**

**Problem:**
The example "Create a DaemonSet" adds a toleration for the "NoSchedule" effect on the master node, I don't understand why. I don't think this is a good default to have in the example. 

**Proposed Solution:**
Remove the toleration from the spec:
```
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
```

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#create-a-daemonset
