### ISSUE TITLE
Issue with k8s.io/docs/concepts/policy/pod-security-policy/

### ISSUE THREAD

**Issue by zhiyanliu** [kubernetes/website#19564]
**This is a Bug Report**

**Problem:**
I failed to use `podsecuritypolicies` resource after I prepare it and rbac based on the example yaml snippet in the doc https://v1-14.docs.kubernetes.io/docs/concepts/policy/pod-security-policy/#via-rbac .

**How to reproduce/what I tested:**
```
kubectl create namespace psp-example
kubectl create serviceaccount -n psp-example fake-sa

kubectl apply -f- <<EOF
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: example
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: examplerole
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: examplerolebinding
roleRef:
  kind: ClusterRole
  name: examplerole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fake-sa
  namespace: psp-example
EOF

kubectl auth can-i use podsecuritypolicy/example --as=system:serviceaccount:psp-example:fake-sa -n psp-example    # output "no", this is unexpected
```

1. In the rules of above `ClusterRole` resource I used `policy` api group for `podsecuritypolicies` resource as the doc example guided.
2. `kubectl auth can-i use` always returns `no`.

**How to fix/what I verified:**
```
kubectl apply -f- <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: examplerole
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - example
EOF

kubectl auth can-i use podsecuritypolicy/example --as=system:serviceaccount:psp-example:fake-sa -n psp-example    # output "yes", this is normal
```

1. In the rules of above `ClusterRole` resource I updated to use `extensions` api group for `podsecuritypolicies` resource.
2. `kubectl auth can-i use` returns `yes`.

**Software versions I used:**
`kubectl version`
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Additional:**
According to @liggitt 's comments, I see both api groups are checked at [0][1], so I think this doc is ok to use newer `policy` group instead of `extensions`, but I consider a defect in somewhere need to be fixed to make the example yaml snippet in the doc works (or correct me if my testing has something wrong). I'd like to move this issue to a proper place if needed.

[0] https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/security/podsecuritypolicy/admission.go#L345-L351
[1] https://github.com/kubernetes/kubernetes/blob/release-1.14/plugin/pkg/admission/security/podsecuritypolicy/admission.go#L371

**Last issue description: (in order to help reader understands original comments in this issue)**
Wrong api group used in the example yaml snippet at https://kubernetes.io/docs/concepts/policy/pod-security-policy/#via-rbac , the api group name of resource `podsecuritypolicies` should be changed to `extensions` from `policy`.
I tested the group policy rule in v.1.14.9 [0], the policy can not be granted to the service account always.
[0] https://v1-14.docs.kubernetes.io/docs/concepts/policy/pod-security-policy/#via-rbac

Thanks.
