### ISSUE TITLE
Improvement for k8s.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage

### ISSUE THREAD

**Issue by davidparks21** [kubernetes/website#20134]
Looking at section: Local Ephemeral Storage
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage

The example YAML for ephemeral storage does not demonstrate the need for the volume or volume mount, it only shows the resource request form in the YAML as:

```
resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
```

From reading that documentation it's easy to assume that simply adding the `ephemeral-storage` resource request makes that amount of storage available to the containers root filesystem, which is not correct.

The ephemeral-storage volume needs to be mounted as with:

```
      volumes:
      - name: data
        emptyDir: {}
```
and
```
        volumeMounts:
        - name: data
          mountPath: /mnt/data
```

But that is not captured in the documentation. At a minimum, the example YAML should include the volume and mount example to clarify this point. Otherwise, people (like me) will unwittingly assume they have 2Gi of space on the container root, which will likely work until a random unlucky day in the future leading to hard to debug issues.

**Comment by tengqm** [comment]
@davidparks21 Are you okay to close this now?

**Comment by davidparks21** [comment]
I think the best way to express that is to simply add the volume mounts to the example. This example is lacking volume mounts and so it's not clear unless you dig into the text to understand this detail.

```
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
  - name: wp
    image: wordpress
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
```

If you change that example to this it becomes a complete example in which the ephemeral-storage is actually mounted. As-is that example misleads the user to thinking that they have requested 2Gi of ephemerial-storage which is applied to their root filesystem. 

```
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
      - name: ephemeral
        mountPath: "/tmp"
  volumes:
    - name: ephemeral
      emptyDir: {}
  - name: wp
    image: wordpress
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
      - name: ephemeral
        mountPath: "/tmp"
  volumes:
    - name: ephemeral
      emptyDir: {}
```
