### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by pleshakov** [kubernetes/website#20397]
**This is a Bug Report**

**Problem:**

In the documentation for the IngressClass resource, the provided example is rejected by the Kubernetes API:
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: external-lb
spec:
  controller: example.com/ingress-controller
  parameters:
    apiGroup: k8s.example.com/v1alpha
    kind: IngressParameters
    name: external-lb
```
```
kubectl create -f example.yaml
The IngressClass "external-lb" is invalid: spec.parameters.apiGroup: Invalid value: "k8s.example.com/v1alpha": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Proposed Solution:**
`k8s.example.com/v1alpha` --> `k8s.example.com`

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class
