### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/get-shell-running-container/

### ISSUE THREAD

**Issue by vmwarelab** [kubernetes/website#20688]
**This is a Bug Report**

**Problem:**
this command doesn't work when trying to access a pod
kubectl exec -it shell-demo -- /bin/bash

usually now i do 
kubectl exec -it shell-demo -- sh

**Page to Update:**
https://kubernetes.io/...

**Comment by viniciusbds** [comment]
Hi @vmwarelab. 

I think that doesn't work because you are using a image that doesn't have the bash command.

for exemple:

The busybox image doesn't have a /bin/bash file

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox-shell-demo
  labels:
    app: myapp
spec:
  containers:
  - name: busybox-shell-demo
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
```

and will fail if we try to use **/bin/bash** ...

```
vinicius@ideapad-s145:~$ kubectl exec -it busybox-shell-demo -- /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
command terminated with exit code 126
```

So if we use an image that contains the /bin/bash file, e.x: ubuntu, it will work as  expected.

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-shell-demo
  labels:
    app: myapp
spec:
  containers:
  - name: ubuntu-shell-demo
    image: ubuntu
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
```

```
vinicius@ideapad-s145:~$ kubectl exec -it ubuntu-shell-demo -- /bin/bash
root@ubuntu-shell-demo:/# 

```

Hope this helps :)
