### ISSUE TITLE
Issue with /docs/user-guide/containers/ : docker args use cases for cap-add/cap-drop

### ISSUE THREAD

**Issue by bogdando** [kubernetes/website#2082]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

[Doc](http://kubernetes.io/docs/user-guide/containers/) says "We can have fine grain control over the capabilities using cap-add and cap-drop" but does't explain *how*. And from the table above that doesn't look possible as the `args` stand for `command` args only.

**Proposed Solution:**

* Add examples like
```
      containers:
        - name: foo
          image: docker.io/foo:bar
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
```
* Refer to [podsecuritycontext](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_podsecuritycontext) for more details

**Page to Update:**
http://kubernetes.io/docs/user-guide/containers/

1.5.1

thanks to \@portdirect and \@lihan on k8s slack!
