### ISSUE TITLE
Copy to Clipboard copies with the title 

### ISSUE THREAD

**Issue by harik8** [kubernetes/website#21057]
**This is a Bug Report**

When I click on copy to clipboard it copies with the title
```
pods/resource/cpu-request-limit.yaml

apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: cpu-example
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
```

**Proposed Solution:**
It'd be nice if it's only copies the yaml content.

**Page to Update:**
https://kubernetes.io/...
