### ISSUE TITLE
Additional configuration needed in Multiple Schedulers Tutorial

### ISSUE THREAD

**Issue by zorro786** [kubernetes/website#21293]
**This is a Bug Report**

**Problem:** The [documentation](https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/) provided to run multiple schedulers needs some more configuration to avoid errors in scheduler logs.

```
E0529 17:32:33.296652       1 reflector.go:178] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```

**Proposed Solution:**
`kubectl edit clusterrole system:kube-scheduler`
Add the following list item under rules:

```
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - get
  - watch
```

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

Kubernetes Version: 1.18

Additional Information: It was recommended by @damemi to "create a rolebinding from the SA in your namespace to the extension-apiserver-authentication-reader role"

**Comment by damemi** [comment]
Thanks for reporting this @zorro786!

To clarify my suggestion, based on the error I think that the `my-scheduler.yaml` provided in the docs page needs to add a binding to the `extension-apiserver-authentication-reader` role like so:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-scheduler
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: my-scheduler
  namespace: kube-system
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
```

but I haven't personally tested this yet
