### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/service-topology/

### ISSUE THREAD

**Issue by charlesguo404** [kubernetes/website#21974]
I think this is conflict, really not support for clusterIP ?
```
but this is not supported for ClusterIP Services
```

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  topologyKeys:
    - "kubernetes.io/hostname"
```
