### ISSUE TITLE
Stylesheet does not limit width of <ol> for larger screens

### ISSUE THREAD

**Issue by SaiHarshaK** [kubernetes/website#22042]
**This is a Bug Report**

**Problem:** Stylesheet does not limit width of \<ol> for larger screens. The config details in [kubectl-commands](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#config) overflow its container.  
(I use mozilla firefox if it's required)

**Proposed Solution:**
Find a way to add, "width:52%;" attribute for \<ol> tags in Stylesheet under "@media screen and (min-width: 992px)"

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#config

/kind bug
/language en

I'll try to make a PR to fix this if its fine.

**Comment by sftim** [comment]
I'm not sure that fixing just for `<ol>` elements is the right approach. Maybe fix it for `.body-content > *` or, if there need to be exceptions, `.body-content > *:not(something)`?

**Comment by SaiHarshaK** [comment]
I see. I suggested changing just \<ol> tag previously since the generated stylesheet had mentioned for lot of them individually.
```css
    .body-content h1, .body-content h2 {
        width: 52%;
        clear: both;
    }

    .body-content > h3, .body-content > h4, .body-content > h5, .body-content > h6, .body-content > p, .body-content > ul > li, .body-content > ul > li {
        width: 52%;
    }

    .body-content table {
        width: 52%;
    }

    .body-content .code-block {
        width: 45%;
        float: right;
        clear: right;
    }
```
