### ISSUE TITLE
Set right-to-left direction using CSS

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22731]
**This is a Feature Request**

**What would you like to be added**
Override theme CSS to ensure that right-to-left content is rendered correctly.
(Also, check that this is necessary - it might already be handled in [Docsy](https://www.docsy.dev/) itself).

**Why is this needed**
We need to indicate that some localizations use right-to-left writing direction, rather than the now more common left-to-right orientation.

**Comments**
Example implementation:
```css
body > div { direction: ltr; }
body:lang(ar) > div { direction: rtl; }
body:lang(fa) > div { direction: rtl; }
```

/area web-development
