### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/quality-service-pod/

### ISSUE THREAD

**Issue by seyedk** [kubernetes/website#22980]
**This is a Bug Report**

**Problem:**
The location of qosClass is not correct in the last example, 
```
spec:
  containers:
    ...
    name: qos-demo-4-ctr-1
    resources:
      requests:
        memory: 200Mi
    ...
    name: qos-demo-4-ctr-2
    resources: {}
    ...
  # wrong:
  qosClass: Burstable
```

which is a result of the following command:
```
kubectl get pod qos-demo-4 --namespace=qos-example --output=yaml
```
**Proposed Solution:**
```
spec:
  containers:
    ...
    name: qos-demo-4-ctr-1
    resources:
      requests:
        memory: 200Mi
    ...
    name: qos-demo-4-ctr-2
    resources: {}
    ...
# Correct: the QoS belongs to the status here
status:
  qosClass: Burstable
```

**Page to Update:**
https://kubernetes.io/...
