### ISSUE TITLE
Automated spell check

### ISSUE THREAD

**Issue by rikatz** [kubernetes/website#23254]
**This is a Feature Request**

So here's an idea (I though someone already had it): what if, when submitting a new PR, there's an additional job that detects what's the locale being changed and runs a spell check?

I've been digging into pyspelling and it looks pretty helpful after some tuning. It can be configured per locale/subdirectory, each one can have its own dictionary + maybe a common one (no spell checker can recognize Kubernetes, kubectl, kubelet, and this is a shame :P ) 

It still needs to be verified some specific points, like 'code blocks', or the page metadata (between the -----). I'm just throwing the idea here to see if someone buys it :)

The following is an example of my pyspelling (just testing), but the commented line could be used for a broader verification of a whole locale directory.

```
matrix:
- name: ptbr 
  sources:
  - content/pt/docs/tasks/**/*.md
    #- content/pt/**/*.md
  aspell:
    lang: pt_BR
  dictionary:
    wordlists:
    - dictionary/pt-custom.txt
    - dictionary/kubernetes.txt
    output: build/dictionary/python.dic
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
```

Let me know if you want me to open a Kep, provide more tests, etc etc :)
