### ISSUE TITLE
CronJob Documentation Fails to Create Cron Job

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/website#2325]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The [https://kubernetes.io/docs/user-guide/cron-jobs/](https://kubernetes.io/docs/user-guide/cron-jobs/) guide fails at the first step, which is creating the actual CronJob. 

Here is the error that I'm seeing:

```
$ kubectl create -f cronjob.yaml
error: error validating "cronjob.yaml": error validating data: couldn't find type: v2alpha1.CronJob; if you choose to ignore these errors, turn validation off with --validate=false
```

For reference here is my exact `cronjob.yaml`, which should match exactly what is listed in the example on said page.

```
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

**Proposed Solution:**

I have tried to disable validation as referenced in the above error output, but that doesn't fix the problem. Here's that message:

```
$ kubectl create --validate=false -f cronjob.yaml
error: unable to recognize "cronjob.yaml": no matches for batch/, Kind=CronJob
```

There is a prerequisite in the doc, which states that `batch/v2alpha1` must be explicitly enabled. I believe that it is as here's my output of `kubectl api-versions`:

```
$ kubectl api-versions
apps/v1alpha1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1beta1
autoscaling/v1
batch/v1
batch/v2alpha1
certificates.k8s.io/v1alpha1
extensions/v1beta1
policy/v1alpha1
rbac.authorization.k8s.io/v1alpha1
storage.k8s.io/v1beta1
v1
```

This might be caused by [this issue](https://github.com/kubernetes/kubernetes.github.io/issues/2229), but I am not sure so I posted this bug report.

**Page to Update:**
https://kubernetes.io/docs/user-guide/cron-jobs/

**Kubernetes Version:**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T07:30:54Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
