### ISSUE TITLE
Set Kubelet parameters via a config file

### ISSUE THREAD

**Issue by wssgyyg** [kubernetes/website#23779]
For this doc: https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/

I wonder can we have an example config file here. What I want to do is simple, start kubelet and register it to api-server. 

Thx a lot for any help!

**Comment by tengqm** [comment]
Did you read https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/#generating-a-file-that-contains-the-current-configuration ?
/triage support

**Comment by wssgyyg** [comment]
> Did you read https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/#generating-a-file-that-contains-the-current-configuration ?
> /triage support

@tengqm Thx for reply, actually what I want to do is try to start kubelet by 
`./kubelet --api-servers=127.0.0.1:8080`
But the flag `--api-servers` seems to be deperacated since v1.6.0，so I wonder if there is a way to replace it. I read many docs but    still can't find a solution.

**Comment by tengqm** [comment]
@wssgyyg Maybe you should try `--kubeconfig`?

**Comment by wssgyyg** [comment]
@tengqm Yeah, I copied a config file from another cluster and finally get my kubelet run.

**Comment by wssgyyg** [comment]
For those who read [this](http://kamalmarhubi.com/blog/2015/09/06/kubernetes-from-the-ground-up-the-api-server/) article, use --kubeconfig /path/to/kubeconfig-file to replace --api-servers. Below is an example for kubeconfig file.
```
apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:8080
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
    user: default-auth
  name: default-context
current-context: default-context
kind: Config
preferences: {}
```
