### ISSUE TITLE
Unable to follow Ingress with NGINX task in Katacoda

### ISSUE THREAD

**Issue by dheerujava** [kubernetes/website#24080]
None of the examples given this page run.
I have enabled the nginx addon controller with minikube and trying to run the example given but always get this error
error: unable to recognize "ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1"
Example Code:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
spec:
  defaultBackend:
    resource:
      apiGroup: k8s.example.com
      kind: StorageBucket
      name: static-assets
  rules:
    - http:
        paths:
          - path: /icons
            pathType: ImplementationSpecific
            backend:
              resource:
                apiGroup: k8s.example.com
                kind: StorageBucket
                name: icon-assets
```

This gives Error as no matches for kind "Ingress" in version "networking.k8s.io/v1" . 
Can you please update what is missing in documentation.
