### ISSUE TITLE
Horizontal Pod Autoscaler doc issue

### ISSUE THREAD

**Issue by randallt** [kubernetes/website#24226]
Near the bottom the page
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

> To allow a final drop of 5 pods, another policy can be added and a selection strategy of minimum:

```
behavior:
  scaleDown:
    policies:
    - type: Percent
      value: 10
      periodSeconds: 60
    - type: Pods
      value: 5
      periodSeconds: 60
    selectPolicy: Max
```
Shouldn't the text replace 'minimum' with 'maximum', as specified by the yaml block?
