### ISSUE TITLE
Issue with /docs/user-guide/persistent-volumes/#dynamic

### ISSUE THREAD

**Issue by naisanza** [kubernetes/website#2451]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
With this PV, does it mean if a new Deployment is created with `volume.beta.kubernetes.io/storage-class: ""` it will create new directories in the NFS path `/tmp` for each new PVC?

The documentation mentions about PV's and PVC's, and I want to create dynamic PVC's over an NFS PV. Is that possible?

```
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv0003
    annotations:
      volume.beta.kubernetes.io/storage-class: ""
  spec:
    capacity:
      storage: 1024Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /tmp
      server: 172.17.0.2
```

**Page to Update:**
https://kubernetes.io/docs/user-guide/persistent-volumes/#dynamic
