### ISSUE TITLE
Ingress: Specify the behaviour for path with default value

### ISSUE THREAD

**Issue by pavelgordon** [kubernetes/website#24684]
Given the spec

```
spec:
  rules:
  - host: {{ .Values.ingressPublic.hostname }}
    http:
      paths:
      - backend:
          serviceName: {{ include "service.fullname" . }}
      - path: /anotherservice/
        backend:
          anotherservice: {{ include "anotherservice.fullname" . }}
```

I assume that
```
- backend:
    serviceName: {{ include "service.fullname" . }}
```
is equivalent of

```
- path: /
  backend:
     serviceName: {{ include "service.fullname" . }}
```

But documentation doesnt cover it. Do you think it's a good idea to include it in https://kubernetes.io/docs/concepts/services-networking/ingress/ in `Path types` area?
