### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by amado-saladino** [kubernetes/website#24763]
Ingress file provided does not work, it might be due to difference in versions.
This version works for me:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 8080
          - path: /v2
            backend:
              serviceName: web2
              servicePort: 8080    
```
