### ISSUE TITLE
Dynamic Admission Control || kube-apiserver not coming up after adding --admission-control-config-file flag

### ISSUE THREAD

**Issue by ak89224** [kubernetes/website#24946]
```
root@ubuntu151:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
My admission webhooks require authentication so I'm restarting the apiserver by specifying the location of the admission control configuration file via the --admission-control-config-file flag. Doing as --

```
root@ubuntu151:~# vi /etc/kubernetes/manifests/kube-apiserver.yaml
...
spec:
  containers:
  - command:
     - --admission-control-config-file=/var/lib/kubernetes/kube-AdmissionConfiguration.yaml
...

```

```
root@ubuntu151:~# vi /var/lib/kubernetes/kube-AdmissionConfiguration.yaml

apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: /var/lib/kubernetes/kube-config.yaml
- name: MutatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: /var/lib/kubernetes/kube-config.yaml

```
  kubeConfigFile: /var/lib/kubernetes/kube-config.yaml is the file I copied from ~/.kube/config

Now my kube-apiserver is not coming up .

Please help !

Thanks in Advance !
