### ISSUE TITLE
Can data: in opaque secrets be a map?

### ISSUE THREAD

**Issue by symbiont-ji** [kubernetes/website#25035]
The documentation in https://kubernetes.io/docs/concepts/configuration/secret/ does not mention any restrictions on what kind of structure the `data:` field can have. All examples just show that it is a simple map. If it cannot be a map of maps of lists, etc., please either document it, or give an example of how it can be done. If I try `kubectl edit secret quux` and put this as my `data`:

```yml
data:
  foo: cXV1eA==
  bar:
    - one:
      alice: cXV1eA==
      bob: cXV1eA==
```

the editor rejects it and comes back with the error `# * : Invalid value: "The edited file failed validation": ValidationError(Secret.data.provider): invalid type for io.k8s.api.core.v1.Secret.data: got "array", expected "string"` in a comment.

**Comment by sftim** [comment]
(from the page)
> The values for all keys in the data field have to be base64-encoded strings. 

That seems clear to me @symbiont-ji - did you have some different wording in mind?
/priority awaiting-more-evidence
/language en
/sig apps

**Comment by symbiont-ji** [comment]
I should have said "more than a simple map". This is the sort of thing I
need. If it's not supported, we should document that, too, hopefully with a
reason why it is not supported.


# secrets "foo" was not valid:
# * : Invalid value: "The edited file failed validation":
ValidationError(Secret.data.bar): invalid type for
io.k8s.api.core.v1.Secret.data: got "map", expected "string"
#
apiVersion: v1
data:
 foo: Zm9vCg==
 bar:
   baz: Zm9vCg==
   quux: Zm9vCg==

**Comment by sftim** [comment]
The values for all keys in the `data` field **have** to be (base64-encoded) strings. That's part of how the ConfigMap resource is defined.

You can store a string that is a JSON document, or a TOML document, or a YAML document. But it **must** be a string to Kubernetes.

/triage support

**Comment by tengqm** [comment]
Instead of

```
data:
  foo: cXV1eA==
  bar:
    - one:
      alice: cXV1eA==
      bob: cXV1eA==
```

You will do either:

```
data:
  foo: cXV1eA==
  bar: W3sib25lIjogIiIsICJhbGljZSI6ICJxdXV4IiwgImJvYiI6ICJxdXV4In1d
```

where, `W3sib25lIjogIiIsICJhbGljZSI6ICJxdXV4IiwgImJvYiI6ICJxdXV4In1d` decodes to JSON `[{"one": "", "alice": "quux", "bob": "quux"}]`.

or

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic
stringData:   # using stringData as documented
  foo: quux
  bar: |
    - one:
      alice: quux
      bob: quux
```
