### ISSUE TITLE
Configure a Pod to Use a PersistentVolume for Storage - Wrong yaml definition

### ISSUE THREAD

**Issue by sidhlipu** [kubernetes/website#25821]
Example in the section has errors in the yaml definition. 

Link: https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-pod

`apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
 `

The correct yaml definition would be.

`apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
         name: task-pv-storage
 `

**Comment by tengqm** [comment]
@sidhlipu Pls revise the message so we can understand what is wrong.

**Comment by sidhlipu** [comment]
Hi @tengqm, I see there's indentation issue in the example. 

apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      **- mountPath: "/usr/share/nginx/html"
      *** name: task-pv-storage
[two extra spaces marked by *]

Actually it should be 

apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
         name: task-pv-storage

P.S: Please excuse if my understanding is not correct here.

**Comment by sftim** [comment]
@sidhlipu with your permission, I can use admin edit access to update the description you wrote to show the problem more clearly. Let me know if that's OK.

**Comment by sidhlipu** [comment]
@sftim sure, please

**Comment by tengqm** [comment]
@sidhlipu You may use the three backtiqs (```) before and after your code snippets so we understand what is wrong.

**Comment by sidhlipu** [comment]
Hi @tengqm ,

Putting it in a right format.

```
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage

```

What it should actually would be 

```
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: task-pv-storage
```

**Comment by tengqm** [comment]
Ah, I see, so the confusing lines are the following ones:

```
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: task-pv-storage
```

In YAML, the above indentation is actually VALID. However, I do (personally) prefer an explicit indentation for list items which makes the nesting of things more evident, i.e.

```
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
```

**Comment by sftim** [comment]
Let's make sure that the indentation is consistent between `ports` and `volumeMounts`.

I would either leave that example as-is, or put `name` first for each field that has one:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: task-pv-claim
  containers:
  - name: task-pv-container
    image: nginx
    ports:
    - name: "http-server"
      containerPort: 80
    volumeMounts:
    - name: task-pv-storage
      mountPath: "/usr/share/nginx/html"
```

Diff:
```diff
--- https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/storage/pv-pod.yaml	2019-08-10 06:33:15 +0900
+++ https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/storage/pv-pod.yaml	2021-01-04 08:15:42 +0000
@@ -11,8 +11,8 @@
   - name: task-pv-container
     image: nginx
     ports:
-    - containerPort: 80
-      name: "http-server"
+    - name: "http-server"
+      containerPort: 80
     volumeMounts:
-    - mountPath: "/usr/share/nginx/html"
-      name: task-pv-storage
+    - name: task-pv-storage
+      mountPath: "/usr/share/nginx/html"
```
