### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by ivanruizalcuadrado** [kubernetes/website#25922]
### EXAMPLE INJECT CONFIGMAP IN POD
_Use envFrom
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/_

**Right:**

```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-with-env-configmap
  labels:
    name: use-configmap-env
spec:
  containers:
  - envFrom:
    -configMapRef:
	 name: my-config-map-name
    image: nginx
    name: my-http-server
```
	

**wrong in documentation**

```
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: special-config
```
