### ISSUE TITLE
update Ingress config example to networking.k8s.io/v1beta1 until networking.k8s.io/v1 example supports Ingress kind

### ISSUE THREAD

**Issue by zebralight** [kubernetes/website#25933]
**This is a Bug Report**

**Problem:**  Examples on Ingress page specify version `networking.k8s.io/v1`, but also use kind value of `Ingress`, which is according to [this thread](https://github.com/kubernetes/kubernetes/issues/90077), not yet supported in v1.

**Proposed Solution:** Update example to either 
1) use version of `networking.k8s.io/v1beta1` until `Ingress` is available as a kind on `networking.k8s.io/v1`
2) any other configuration that will not result in an error

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/

example:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```

Kubernetes Version: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
