### ISSUE TITLE
Incorrect description in device-plugins.md

### ISSUE THREAD

**Issue by pokerfaceSad** [kubernetes/website#25938]
**This is a Bug Report**

**Problem:**
In [monitoring-device-plugin-resources](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#monitoring-device-plugin-resources), the description about `/var/lib/kubelet/pod-resources/kubelet.sock` is inaccurate.
```
If a device monitoring agent is running as a DaemonSet, /var/lib/kubelet/pod-resources must be mounted as a Volume in the plugin's PodSpec.
```
The `/var/lib/kubelet/pod-resources/kubelet.sock` should be mounted in device monitoring agent pod but not device plugin pod.

For an instance, the [nvidia dcgm exporter](https://github.com/NVIDIA/gpu-monitoring-tools) is a device monitor agent. The `/var/lib/kubelet/pod-resources` is mounted as a volume in it PodSpec.
[dcgm-exporter.yaml#L50-L57](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/dcgm-exporter.yaml#L50-L57)
```
      ...
        volumeMounts:
        - name: "pod-gpu-resources"
          readOnly: true
          mountPath: "/var/lib/kubelet/pod-resources"
      volumes:
      - name: "pod-gpu-resources"
        hostPath:
          path: "/var/lib/kubelet/pod-resources"
      ...
```
**Proposed Solution:**
I have submited a PR #25937 
**Page to Update:**
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#monitoring-device-plugin-resources
