### ISSUE TITLE
[problem solved] How to make all nodes authenticated to a private registry by kubectl on a remote ECS

### ISSUE THREAD

**Issue by Bamzhy** [kubernetes/website#26426]
### This is just a footnote, mainly based on the situation I met
- After installing the kuberctl and getting connected to the kubernetes cluster
    - Make sure `kubectl get nodes` works
- I finish the deployment.yaml, and excute `kubectl apply -f deployment.yaml`  command
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME
spec:
  selector:
    matchLabels:
      app: APP
  template:
    metadata:
      labels:
        app: APP
    spec:
      containers:
      - name: NAME
        image: NAME:TAG
```
- But the pod didn't work, and it throw out an error `Error: ImagePullBackOff`
- The next step should be create your own secret
    - Login in to the private docker registry
       -  `docker login --username USE_RNAME REPO_ADDRESS` then type in password
    - Create you own secret `kubectl create secret docker-registry SECRET_NAME ...`  [click it to get more details](https://kubernetes.io/docs/concepts/configuration/secret/)
    -  **After you created the secret, it will be transfered to all nodes**
- Use the secret you just generated by this field `imagePullSecrets`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME
spec:
  selector:
    matchLabels:
      app: APP
  replicas: 1
  template:
    metadata:
      labels:
        app: APP
    spec:
      containers:
      - name: NAME
        image: NAME:TAG
      imagePullSecrets:
      - name: SECRET_NAME
``` 
- **Make sure image's name and tag is absolutely corrent**
    - This is a silly mistake and I've been stuck here for a long time 
- Then `kubectl apply -f deployment.yaml`

### I hope this helps
