### ISSUE TITLE
Configuration file(s) and config document schemas would be very helpful

### ISSUE THREAD

**Issue by robtayl0r** [kubernetes/website#26445]
**This is a Feature Request**

**What would you like to be added**
A reference to yaml config file structures, specifically from within the kubeadm reference pages. More specifically the `kind: InitConfiguration` and `kind: ClusterConfiguration` blocks. But finding a reference to any structures has proven very difficult. 

**Why is this needed**
Perhaps it's because I'm new to kubeadm and k8s, but it's proven very difficult to find a schema of these config structures. The output of `kubeadm config print join-defaults` has a structure that seems to differ from that of the kubeadm [join command](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#options) reference page. 

i.e. print join-defaults
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: kube-apiserver:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: abcdef.0123456789abcdef
kind: JoinConfiguration
```

`discovery.bootstrapToken.token` but `--discovery-token` is listed on the reference page. Not sure if these are even. synonymous, but, just an example. 

I also notice `nodeRegistration` key in both JoinConfiguration and InitConfiguration defaults. How do these relate or how does one take precedence over the other? Is there a place to reference these keys and the schemas of these different configuration ("kind" key) yaml documents?

**Comments**
