### ISSUE TITLE
Improve apiserver proxy url resource location port filter

### ISSUE THREAD

**Issue by derektamsen** [kubernetes/website#26443]
**This is a Feature Request**

**What would you like to be added**

The [documentation for manually constructing apiserver proxy URLs](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/access-application-cluster/access-cluster.md#manually-constructing-apiserver-proxy-urls) is lacking clarity that both the port name or port number can be used when proxying to a service. The documentation should mention the field represented by `<port_name>` can either be the name of a port in a service or the port number of a service for both forms `<service_name>:<port_name>` and `https:<service_name>:<port_name>`.

**Why is this needed**
The apiserver proxy endpoint `ResourceLoction()` supports using either a [port name or a port number](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/service/storage/rest.go#L528-L543) to locate the service to proxy to.

The alternative form of using the port number could be useful if migrating from an unnamed/default service port to a named service port.

***Example:***
The following api server request could be used to proxy either form of the following service object since it references the port number, `8080`. If the query was constructed as `http:sealed-secrets-controller:`, only the unnamed port would return a result. Conversely, if `http:sealed-secrets-controller:http` was used in the query only the named port would return a result.
```
http://127.0.0.1:8080/api/v1/namespaces/sealed-secrets/services/http:sealed-secrets-controller:8080/proxy/v1/cert.pem
```
default/unnamed:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sealed-secrets-controller
    app.kubernetes.io/instance: sealed-secrets-local
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sealed-secrets-controller
  sessionAffinity: None
  type: ClusterIP
```
named:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sealed-secrets-controller
    app.kubernetes.io/instance: sealed-secrets-local
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sealed-secrets-controller
  sessionAffinity: None
  type: ClusterIP
```

**Comments**
