### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/labels/

### ISSUE THREAD

**Issue by nikhilbagdi** [kubernetes/website#26460]
**This is an Information Suggestion**

**Information should be made available on Web Page**

URL: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ 

**Service with set-based labels**
If we're using set-based labels in our deployment file then it is not possible to expose them, as `Service` does not support set-based selectors. For example, if we're using
```
selector:
  matchExpresssions:
  - key: type
    operator: In
    values: 
    - prod
```
Then we cannot expose it using `Service`. It only supports equality-based labels.

**Why is this needed**
To clarify that `Service` does not support Set-Based Labels

**Comment by sftim** [comment]
Hi @nikhilbagdi 

This sounds like it could describe a worthwhile improvement, but I'm worried that contributors might not be able to understand the issue description as it stands. Can you add some more description so that a person who picks this up is confident about the change they should make to get this fixed?

/language en
/triage needs-information

**Comment by nikhilbagdi** [comment]
**Expose using Set-Based Selector**
Suppose, we are deploying a basic deployment of Nginx. At first, while deploying we're using Equality-Based Selector like
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: nginx-pod
      labels:
        tier: frontend
    spec:
      containers:
      - image: nginx:latest
        name: nginx-container
```
Here we have used an equality-based selector of  `tier: frontend`. When we describe our deployment using the `kubectl describe` command we'll notice that the field `Selector` is `tier=frontend`
If we want to expose it using `Service` then we can do it using an imperative command like 
`kubectl expose deploy/nginx-deployment --port=80 --type=NodePort`
Or we can also expose it using a declarative file. E.g.
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: service
spec: 
  type: NodePort
  selector:
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
```
When we describe the service using the command `kubectl describe service/nginx-service`, we can observe that the service is successfully connected with the `Pod` which has the labels `tier=frontend`.
Note: Here, in `Service` we can only use an equality-based selector under the `spec.selector` field. We can not use a set-based selector.
**Now, the question arises that what if our deployment has a set-based selector?** Like
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: deployment
spec:
  replicas: 1
  selector:
    matchExpressions:
    - key: tier
      operator: In
      values:
      - frontend
  template:
    metadata:
      name: nginx-pod
      labels:
        tier: frontend
    spec:
      containers:
      - image: nginx:latest
        name: nginx-container
```
When we describe using the `kubectl describe` command we'll notice that the `Selector` is `tier in (frontend)`.
We can not expose it using the `Service` declarative file as it does not support a set-based selector as the `Deployment` declarative file does. Also, we can not expose using the imperative command as the `--selector` option only supports equality-based selector.
