### ISSUE TITLE
Questions about configuring kube-scheduler in "Scheduler Configuration" section

### ISSUE THREAD

**Issue by Alpenbelieve** [kubernetes/website#26762]
Hello, I've been learning Kubernetes for a while and recently wanted to implement a custom scheduler.
And there're 4 ways to achieve:
1. clone and modify source code
2. run a separate scheduler along with default scheduler
3. scheduler extender
4. **scheduling framework (recommend)**

When I'm working on the 4th method, I find [Scheduler Configuration](https://kubernetes.io/docs/reference/scheduling/config/). It says:

> For each extension point, you could disable specific default plugins or enable your own. For example:
```apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
profiles:
  - plugins:
      score:
        disabled:
        - name: NodeResourcesLeastAllocated
        enabled:
        - name: MyCustomPluginA
          weight: 2
        - name: MyCustomPluginB
          weight: 1
```

This means we can use default plugins or **plugins implemented by ourselves** to configure different stages of scheduling in the kube-scheduler. In the code snippet above, a default plugins is disabled and two custom plugins are enabled during **score** extension point.

However, I searched a lot but failed to find any ways to implement a plugin, which can configure the default scheduler. Is there any ways to achieve this? Thanks : )

**Comment by Alpenbelieve** [comment]
I know that the common way is to use Scheduling Framework to write a custom scheduler, and register some plugins on extension points.

Following is an example: (comes from [this repo)](https://github.com/NJUPT-ISL/Yoda-Scheduler/blob/855e9d6812b80a1aadc89c5a9460e380776dd62b/deploy/yoda-scheduler.yaml#L21)

```
    kind: KubeSchedulerConfiguration
    profiles:
      - plugins:
          filter:
            enabled:
              - name: yoda
                weight: 0
          score:
            enabled:
              - name: yoda
                weight: 300
        schedulerName: yoda-scheduler2
```
The author use Scheduling Framework to write a scheduler called "yoda-scheduler2", and register a plugin called "yoda" on filter and score extension point to achieve custom schedule logic.

Implementing a scheduler by myself would be more flexible, but I'm wondering whether it is feasible to implement a plugin and use it to control the scheduling process of the default scheduler?
