### ISSUE TITLE
Mention .ttlSecondsAfterFinished in CronJob concept page

### ISSUE THREAD

**Issue by agnesjang98** [kubernetes/website#26917]
Can this mechanism be used for CronJobs as well?
https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/

**Comment by sftim** [comment]
/kind support

I'm not clear on what a “finished” CronJob would look like. CronJobs define a pattern for repeatedly invoking a job.

**Comment by agnesjang98** [comment]
Would it be possible to set this for the invoked jobs that were created by the CronJob? We have some problems where the pods that are created by the invoked jobs get stuck in bad state (e.g ImagePullBackOff) and we want to kill those jobs after a certain period of time to prevent them from blocking the invocation of new jobs. Our current workaround is to delete the bad jobs manually, but we were hoping to use this to automatically delete invoked jobs after a period of time.

**Comment by sftim** [comment]
There's a trick mentioned in https://github.com/kubernetes/kubernetes/issues/829#issuecomment-51796318

@agnesjang98 maybe we could document this in the page about Job / CronJob?

**Comment by agnesjang98** [comment]
I'll try defining activeDeadlineSeconds and yes some documentation would be nice about the trick? I wasn't completely sure how to progress with the workaround you linked, will look over it again.

**Comment by agnesjang98** [comment]
Putting ttlSecondsAfterFinished in the jobTemplate spec for specifying the Job invoked by the CronJob works! It would be helpful to add this in the documentation :)

Part of our cronjob.yaml as an example:
```
...
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: 
  namespace: 
spec:
  concurrencyPolicy:
  startingDeadlineSeconds: 
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ $job.ttlSecondsAfterFinished | default 120 }}
...
```
