### ISSUE TITLE
Tried Dynamic Configuration but failed at kubelet did not checkpoint configMap

### ISSUE THREAD

**Issue by chiwenchen** [kubernetes/website#27119]
version:
```
Client Version: v1.19.3
Server Version: v1.17.8
```

I follow the step in this document trying to change the value of `imageGCHighThresholdPercent` and `imageGCLowThresholdPercent`, and I exam the result by check if the config map in on cluster, and it did shows up at the latest one
```
kubectl -n kube-system get configmaps

NAME                                 DATA   AGE
calico-config                        4      58d
extension-apiserver-authentication   6      58d
kops-controller                      1      58d
kops-controller-leader               0      58d
kube-dns-autoscaler                  1      58d
my-node-config-2f7hf95dg8            1      47h
```

and then I check if I correctly config the node to use the new config map by issuing command below
```
kubectl get no MY_NODE_NAME -o yaml

...
spec:
  configSource:
    configMap:
      kubeletConfigKey: kubelet
      name: my-node-config-2f7hf95dg8
      namespace: kube-system
  podCIDR: 100.96.2.0/24
  podCIDRs:
  - 100.96.2.0/24
...
```
I did see the spec.configSource, but I did not see the expected `.status.config`.
I also tried to restart the kubelet, but still nothing happened, can anyone helps to find what I missed, many appreciate.

As quoted from official doc, it seems like kubelet did not notice the configMap is updated, hence it did not trigger the checkpoints action and everything just stop there.
> Each Kubelet watches its associated Node object for changes. When the Node.Spec.ConfigSource.ConfigMap reference is updated, the Kubelet will "checkpoint" the new ConfigMap by writing the files it contains to local disk.
