### ISSUE TITLE
Change supported Windows OS version support table in docs to reference a .yaml file in another repo

### ISSUE THREAD

**Issue by marosset** [kubernetes/website#27222]
**This is a Feature Request**

Update how https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support gets populated so we don't need to make PRs to kubernetes/website to update this tabel.

**Comments**

@neolit123 suggested keeping a .yaml file in one of the kubernets-sigs repo and pulling data from that.

/sig windows

**Comment by sftim** [comment]
If we keep that YAML file in another repo, is there a reason why that's better than keeping it in this repo? I'm imagining that maintenance would be fairly similar.

We can use [Hugo data](https://gohugo.io/templates/data-templates/) to make a shortcode that renders as the version support table. (My gut feeling is that maintaining a Markdown table is about as much effort, though).

If we use YAML and it's in _this_ repo, we can do CI checks on changes to only allow valid updates.

**Comment by marosset** [comment]
I think it would be fine to keep it in this repo too.

**Comment by neolit123** [comment]
two minor downsides that i see of using k/website are:
- machine readable consumers of the YAML might wonder this file lives in the website repository.
- requires approval from k/website owners for changes on this rather technical aspect maintained by SIG Windows (version additions).

> We can use Hugo data to make a shortcode that renders as the version support table. (My gut feeling is that maintaining a Markdown table is about as much effort, though).

if this would be only for human readers a markdown file would suffice.
i have a wild guess that someone might want to know to automate their infrastructure provisioning (VMs) based on the k8s version.

for non-humans there has to be a minimal API here - e.g.:
```
- kubernetesVersion: 1.17
  windowsLTSVersions:
  - windows-server-2019
  windowsSACVersions:
  - windows-server-1809
- kubernetesVersion: 1.18
  windowsLTSVersions:
  - windows-server-2019
  windowsSACVersions:
  - windows-server-1809
  - windows-server-1903
  - windows-server-1909
...
```

my vote would be to have the file machine readable in something like:
https://sigs.k8s.io/sig-windows-tools/supported-versions/supported-versions.yaml

and import it on the k/website page with Hugo data.

if machine readable is too much at this stage, my vote would to have the file in:
https://sigs.k8s.io/sig-windows-tools/supported-versions/supported-versions.md
