### ISSUE TITLE
Horizontal Pod Autoscaler Walkthrough

### ISSUE THREAD

**Issue by JulesBelveze** [kubernetes/website#27527]
Hey guys,
I am trying to use the `LabelSelector` within an external metric, as shown in the docs:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
   ...
      external:
        metric:
          name: kubernetes.io|container|accelerator|duty_cycle
          selector: "resource.labels.container_name=classifier"
```
but I'm running into the following issue:
```
error: error validating "classifier_hpa.yaml": error validating data: ValidationError(HorizontalPodAutoscaler.spec.metrics[0].external.metric.selector): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector: got "string", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false
```
Any idea how I could potentially solve that?

Cheers!
