### ISSUE TITLE
Guide for scheduling Windows containers in Kubernetes - Wrong apiVersion (Runtimeclass)

### ISSUE THREAD

**Issue by marciogmorales** [kubernetes/website#27738]
The following Runtimeclass is not part of the api: **node.k8s.io/v1**

```
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: windows-2019
handler: 'docker'
scheduling:
  nodeSelector:
    kubernetes.io/os: 'windows'
    kubernetes.io/arch: 'amd64'
    node.kubernetes.io/windows-build: '10.0.17763'
  tolerations:
  - effect: NoSchedule
    key: os
    operator: Equal
    value: "windows"
```

Change it for: **node.k8s.io/v1beta1**
