### ISSUE TITLE
Kubeadm documentation example for customizing the control plane with scheduler flags is misleading and results in a broken scheduler if used as written

### ISSUE THREAD

**Issue by adamnovak** [kubernetes/website#27816]
**This is a Bug Report**

**Problem:**

The example at https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md#scheduler-flags shows `scheduler.extraArgs.config` in the `ClusterConfiguration` being used without `scheduler.extraVolumes`. Because `kubeadm` (by default?) sets up the scheduler to run inside a pod, it is necessary to use `scheduler.extraVolumes` to mount the config file into the pod. Using the example as given will cause the scheduler to fail to start, even if the referenced config file exists on the host.

It is also not mentioned here that providing a config file (now?) causes the scheduler to ignore several of the flags (like `--kubeconfig` and `--port`) that kubeadm sets the scheduler up with, so any config file passed needs to duplicate those settings if the scheduler is to work as kubeadm intends. In particular, without setting a `clientConnection.kubeconfig`, the scheduler will not come up.

This documentation is especially important because `kubectl logs` doesn't necessarily work before the scheduler can schedule enough Kubernetes components to start up TLS, so it can be nearly impossible to debug what is wrong with a non-working scheduler pod without a lot of documentation.

**Proposed Solution:**

A working example that lets the scheduler come up with a nontrivial configuration change seems to be:

Scheduler config file on host in e.g. `/home/core/scheduler-config.yml`:
```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
  - schedulerName: default-scheduler
    plugins:
      score:
        disabled:
        - name: NodeResourcesLeastAllocated
        enabled:
        - name: NodeResourcesMostAllocated
          weight: 1
```

Config file for `kubeadm init` to point to and mount it:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
scheduler:
  extraArgs:
    config: "/etc/kubernetes/scheduler-config.yml"
  extraVolumes:
    - name: schedulerconfig
      hostPath: "/home/core/scheduler-config.yml"
      mountPath: "/etc/kubernetes/scheduler-config.yml"
      readOnly: true
      pathType: "File"
```

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#scheduler-flags

Kubernetes Version: 1.19.3

**Comment by neolit123** [comment]
> Because kubeadm (by default?) sets up the scheduler to run inside a pod

no other ways are supported.

> It is also not mentioned here that providing a config file (now?) causes the scheduler to ignore several of the flags (like --kubeconfig and --port) that kubeadm sets the scheduler up with, so any config file passed needs to duplicate those settings if the scheduler is to work as kubeadm intends. In particular, without setting a clientConnection.kubeconfig, the scheduler will not come up.

i can see how the kubeadm example may be bogus in that regard.
if scheduler config overrides flags that is an artifact of the kube-scheduler. normally flags should override config, or the mixture should just error out.

> This documentation is especially important because kubectl logs doesn't necessarily work before the scheduler can schedule enough Kubernetes components to start up TLS, so it can be nearly impossible to debug what is wrong with a non-working scheduler pod without a lot of documentation.

if some kube-scheduler specifics are not documented they should go here:
https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/
or here:
https://kubernetes.io/docs/reference/scheduling/config/

kubeadm just allows you to configure it and i don't think we should special case the component a lot here:
https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md#scheduler-flags

having the following minimal example makes sense to me:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
scheduler:
  extraArgs:
    config: /home/johndoe/schedconfig.yaml
  extraVolumes:
    - name: schedulerconfig
      hostPath:  /home/johndoe/schedconfig.yaml
      readOnly: true
      pathType: "File"
```

> For details, see the reference documentation for kube-scheduler.

^ this sentence can also be extended to link to https://kubernetes.io/docs/reference/scheduling/config/

/sig cluster-lifecycle scheduling
/triage accepted

scoped, minimal PRs are welcome.
