### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

### ISSUE THREAD

**Issue by anasalloush** [kubernetes/website#27931]
Hi,

In this document, In this section
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#kubelet-serving-certs

It is mentioned that in order to make the metrics-server works probably, you have to edit the ConfigMap as shown

```
If you have already created the cluster you must adapt it by doing the following:

Find and edit the kubelet-config-1.21 ConfigMap in the kube-system namespace. In that ConfigMap, the config key has a KubeletConfiguration document as its value. Edit the KubeletConfiguration document to set serverTLSBootstrap: true.
```
But in a kubeadm deployed cluster, there is no `config `key in the `kubelet-config-1.21` ConfigMap ..
There is this:
```
 data:
    kubelet: |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
```
Which you can not edit as described in the document.
The metrics-server is not working due to this issue..
