### ISSUE TITLE
Taints and Tolerations

### ISSUE THREAD

**Issue by shmelkin** [kubernetes/website#28029]
In the tutorial section, it is mentioned that one can allow scheduling of pods on the control plane node by executing 
 kubectl taint nodes --all node-role.kubernetes.io/master-
However, I'm still unable to schedule a pod on the control plane node after executing this command.

The third replica is failing either because of the antiAffinity or since the hostPort 80 is already taken.
Any suggestions?

Im Using
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
kubectl get nodes
```
NAME         STATUS   ROLES                  AGE    VERSION
kubecloud1   Ready    control-plane,master   163m   v1.21.1
kubecloud2   Ready    <none>                 163m   v1.21.1
kubecloud3   Ready    <none>                 163m   v1.21.1
```
kubectl get all
```
NAME                              READY   STATUS    RESTARTS   AGE
pod/springboot-69df4f9954-56gj8   1/1     Running   0          115s
pod/springboot-69df4f9954-pdlp4   0/1     Error     4          115s
pod/springboot-69df4f9954-zj6fg   1/1     Running   0          115s

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1        <none>        443/TCP   160m
service/springboot   ClusterIP   10.104.154.228   <none>        80/TCP    115s

NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/springboot   2/3     3            2           115s

NAME                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/springboot-69df4f9954   3         3         2       115s


```

kubectl get pods -o wide
```
NAME                          READY   STATUS             RESTARTS   AGE     IP              NODE         NOMINATED NODE   READINESS GATES
springboot-69df4f9954-56gj8   1/1     Running            0          4m50s   172.26.63.206   kubecloud2   <none>           <none>
springboot-69df4f9954-pdlp4   0/1     CrashLoopBackOff   5          4m50s   172.26.63.207   kubecloud3   <none>           <none>
springboot-69df4f9954-zj6fg   1/1     Running            0          4m50s   172.26.63.207   kubecloud3   <none>           <none>


```
deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - springboot
            topologyKey: job
      containers:
      - name: springboot-container
        image: shmelkin/dissertation
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: springboot
```
