### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/

### ISSUE THREAD

**Issue by josp70** [kubernetes/website#28203]
Is startupProbe not available on windows container? If that is the case could it be explicitly stated on that page (issue subject)?

**Comment by HongjiangHuang** [comment]
> Is startupProbe not available on windows container
How did you come to this conclusion

**Comment by josp70** [comment]
> > Is startupProbe not available on windows container
> 
> How did you come to this conclusion

(Thanks fo the attention to this request)

This question arise after a request we summited to AWS (eks cluster) support. As a summary, we have configured startupProbe, readinessProbe and livenessProbe for a given deployment, and we have observed the readinessProbe and livenessProbe started as if no startupProbe were configured.

It's worth to mention this is done for a windows deployment.

Part of the resolution of the request from AWS was that the startupProbe is not implemented for windows containers and part of the explanation is that in the page https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/  only makes reference to readinessProbe & livenessProve (no explicit reference startupProbe is done)

> The following Pod capabilities, properties and events are supported with Windows containers:
>
> - Single or multiple containers per Pod with process isolation and volume sharing
> - Pod status fields
> - **Readiness and Liveness probes**
> - postStart & preStop container lifecycle events
> - ConfigMap, Secrets: as environment variables or volumes
> - EmptyDir
> - Named pipe host mounts
> - Resource limits

The server version is:
```
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by HongjiangHuang** [comment]
Hello, bro ~
The source code does not distinguish between windows.
And there is no big difference between LivenessProbe and StartupProbe implementation, so I don't think it's not supported by windows container, you can provide a rough deployment config(YAML) as a reference?

https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/kubelet/prober/prober.go#L91

https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/kubelet/prober/prober.go#L156

**Comment by HongjiangHuang** [comment]
It is worth mentioning that the related documentation has not been updated since this [PR](https://github.com/kubernetes/website/pull/13174)

**Comment by josp70** [comment]
> Hello, bro ~ @josp70
> The source code does not distinguish between windows.
> And there is no big difference between LivenessProbe and StartupProbe implementation, so I don't think it's not supported by windows container, you can provide a rough deployment config(YAML) as a reference?
> 
> https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/kubelet/prober/prober.go#L91
> 
> https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/kubelet/prober/prober.go#L156

Here you can see the deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cm-sit
  name: myserver
  labels:
    app: myserver
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: myserver
  template:
    metadata:
      labels:
        app: myserver
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: myserver
          image: myserver-xx:sit
          args: ["-UseThisLookup", "$(LOOKUP_URI)", "-Environment", "qa", "-Settings", "env-settings", "-Run"]
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "4Gi"
          startupProbe:
            initialDelaySeconds: 90
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 1
            tcpSocket:
              port: service
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5
            tcpSocket:
              port: service
          # livenessProbe:
          #   initialDelaySeconds: 120
          #   failureThreshold: 3
          #   periodSeconds: 10
          #   exec:
          #     command:
          #       #- "scripts/healthz.ps1"
          #       - powershell
          #       - "scripts/healthz.ps1"
          #       - "-ServiceHost"
          #       - "127.0.0.1"
          #       - "-ServicePort"
          #       - "8704"
          #       - "-Timeout"
          #       - "5"
          ports:
            - name: service
              containerPort: 8704
            - name: trace
              containerPort: 3173
          env:
            - name: LOOKUP_URI
              valueFrom:
                configMapKeyRef:
                  key: lookup-uri
                  name: env-settings
          volumeMounts:
            - name: settings
              mountPath: C:/service/settings
          imagePullPolicy: Always
      volumes:
        - name: settings
          configMap:
            name: env-settings
      imagePullSecrets:
      - name: us-east-1-ecr-registry
```

Thanks!
