### ISSUE TITLE
Improvement for k8s.io/docs/tasks/run-application/run-replicated-stateful-application/

### ISSUE THREAD

**Issue by iampronoy** [kubernetes/website#28334]
For completeness of the document, please describe the related storage class configuration/yaml to support the below pvc:
```
 volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
```
