### ISSUE TITLE
Certificate Signing Requests not filling the status.certificate section

### ISSUE THREAD

**Issue by dpstratascale** [kubernetes/website#28450]
Hello, 

I am following the procedure on how to create a csr, and the procedure seems to be going smoothly and without any issue, but when I run the following command `kubectl get csr/appname-iwh.ns -o yaml` the result that I'm getting back is the following: 

```
    "status": {
        "conditions": [
            {
                "lastTransitionTime": "2021-06-16T20:09:09Z",
                "lastUpdateTime": "2021-06-16T20:16:04Z",
                "message": "This CSR was approved by kubectl certificate approve.",
                "reason": "KubectlApprove",
                "status": "True",
                "type": "Approved"
            }
        ]
    }
```

my cluster is deployed on a private network that I'm connected to using a VPN.

I am running all the commands to create the .pem and .csr files manually on an ubuntu Linux machine.

There is no outstanding error and I'm approving the certificate with the following command 

`kubectl certificate approve appname-iwh.ns`

My concern is that I'm running the same script on a different cluster and it works just fine, the cluster that has no problem is hosted on AWS, and orchestrated with Rancher, while the cluster that is giving me the problem is deployed on a server and orchestrated by rancher.

Thank you very much for looking into this.

**Comment by jihoon-seo** [comment]
Hello @dpstratascale .
Did you referenced https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/ page?

**Comment by sftim** [comment]
This looks to me more like a request for advice

/kind support

**Comment by dpstratascale** [comment]
Sorry for the late update. After some additional testing, it seems that the version of Kubernetes causes the issue. 
If we use Kubernetes v1.19+ (eks cluster) with certificates.k8s.io/v1 the certificates are approved but not generated. 
another cluster (aks) running Kubernetes version 1.18.19 with certificates.k8s.io/v1beta1 generates and approves the certs without any issue.

The EKS cluster used to work perfectly fine when running version 1.17 (we were using the following apiVersion:certificates.k8s.io/v1beta1)

These are the scripts we use to generate the certificate signing request and approve it: 

1. we generate the keys

```
  cat <<EOF | cfssl genkey - | cfssljson -bare iwh
{
  "CN": "system:node:${NAMESPACE}-iwh.kiab.svc.cluster.local",
  "hosts": [
    "${NAMESPACE}-iwh.kiab.svc",
    "${NAMESPACE}-iwh.kiab.svc.cluster",
    "${NAMESPACE}-iwh.kiab.svc.cluster.local"
  ],
  "names" : [{
    "O": "system:nodes"
  }],
  "key": {
    "algo": "ecdsa",
    "size": 256
  }
}
EOF
```

2. We generate the signing request 

```
cat <<EOF | ${kubectlcmd} apply -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ${NAMESPACE}-iwh.kiab
spec:
  request: $(cat iwh.csr | base64 | tr -d '\n')
  signerName: kubernetes.io/kubelet-serving
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
```

3. We approve the certs 

`kubectl certificate approve ${NAMESPACE}-iwh.kiab
`
the process should be very simple and straightforward and it works with a Kubernetes cluster running version 1.17 - 1.18

The only difference when running older version is that on step 2 we use this snippet of code to create the signing request

```
cat <<EOF | ${kubectlcmd} apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: ${NAMESPACE}-iwh.kiab
spec:
  request: $(cat iwh.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
```
The ${kubectlcmd} stands for kubectlcmd="/usr/local/bin/kubectl"

With these information anyone should be able to simulate the issue
