### ISSUE TITLE
Wrong data docs/reference/access-authn-authz/rbac.md

### ISSUE THREAD

**Issue by behradeslamifar** [kubernetes/website#28741]
**This is a Bug Report**

**Problem:**
in "Rolebinding examples" wrong example exist:
For all service accounts in the "dev" group in the "development" namespace:
```
subjects:
- kind: Group
  name: system:serviceaccounts:dev
  apiGroup: rbac.authorization.k8s.io
  namespace: development
```

Service account cant be in dev group and created in development namespace at the same time. 

**Proposed Solution:**
Remove example

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/rbac/
