### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/persistent-volumes/

### ISSUE THREAD

**Issue by sgpinkus** [kubernetes/website#28832]
[Docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1) state:

> If the admission plugin is turned off, there is no notion of a default StorageClass. All PVCs that have no storageClassName can be bound only to PVs that have no class. In this case, the PVCs that have no storageClassName are treated the same way as PVCs that have their storageClassName set to "".

I don't think this is true. The following `storageClassName`-less PVC successfully binds to the `storageClassName`-ful PV:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    name: local-pv-1
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #
  storageClassName: local-storage
    path: /mnt/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    name: busybox
spec:
  hostname: busybox1
  subdomain: default-subdomain
  containers:
    - name: busybox
      image: busybox:latest
      command:
        - sleep
        - "3600"
       - mountPath: /mnt/local
         name: local-storage-1
  volumes:
    - name: local-storage-1
      persistentVolumeClaim:
        claimName: my-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
spec: 
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: local-pv-1
```
