### ISSUE TITLE
Questions about the YAML Block Sequences indent style

### ISSUE THREAD

**Issue by chenzhiwei** [kubernetes/website#29603]
In the Kuberentes website, there are various yaml example content, they have two styles of block sequences.

1. Indent with two spaces

    ```
    block-sequences:
      - one
      - two
    ```

2. Indent with zero space

    ```
    block-sequences:
    - one
    - two
    ```

In different kubernetes.io pages, the styles are different, and I also found that there are two styles in a single yaml block, like this page: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

The `ports` child has two spaces indent, but the `ingress` child has zero space:

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  clusterIP: 10.0.171.239
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
```

I know both styles are ok, but can someone provide a guideline about which one is preferred?

I think it worth the effort to unify the yaml styles on all Kubernetes website pages.

In the official YAML Spec website and other community style guides, seems two spaces indent of block sequences is the preferred style.

* https://yaml.org/spec/1.2/#id2797382
* https://developers.home-assistant.io/docs/documenting/yaml-style-guide/#block-style-sequences
* https://github.com/flathub/flathub/wiki/YAML-Style-Guide
