### ISSUE TITLE
CronJob example may be incorrect or misleading?

### ISSUE THREAD

**Issue by ismith** [kubernetes/website#29731]
**This is a Bug Report**

**Problem:**
The CronJob page has [an example](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax) of cron syntax that includes an optional timezone.

However, attempting to create a cronjob with `CRON_TZ=UTC` causes a validation error:
```
Error: CronJob.batch "[redacted" is invalid: spec.schedule: Invalid value: "CRON_TZ=UTC 15 20 * * 1": Expected exactly 5 fields, found 6: CRON_TZ=UTC 15 20 * * 1

```

This is from a spec like:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: [redacted]
  namespace: [redacted]
spec:
  # Monday, 20:15 UTC
  schedule: "15 20 * * 1"
  jobTemplate:
[...]
```

**Proposed Solution:**
Seems like that ASCII art diagram, while useful, refers to a timezone feature that the cronjob controller doesn't support?  The diagram would be fine with just that one element removed.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs

Kubernetes Version: 1.21
