### ISSUE TITLE
Using Admission Controllers - EventRateLimit

### ISSUE THREAD

**Issue by serewicz** [kubernetes/website#29741]
This admission controller is now stable as found with the v1 designation in the YAML example below. Just need to remove FEATURE STATE: Kubernetes v1.13 [alpha]
![test drawio](https://user-images.githubusercontent.com/7537557/133853352-72a13714-1f24-4481-b04f-0983a33a4ebc.png)

**Comment by Shubham82** [comment]
Hi @serewicz 
The apiVersion `apiserver.config.k8s.io/v1`  is for ` AdmissionConfiguration` not for **EventRateLimit**.
See the `eventconfig.yaml` file in the docs after that, which look like below one:

```
apiVersion: eventratelimit.admission.k8s.io/v1alpha1
kind: Configuration
limits:
- type: Namespace
  qps: 50
  burst: 100
  cacheSize: 2000
- type: User
  qps: 10
  burst: 50
```
