### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by philanton** [kubernetes/website#29856]
Hi. I pass this tutorial for a few hours, because ingress didn't work and every time I received 404 err.
I'm using minikube (v1.23.0) on Arch Linux.
I finally went to this page https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/ and realized that row below  wasn't in example-ingress.yaml:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"

All work fine after I inserted it.

**Comment by sftim** [comment]
BTW https://github.com/kubernetes/website/pull/29206 is an open PR targeting that page

**Comment by philanton** [comment]
@sftim Without that row it doesn't work for me, I tried about anything

**Comment by niteshseram** [comment]
I don't think it will work without that. If you want you can try with the below config where I changed `kubernetes.io/ingress.class`  to  `ingressClassName`.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservicea
spec:
  ingressClassName: nginx
  rules:
  - host: myservicea.foo.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myservicea
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myserviceb
spec:
  ingressClassName: nginx
  rules:
  - host: myserviceb.foo.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myserviceb
            port:
              number: 80
```

I don't have much idea about Kubernetes but reading through the docs here https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#putting-it-all-together, I found out we can use  `ingressClassName` in place of `kubernetes.io/ingress.class` if I am not wrong.
