### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/system-metrics/

### ISSUE THREAD

**Issue by jotavar** [kubernetes/website#30073]
The described role is not enough to be able to invoke the kubelet metrics endpoint (https://<node_IP>:10250/metrics):

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
```

With this role you get the following:

```
Forbidden (user=system:serviceaccount:default:default, verb=get, resource=nodes, subresource=metrics)
```

I tested with this role instead and it works:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/metrics"]
    verbs: ["get"]
```
