### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

### ISSUE THREAD

**Issue by MPParsley** [kubernetes/website#30376]
Where is it stated that a file on /redis-master/redis.conf will be picked up by redis?

In most default configurations found online, includes are commented:

```
################################## INCLUDES ###################################

# Include one or more other config files here.  This is useful if you
# have a standard template that goes to all Redis servers but also need
# to customize a few per-server settings.  Include files can include
# other files, so use this wisely.
#
# Notice option "include" won't be rewritten by command "CONFIG REWRITE"
# from admin or Redis Sentinel. Since Redis always uses the last processed
# line as value of a configuration directive, you'd better put includes
# at the beginning of this file to avoid overwriting config change at runtime.
#
# If instead you are interested in using includes to override configuration
# options, it is better to use include as the last line.
#
# include /path/to/local.conf
# include /path/to/other.conf
```

So the documentation here seems to be missing a step on how to add this line to the default config (/etc/redis.conf):
`include /redis-master/redis.conf`

**Comment by MPParsley** [comment]
Added the config in a postStart command as a workaround:

```
              lifecycle:
                postStart:
                  exec:
                    - /bin/sh
                    - '-i'
                    - '-c'
                    - >-
                      echo -e "\ninclude /redis-master/redis.conf" >> /etc/redis.conf && redis-cli -h 127.0.0.1 -a $REDIS_PASSWORD config rewrite

```
