### ISSUE TITLE
Downward API doc - CPU requests/limits values are misleading

### ISSUE THREAD

**Issue by ErwanDL** [kubernetes/website#30766]
**This is a Bug Report**

**Problem:**

The [Downward API docs give an example](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-container-fields-as-values-for-environment-variables) of how to access `request.cpu`, `limits.cpu`, `requests.memory`, `limits.memory` via environment variables in a container. However, although the resources and env vars are set as such in the example : 
```yaml
resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      env:
        - name: MY_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: requests.cpu
        - name: MY_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: limits.cpu
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: limits.memory
```

the logs underneath the examples show values for `request.cpu` and `limits.cpu` of `1`, as opposed to `125m` and `250m` as expected.

**Proposed Solution:**

This is technically _not a bug of the API_, but it's very counter-intuitive for new users: they won't know that they have to use the `divisor` field to get a result in millicpus. I propose the YAML example be modified to include the `divisor` field:
```yaml
      env:
        - name: MY_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: requests.cpu
              divisor: 1m
        - name: MY_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: limits.cpu
              divisor: 1m
```

and then the logs underneath should be modified as well:
```
125
250
33554432
67108864
```

**Page to Update:**
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-container-fields-as-values-for-environment-variables
