### ISSUE TITLE
kubeadm control plane customization doc has wrong InitConfiguration yaml declaration

### ISSUE THREAD

**Issue by dhiller** [kubernetes/website#30834]
**This is a Bug Report**

**Problem:**

The yaml for control-plane-flags patch section has an incorrect structure.
 
Please see the InitConfiguration definition here: https://github.com/kubernetes/kubernetes/blob/b0bc8adbc2178e15872f9ef040355c51c45d04bb/cmd/kubeadm/app/apis/kubeadm/types.go#L69

**Proposed Solution:**

It should be like this:
```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
patches:
  directory: /home/user/somedir
```

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches

1.23
