### ISSUE TITLE
storageclass.storage.k8s.io "manual" not found

### ISSUE THREAD

**Issue by winkee01** [kubernetes/website#30912]
##### Environment:
Kube cluster is running on local Lan.

##### Symptom
So I followed with [the official tutorial](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/) about creating a PVC, but after I created PV and PVC,  I got this error saying `"manual" not found`. 

On that page it defines a StorageClass in PV's config file (listed below), I think this might be very confusing because there is no information about where this **`manual`** StorageClass comes from, is it a StorageClass already defined somewhere?, or we just declare a new one here. 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

The error clearly says "manual" StorageClass is not found, when I query `kubectl get storageclass`, it says No resources found. 

Can you make "manual" here more sense? 

##### Another observation
After I delete PV and PVC, and recreate them, the error disappears, wow, I am even more confused.
