### ISSUE TITLE
Assigning Pods to Nodes

### ISSUE THREAD

**Issue by cheersalam** [kubernetes/website#30955]
I am trying to deploy pods to multiple nodes with labels as `disktype=ssd`. I am using the same yml from website 
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd
```

And I am deploying by running command `kubectl apply -f pod-nginx.yaml`. But it is getting deployed to only one node. I have multiple nodes with disktype=ssd label. How can I deploy to all the nodes with same label?
