### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by robtayl0r** [kubernetes/website#31060]
Following the instructions per this page, any attempts to connect to the cluster via ingress timeout/hang indefinitely. As a matter of fact, it's unclear if I'm even attempting the connection correctly, using the minikube ip. 

MacOS, Docker driver, Docker Desktop.

```sh
$ minikube start 
$ minikube addons enable ingress
```

I have a NodePort service created for my deployment. 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-name
spec:
  selector:
    app: svc-name
  type: NodePort
  ports:
    - name: http
      port: 8080

```

When using `minikube service svc-name` the 127.0.0.1 tunnel works, and I'm able to make requests.

However, creating the following Ingress resource:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: api.local
      http:
        paths:
          - path: /svc
            pathType: Prefix
            backend:
              service:
                name: svc-name
                port:
                  number: 8080
```

```sh
$ kubectl get ingress
NAME   CLASS   HOSTS            ADDRESS     PORTS   AGE
rest   nginx   api.local   localhost   80      30m
```
Then, per:
> Note: If you are running Minikube locally, use minikube ip to get the external IP. The IP address displayed within the ingress list will be the internal IP. 

```sh
$ minikube ip
192.168.49.2
```
```sh
$ curl 192.168.49.2/svc      # hangs
$ curl api.local/svc             # having pointed api.local to 192.168.49.2 in /etc/hosts, hangs
$ socat - TCP4:192.168.49.2:80 
2021/12/21 17:31:19 socat[60673] E connect(7, LEN=16 AF=2 192.168.49.2:80, 16): Operation timed out
```

nginx-ingress-controller pod up, healthy. As is my application pod. 

There appears to be a crucial step missing. Isn't the common use case to run minikube "locally"?
