### ISSUE TITLE
Improve Ingress concept to explain use of ingressClassName field

### ISSUE THREAD

**Issue by timothyclarke** [kubernetes/website#31215]
IngressClass is defined, but there are no examples of it's usage, specifically when there are multiple ingress classes.
There is a deprecated annotation notice `kubernetes.io/ingress.class`
Assuming nginx is the new ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
ingressClassName: nginx
```
Or
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  ingressClassName: nginx
``` 
Or
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: nginx
```
