### ISSUE TITLE
Create a shortcode for pages that mention Docker Engine and / or dockershim

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#31425]
ref: https://github.com/kubernetes/website/issues/30771

----

Create a shortcode in https://github.com/kubernetes/website/tree/main/layouts/shortcodes, similar to https://github.com/kubernetes/website/blob/main/layouts/shortcodes/thirdparty-content.html, with the following:

```
 Warning: This page mentions Docker Engine. Docker Engine compatibility was deprecated as of Kubernetes 1.24. For more information see [Dockershim FAQ](https://kubernetes.io/blog/2020/12/02/dockershim-faq/)
```

(note: you'll need to use HTML, not markdown.) 

/triage accepted
/priority important-soon

**Comment by sftim** [comment]
When implementing this, make sure that the approach you use supports localization. Also, don't use the name `warning` for the shortcode; pick a new one.

/area web-development

**Comment by sftim** [comment]
@celestehorgan we could consider making this marker be part of the front matter, eg
```yaml
---
title: How to set up a Node with Docker Engine
content_warnings:
  - dockershim_deprecation
...
---

## Page content goes here
```
if you prefer that approach
