### ISSUE TITLE
Operating etcd clusters for Kubernetes

### ISSUE THREAD

**Issue by FerminCastro** [kubernetes/website#31822]
See etcd issue https://github.com/etcd-io/etcd/issues/13724 this is preventing us from upgrading a kubeadm control plane from 1.21.9 to 1.22. We need confirmation that we can just update the etcd image to 3.5.2 or a detailed alternative to upgrae the internal etcd cluster version BEFORE upgrading kubeadm/the control plane....

**Comment by neolit123** [comment]
there is no etcd 3.5.2 in the k8s GCR bucket, yet.
https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/us/etcd

you can log an issue for that in kubernetes/kubernetes.
there was PR but it got closed:
https://github.com/kubernetes/kubernetes/pull/107917

to use a custom etcd images in kubeadm you can edit the kube-system/kubead-config config map that holds the ClusterConfiguration:

```
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
...
etcd:
  local:
    imageRepository: "your.registry.com"
    imageTag: "3.5.2"
```

then modify the /etc/kubernetes/manifests/etcd.yaml on CP machines one at a time.

https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images

for more support questions please use:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
/sig cluster-lifecycle api-machinery
