### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by ydahan** [kubernetes/website#32077]
Page: [Example: Deploying WordPress and MySQL with Persistent Volumes](https://k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/)

---

Hi,

I was unable to create using the provided information. and done some adjustments to make this work.
My setup has workers with NFS mount to /mnt/data. I create /mnt/data/wp/mysql and /mnt/data/wp/wordpress folders.
I added the following to the end of `mysql-deployment.yaml:`

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
    tier: mysql
spec:
  capacity:
    storage: 20Gi 
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/data/wp/mysql"
```

And just for using NFS directly added the following to the end of `wordpress-deployment.yaml`.

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
    tier: frontend
spec:
  capacity:
    storage: 20Gi 
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /vol/vol2/wp/wordpress
    server: 192.168.5.50 
    readOnly: false
# I have changed the mysql image to 5.7....
```

Please add a remark that you will not be able to download images unless register to docker hub and apply that to the Kubernetes settings at the control plane:
First file - `create-secret-docker-registry.sh`:

```shell
#!/bin/bash

for ns in $(kubectl get namespaces |grep -v NAME|awk '{print $1}')
do
   kubectl create secret docker-registry docker.registry \
       --docker-username=<YOUR USER> \
       --docker-password='<YOUR PASSWORD>' -n $ns
done
```

Second file:
```shell
for ns in $(kubectl get namespaces|grep -v NAME|awk '{print $1}')
do
        for sa in $(kubectl -n $ns get sa|grep -v SECRETS|awk '{print $1}')
        do
           kubectl patch serviceaccount $sa -p '{"imagePullSecrets": [{"name": "docker.registry"}]}' -n $ns
           if [ $? -eq 0 ]; then
                echo $ns $sa patched
           else
                echo Error patching $ns $sa
           fi
        done
done
```

&nbsp;

```bash
# I had to create the mysql wordpress DB
kubectl exec --stdin --tty  wordpress-mysql-xxxxxxxxxxxx -- /bin/bash
mysql -u root -p
```
```
CREATE DATABASE wordpress;
```

Also after deployment you need to access the application using web browser to `/admin/install.php` not the root (I got 500 error).

I don't think below is true if one use hostpath like I did (`/mnt/data/wp/mysql`).
![In local clusters, the default StorageClass uses the hostPath provisioner. hostPath volumes are only suitable for development and testing. With hostPath volumes, your data lives in /tmp on the node the Pod is scheduled onto and does not move between nodes. If a Pod dies and gets scheduled to another node in the cluster, or the node is rebooted, the data is lost. ](https://user-images.githubusercontent.com/15953845/156913498-721f0b36-b289-474e-9289-fd9f13f6afc8.png)
