### ISSUE TITLE
yaml - ignorePreflightErrors need to under nodeRegistration

### ISSUE THREAD

**Issue by felixlutq** [kubernetes/website#32125]
file: kubeadm-config.v1beta3.md
ignorePreflightErrors need to under nodeRegistration.

**Comment by tengqm** [comment]
That is exactly what the reference is saying.

**Comment by sftim** [comment]
I think you're suggesting a clarification to https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/ @felixlutq 
Have I got that right?

**Comment by felixlutq** [comment]
https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/

In the example:

 

apiVersion: kubeadm.k8s.io/v1beta3

kind: InitConfiguration

bootstrapTokens:

- token: "9a08jv.c0izixklcxtmnze7"

  description: "kubeadm bootstrap token"

  ttl: "24h"

- token: "783bde.3f89s0fje9f38fhf"

  description: "another bootstrap token"

  usages:

  - authentication

  - signing

  groups:

  - system:bootstrappers:kubeadm:default-node-token

nodeRegistration:

  name: "ec2-10-100-0-1"

  criSocket: "/var/run/dockershim.sock"

  taints:

  - key: "kubeadmNode"

    value: "master"

    effect: "NoSchedule"

  kubeletExtraArgs:

    v: 4

ignorePreflightErrors:

- IsPrivilegedUser

   imagePullPolicy: "IfNotPresent"

localAPIEndpoint:

  advertiseAddress: "10.100.0.1"

  bindPort: 6443

certificateKey: "e6a2eb8581237ab72a4f494f30285ec12a9694d750b9785706a83bfcbbbd2204"

skipPhases:

- addon/kube-proxy

**Comment by felixlutq** [comment]
https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/

In the example:

 

apiVersion: kubeadm.k8s.io/v1beta3

kind: InitConfiguration

bootstrapTokens:

- token: "9a08jv.c0izixklcxtmnze7"

  description: "kubeadm bootstrap token"

  ttl: "24h"

- token: "783bde.3f89s0fje9f38fhf"

  description: "another bootstrap token"

  usages:

  - authentication

  - signing

  groups:

  - system:bootstrappers:kubeadm:default-node-token

nodeRegistration:

  name: "ec2-10-100-0-1"

  criSocket: "/var/run/dockershim.sock"

  taints:

  - key: "kubeadmNode"

    value: "master"

    effect: "NoSchedule"

  kubeletExtraArgs:

    v: 4

ignorePreflightErrors:

- IsPrivilegedUser

   imagePullPolicy: "IfNotPresent"

localAPIEndpoint:

  advertiseAddress: "10.100.0.1"

  bindPort: 6443

certificateKey: "e6a2eb8581237ab72a4f494f30285ec12a9694d750b9785706a83bfcbbbd2204"

skipPhases:

- addon/kube-proxy

**Comment by sftim** [comment]
Hi @felixlutq 

I'm going to edit your follow-up for readability - to make the YAML formatting more obvious.

**Comment by sftim** [comment]
That YAML from the email message is equivalent to:
```yaml
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- token: "9a08jv.c0izixklcxtmnze7"
  description: "kubeadm bootstrap token"
  ttl: "24h"
- token: "783bde.3f89s0fje9f38fhf"
  description: "another bootstrap token"
  usages:
  - authentication
  - signing
  groups:
  - system:bootstrappers:kubeadm:default-node-token
nodeRegistration:
  name: "ec2-10-100-0-1"
  criSocket: "/var/run/dockershim.sock"
  taints:
  - key: "kubeadmNode"
    value: "master"
    effect: "NoSchedule"
  kubeletExtraArgs:
    v: 4
ignorePreflightErrors:
- IsPrivilegedUser
   imagePullPolicy: "IfNotPresent"
localAPIEndpoint:
  advertiseAddress: "10.100.0.1"
  bindPort: 6443
certificateKey: "e6a2eb8581237ab72a4f494f30285ec12a9694d750b9785706a83bfcbbbd2204"
skipPhases:
- addon/kube-proxy
```
