### ISSUE TITLE
Ephemeral containers volume mount permissions differ from normal containers

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/website#32351]
### What happened?

Working: a pod with multiple containers, mounting a projected volume mount. Note the different UID/GID

```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-2
  namespace: noproxy
spec:
  selector:
    matchLabels:
      app: shell-2
  template:
    metadata:
      labels:
        app: shell-2
    spec:
      containers:
      - args:
        - /bin/sleep
        - infinity
        image: howardjohn/alpine-shell
        imagePullPolicy: IfNotPresent
        name: shell
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          runAsUser: 1338
      - args:
        - /bin/sleep
        - infinity
        image: howardjohn/alpine-shell
        imagePullPolicy: Always
        name: ephemeral
        resources: {}
        securityContext:
          runAsUser: 1337
          runAsGroup: 1337
        volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: token
      volumes:
      - name: token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: test
              expirationSeconds: 43200
              path: token
```

This works since 1.19+. On 1.18 and old we need `fsGroup: 1337` as well.

Not working: doing the same with ephemeral containers
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: shell
  namespace: noproxy
spec:
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - args:
        - /bin/sleep
        - infinity
        image: howardjohn/alpine-shell
        imagePullPolicy: IfNotPresent
        name: shell
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          runAsUser: 1338
      volumes:
      - name: token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: test
              expirationSeconds: 43200
              path: token
```

Then attach ephemeral container:
```
name: ephemeral
securityContext:
  runAsUser: 1337
  runAsGroup: 1337
image: howardjohn/alpine-shell
args:
  - /bin/sleep
  - infinity
volumeMounts:
- mountPath: /var/run/secrets/tokens
  name: token
```

When doing this, accessing the token from the ephemeral containers gives a permission denied.

If we add `fsGroup: 1337` to the pod spec, it does work.

### What did you expect to happen?

File permissions are the same on ephemeral containers and normal containers

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.4", GitCommit:"359b722c19ff163fb267f2747d794bd667d4f91d", GitTreeState:"clean", BuildDate:"2021-11-04T17:26:07Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
