### ISSUE TITLE
Document what happens in kubectl when two CRDs have the same names

### ISSUE THREAD

**Issue by jroper** [kubernetes/website#32588]
What happens if I deploy the following CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: services.example.com
spec:
  group: example.com
  names:
    kind: Service
    plural: services
    singular: service
    shortNames: [myservice, myservices]
  scope: Namespaced
  version: v1alpha1
```

The plural and singular are already all used by a core k8s resource. Anecdotally, it seems I can only access that resource in kubectl using the name `services.example.com` or `myservice` or `myservices`, but is that just by luck, or is this actually defined behavior? Is it possible that in some circumstances, the names declared above might take precedence over the k8s core resources, such that when I run `kubectl get services`, it returns my CRD instead of the k8s core service? I can't find any documentation on what should happen.

As far as why I might want to do this - my team is deciding on a name for something, that from an API point of view, `services` might make sense, which from an API point of view of course is fine because our CRD has a different api group. And we were thinking of using `shortNames` to control how we would access it to using `kubectl`. But, we're want to be sure if we do this, we're not going to interfere with `kubectl get services` in any way, that should always return the the core service resource, we don't want to break that. So, is that ok, or should we avoid using the name `services`?
