### ISSUE TITLE
Ingress

### ISSUE THREAD

**Issue by sunjianbo945** [kubernetes/website#32840]
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-fanout-example
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 4200
      - path: /bar
        pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 8080
```

does not work. It seems like we still need the annotation?
  annotations:
    ingress.kubernetes.io/rewrite-target: /
am I wrong？
