### ISSUE TITLE
Questions about /website/edit/main/content/en/examples/application/mysql/mysql-configmap.yaml

### ISSUE THREAD

**Issue by Yanshaoshuai** [kubernetes/website#32844]
**This is a Bug Report**

**Problem:**
I use the /website/edit/main/content/en/examples/application/mysql/mysql-configmap.yaml to deploy mysql cluster,and get error when the mysql-1 clone-mysql container starting to get backup file:
```sh
InnoDB: Number of pools: 1
InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
InnoDB: File ./ib_logfile0: 'open' returned OS error 71. Cannot continue operation
InnoDB: Cannot continue operation.

```
I think it is the reason why datadir is not specified
**Proposed Solution:**
then I change mysql-configmap.yaml as ：
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin
    datadir=/var/lib/mysql/mysql
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only
    datadir=/var/lib/mysql/mysql           
```
It works fine and success create other pod

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/
