### ISSUE TITLE
Run a Replicated Stateful Application

### ISSUE THREAD

**Issue by tomaspritrsky** [kubernetes/website#33223]
This tutorial is wrong, the replicas fail on Error.
Applying the mysql-statefulset.yaml I see only **mysql-0** running - mysql-1 fails on Init:Error

**Comment by Kartik494** [comment]
@tomaspritrsky Could you please share error logs you are getting in `init containers`

**Comment by LukasBommes** [comment]
I encountered the same issue following the tutorial. Here is my output for `kubectl logs pod/mysql-1 clone-mysql`

```
+ [[ -d /var/lib/mysql/mysql ]]
++ hostname
+ [[ mysql-1 =~ -([0-9]+)$ ]]
+ ordinal=1
+ [[ 1 -eq 0 ]]
+ ncat --recv-only mysql-0.mysql 3307
+ xbstream -x -C /var/lib/mysql
+ xtrabackup --prepare --target-dir=/var/lib/mysql
xtrabackup version 2.4.4 based on MySQL server 5.7.13 Linux (x86_64) (revision id: df58cf2)
xtrabackup: cd to /var/lib/mysql
xtrabackup: Error: cannot open ./xtrabackup_checkpoints
xtrabackup: error: xtrabackup_read_metadata()
xtrabackup: This target seems not to have correct metadata...
InnoDB: Number of pools: 1
InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
xtrabackup: Warning: cannot open ./xtrabackup_logfile. will try to find.
InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
  xtrabackup: Fatal error: cannot find ./xtrabackup_logfile.
xtrabackup: Error: xtrabackup_init_temp_log() failed.
```

**Comment by tomaspritrsky** [comment]
yes, I have the same error as @LukasBommes

**Comment by SuperChenSSS** [comment]
Hi Team, I could also confirm that I have the same error while following the tutorial, seems the doc needs some update.

**Comment by ProtoSeo** [comment]
I had the same problem too, but I modified 'mysql-configmap.yaml` file below and solved it.
@LukasBommes @tomaspritrsky 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin
    # datadir=/var/lib/mysql/mysql    
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only
    # datadir=/var/lib/mysql/mysql    
```

**Comment by Krapi0314** [comment]
I'm having a same issue on this part of the tutorial. `xtrabackup: Error: xtrabackup_init_temp_log() failed.`

I thought the problem was that `mysql` and `gcr.io/google-samples/xtrabackup:1.0` were not compatible anymore, so the commands were not executable.

I tried image version change & command change but I'm getting different errors :(

Any help??

**Comment by ratnopamc** [comment]
Following this https://v1-24.docs.kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#simulate-pod-and-node-downtime example and the readiness probe fails but the pod keeps running. 
Can anyone fix the doc or suggest a work-around?
Thanks.

**Comment by errhama** [comment]
Hi everyone,

I'm following the official Kubernetes documentation for running a replicated stateful application: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/. However, I'm encountering issues with my pods. They sometimes run successfully, but also crash occasionally.   

I found a potential issue report on the documentation itself: https://github.com/kubernetes/website/blob/main/content/en/examples/application/mysql/mysql-statefulset.yaml

Would anyone be able to help me deploy a stateful application with a master-slave concept?  Alternatively, could you point me towards any accurate documentation or alternative approaches?

Thanks in advance!

**Comment by errhama** [comment]
> I'm having a same issue on this part of the tutorial. `xtrabackup: Error: xtrabackup_init_temp_log() failed.`
> 
> I thought the problem was that `mysql` and `gcr.io/google-samples/xtrabackup:1.0` were not compatible anymore, so the commands were not executable.
> 
> I tried image version change & command change but I'm getting different errors :(
> 
> Any help??

I have the same issue , did you resolve the problem ?

**Comment by errhama** [comment]
> This tutorial is wrong, the replicas fail on Error. Applying the mysql-statefulset.yaml I see only **mysql-0** running - mysql-1 fails on Init:Error
> 
> fails here : https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#:~:text=kubectl%20apply%20%2Df%20https%3A//k8s.io/examples/application/mysql/mysql%2Dstatefulset.yaml

I have the same issue , please did you resolve the issue ?

**Comment by moritz-da** [comment]
I had the same problem. Mainly the mysql version is outdated, which means that a different version of xtrabackup has to be used and there were breaking changes. An approach for the new ones is described here: 

https://awesomeprogrammer.com/blog/2024/05/28/simple-mysql-8-replication-on-k8s/

**Comment by errhama** [comment]
@moritz-da thank you for your feedback , did you implement the tuto?  is it working for you ?

**Comment by moritz-da** [comment]
@errhama The following implementation worked for me. But you should definitely check it again and not use it for productive clusters :)

```
---
# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    readonly: "true"
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin    
    gtid_mode = ON
    enforce-gtid-consistency = TRUE
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only
    gtid_mode = ON
    enforce-gtid-consistency = TRUE
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      app.kubernetes.io/name: mysql
  serviceName: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/name: mysql
    spec:
      initContainers:
      - name: init-mysql
        image: mysql:8.0
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Generate mysql server-id from pod ordinal index.
          [[ $HOSTNAME =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          echo [mysqld] > /mnt/conf.d/server-id.cnf
          # Add an offset to avoid reserved server-id=0 value.
          echo server-id=$((100 + $ordinal)) >> /mnt/conf.d/server-id.cnf
          # Copy appropriate conf.d files from config-map to emptyDir.
          if [[ $ordinal -eq 0 ]]; then
            cp /mnt/config-map/primary.cnf /mnt/conf.d/
          else
            cp /mnt/config-map/replica.cnf /mnt/conf.d/
          fi          
        volumeMounts:
        - name: conf
          mountPath: /mnt/conf.d
        - name: config-map
          mountPath: /mnt/config-map
      - name: clone-mysql
        image: ushuaia/percona-xtrabackup:8.0.35-31-aarch64
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Skip the clone if data already exists.
          [[ -d /var/lib/mysql/mysql ]] && exit 0
          # Skip the clone on primary (ordinal index 0).
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          [[ $ordinal -eq 0 ]] && exit 0
          # Clone data from previous peer.
          ncat --recv-only mysql-$(($ordinal-1)).mysql 3307 | xbstream -x -C /var/lib/mysql
          # Prepare the backup.
          xtrabackup --prepare --target-dir=/var/lib/mysql          
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            cpu: 500m
            memory: 500m
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      - name: xtrabackup
        image: ushuaia/percona-xtrabackup:8.0.35-31-aarch64
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - name: xtrabackup
          containerPort: 3307
        command:
        - bash
        - "-c"
        - |
          set -ex
          cd /var/lib/mysql

          # Determine binlog position of cloned data, if any.
          if [[ -f xtrabackup_slave_info && "x$(<xtrabackup_slave_info)" != "x" ]]; then
            # XtraBackup already generated a partial "CHANGE MASTER TO" query
            # because we're cloning from an existing replica. (Need to remove the tailing semicolon!)
            cat xtrabackup_slave_info | sed -E 's/;$//g' > change_master_to.sql.in
            # Ignore xtrabackup_binlog_info in this case (it's useless).
            rm -f xtrabackup_slave_info xtrabackup_binlog_info
          elif [[ -f xtrabackup_binlog_info ]]; then
            # We're cloning directly from primary. Parse binlog position.
            [[ `cat xtrabackup_binlog_info` =~ ^(.*?)[[:space:]]+(.*?)$ ]] || exit 1
            rm -f xtrabackup_binlog_info xtrabackup_slave_info

            GTID_MATCHED=${BASH_REMATCH[3]}
            echo "Found GTID match: ${GTID_MATCHED}"
            echo "SET GLOBAL gtid_purged='${GTID_MATCHED}';" > gtid_purged.sql.in
          fi

          # Check if we need to complete a clone by starting replication.
          if [[ -f gtid_purged.sql.in ]]; then
            echo "Waiting for mysqld to be ready (accepting connections)"
            until mysql -h 127.0.0.1 -e "SELECT 1"; do sleep 1; done

            echo "Initializing replication from clone position"

            mysql -h 127.0.0.1 \
                          -e "RESET MASTER; \
                          $(<gtid_purged.sql.in) \
                          CHANGE REPLICATION SOURCE TO \
                          SOURCE_HOST='mysql', \
                          SOURCE_USER='root', \
                          SOURCE_PASSWORD='', \
                          SOURCE_AUTO_POSITION = 1, \
                          SOURCE_CONNECT_RETRY = 30; \
                          START REPLICA;" || exit 1
            # In case of container restart, attempt this at-most-once.
            mv gtid_purged.sql.in gtid_purged.sql.orig
          fi

          # Start a server to send backups when requested by peers.
          exec ncat --listen --keep-open --send-only --max-conns=1 3307 -c \
            "xtrabackup --backup --slave-info --stream=xbstream --host=127.0.0.1 --user=root"          
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
```
