### ISSUE TITLE
Add example of hostPath type PV https://k8s.io/docs/concepts/storage/volumes/#hostpath

### ISSUE THREAD

**Issue by SushilSanjayBhile** [kubernetes/website#33671]
### PersistentVolume With Hostpath
A `hostPath` volume can be created by specifying the hostPath property under spec section like following:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-vol
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
          path: /pv/my-vol
```
