### ISSUE TITLE
“Copy to clipboard” button adds extra lines into the copied text

### ISSUE THREAD

**Issue by hackertron** [kubernetes/website#34447]
**This is a Bug Report**

**Problem:** copy to clipboard functionality has an issue. Whenever you copy the yaml file it adds extra spaces. e.g. go to this yaml https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource and copy the yaml using the button. it will be like this
```
apiVersion: networking.k8s.io/v1

kind: NetworkPolicy

metadata:

  name: test-network-policy

  namespace: default

spec:

  podSelector:

    matchLabels:

      role: db

  policyTypes:

    - Ingress

    - Egress

  ingress:

    - from:

        - ipBlock:

            cidr: 172.17.0.0/16

            except:

              - 172.17.1.0/24

        - namespaceSelector:

            matchLabels:

              project: myproject

        - podSelector:

            matchLabels:

              role: frontend

      ports:

        - protocol: TCP

          port: 6379

  egress:

    - to:

        - ipBlock:

            cidr: 10.0.0.0/24

      ports:

        - protocol: TCP

          port: 5978


```
when it should be like this
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
        - namespaceSelector:
            matchLabels:
              project: myproject
        - podSelector:
            matchLabels:
              role: frontend
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 5978
```

**Proposed Solution:**
fix the extra space/markdown when using copy to clipboard.

**Page to Update:**
https://kubernetes.io/...
