### ISSUE TITLE
Dynamic Admission Control API version v1

### ISSUE THREAD

**Issue by borch84** [kubernetes/website#34574]
Hello, we are working on updating an admission controller. We need to update the apiVersion from v1beta1 to v1 but when we use the v1 API, the admission controller is not denying our requests. This is an example of the validating webhook configuration.
I have tried changing the several options in the sideEffects with no luck.
If we return to v1Beta1 the admission controller works again.
I would like to understand where the issue could be and how I can spot it.
Thanks.
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "nfsscout.fullname" . }}
webhooks:
  - name: {{ $fullname }}
    failurePolicy: {{ .Values.nfsniffer.validatingWebhook.failurePolicy }}
    clientConfig:
      service:
        name:  {{ .Values.nfsniffer.service.name }}
        namespace: {{ .Release.Namespace }}
        path: "/api/validate/pod"
        port: 8443
      caBundle: {{ required "nfsniffer.validatingWebhook.caBundle is required" .Values.nfsniffer.validatingWebhook.caBundle | b64enc | quote }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: NoneOnDryRun
    admissionReviewVersions: ["v1", "v1beta1"]
    timeoutSeconds: {{ .Values.nfsniffer.validatingWebhook.timeout }}
 ```
