### ISSUE TITLE
Docs for dockerconfigjson include base64 string that does not match the expected value.

### ISSUE THREAD

**Issue by alphabet5** [kubernetes/website#35004]
**This is a Bug Report**

**Problem:**

The example manifest under 'Create a Secret based on existing credentials' does not use the expected format.

```bash
~ % echo 'UmVhbGx5IHJlYWxseSByZWVlZWVlZWVlZWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGx5eXl5eXl5eXl5eXl5eXl5eXl5eSBsbGxsbGxsbGxsbGxsbG9vb29vb29vb29vb29vb29vb29vb29vb29vb25ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubmdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2cgYXV0aCBrZXlzCg==' | base64 --decode
Really really reeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaalllllllllllllllllllllllllllllllyyyyyyyyyyyyyyyyyyyy llllllllllllllooooooooooooooooooooooooooonnnnnnnnnnnnnnnnnnnnnnnnggggggggggggggggggg auth keys
```

**Proposed Solution:**

Include an example of valid data. Replace the auth key with something reasonable, but keep the same format.

Add a section on how the data is created.

```bash
~ % echo -n 'docker-username:your-really-really-long-auth-key' | base64
ZG9ja2VyLXVzZXJuYW1lOnlvdXItcmVhbGx5LXJlYWxseS1sb25nLWF1dGgta2V5
```

```bash
~ % cat config.json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "ZG9ja2VyLXVzZXJuYW1lOnlvdXItcmVhbGx5LXJlYWxseS1sb25nLWF1dGgta2V5"
		}
	}
}
~ % cat config.json | base64
ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpHOWphMlZ5TFhWelpYSnVZVzFsT25sdmRYSXRjbVZoYkd4NUxYSmxZV3hzZVMxc2IyNW5MV0YxZEdndGEyVjUiCgkJfQoJfQp9Cg==
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: awesomeapps
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpHOWphMlZ5TFhWelpYSnVZVzFsT25sdmRYSXRjbVZoYkd4NUxYSmxZV3hzZVMxc2IyNW5MV0YxZEdndGEyVjUiCgkJfQoJfQp9Cg==
type: kubernetes.io/dockerconfigjson
```

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
