### ISSUE TITLE
Network Policies

### ISSUE THREAD

**Issue by pnpatel** [kubernetes/website#35102]
Hello  K8s Team,

I have noticed some indentation for network policy is incorrect in kubernetes io documentation. 

https://kubernetes.io/docs/concepts/services-networking/network-policies/

section : The NetworkPolicy resource 
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
        - namespaceSelector:
            matchLabels:
              project: myproject
        - podSelector:
            matchLabels:
              role: frontend
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 5978
```
(https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/networking/networkpolicy.yaml)

--------------------------------------
from ingress  - from section. the indentation is incorrect.
I think it should be 
```yaml
ingress:
-  from: 
```

**Comment by akankshakumari393** [comment]
Hi @pnpatel, I compared the YAML content for network policy with an online YAML formatter and the indentation seems to be correct. Let me know If I am missing something.

**Comment by pnpatel** [comment]
Hi Kubernetes/Website,

Please see attached screenshot...not the github but need to see in document
please see attached screenshot. just look ingress section in document

ex...document shows

ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
        - namespaceSelector:
            matchLabels:
              project: myproject
        - podSelector:
            matchLabels:
              role: frontend
      ports:
        - protocol: TCP
          port: 6379


-I guess it should be show as below ...specially - from should be start
just below  of text 'i'  in ingress and not starting just below of text 'g'

ingress:
- from:
  - ipBlock:
      cidr: 172.17.0.0/16
      except:
      - 172.17.1.0/24
   - namespaceSelector:
       matchLabels:
         project: myproject
   - podSelector:
       matchLabels:
         role: frontend
   ports:
   - protocol: TCP
     port: 6379

Please let me know if i am missing something...it document io looks weird
to me

Thanks,
Piyush

**Comment by utkarsh-singh1** [comment]
Hi @pnpatel, you can check the original YAML file and the one you are mentioning here on the YAML checker as they both are correct, it's not weird but to provide better readability of scope of ingress.

**Comment by akankshakumari393** [comment]
1. I do not see any attached screenshot. Could you please re-share it.
2. Do you mean the ingress section should be 
```
  ingress:
  from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
```

and not 
```
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
```

I still think the indentation is correct in the document.
