### ISSUE TITLE
Configure a Pod to Use a ConfigMap

### ISSUE THREAD

**Issue by lisadd** [kubernetes/website#35986]
The below configuration for adding a ConfigMap, will not work. Please verify the changes suggested below:

```yaml

apiVersion: v1
  
kind: Pod
  
metadata:
  
  name: dapi-test-pod
  
spec:
  
  containers:
  
    - name: test-container
  
      image: k8s.gcr.io/busybox
  
      command: [ "/bin/sh", "-c", "env" ]
  
      envFrom:
  
      - configMapRef:
  
          name: special-config
  
  restartPolicy: Never
```
  
---

UPDATE

```yaml

apiVersion: v1
  
kind: Pod
  
metadata:
  
  name: dapi-test-pod
  
spec:
  
    containers:

    -  envFrom:
  
        - configMapRef:
  
               name: special-config
  
        - name: test-container
  
           image: k8s.gcr.io/busybox
  
           command: [ "/bin/sh", "-c", "env" ]
  
  restartPolicy: Never

```
