### ISSUE TITLE
debug-cluster/monitor-node-health: YAML file contains many empty lines

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#36361]
The highlightet YAML file at https://kubernetes.io/docs/tasks/debug/debug-cluster/monitor-node-health/#using-kubectl contains an empty line between every two lines.

```yaml
apiVersion: apps/v1

   kind: DaemonSet

   metadata:

     name: node-problem-detector-v0.1

     namespace: kube-system

     labels:

```
and so on.

There shall be no empty lines shown in the browser.
