### ISSUE TITLE
Some yaml examples have an extra blank line between every line

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/website#36813]
### Problem:
Some yaml examples have an extra blank line between every line

---

### URL:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables

---
### Example:

https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/configmap/configmap-multikeys.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
```

Notice there are no blank lines in the actual YAML.

But on the web page, it has extra blank lines as shown here:
![image](https://user-images.githubusercontent.com/4977542/190230423-8c731a57-276b-42e0-b990-d01eba698b7c.png)

---

### Other Info:
This doesn't happen for every YAML example, but it does hapeen for multiple of them on this same page.

The problem happens on both Chrome and FireFox, the only browsers I tested with.
