### ISSUE TITLE
clarity on behaviour of ports in network policies

### ISSUE THREAD

**Issue by tssdavey** [kubernetes/website#37039]
**This is a Feature Request**
**What would you like to be added**
Add clarity around the behaviour of **ports**
On [this](https://kubernetes.io/docs/concepts/services-networking/network-policies/) page I think it could be made clear that, for example.
```
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 5978
```
allows traffic to 10.0.0.0/24 on port 5978.
While
```
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
    - ports:
        - protocol: TCP
          port: 5978
```
allows traffic to: 10.0.0.0/24 on any port
and also allows traffic to: anywhere on port 5978.
**Comments**
Happy to pick this one up myself
