### ISSUE TITLE
kube-apiserver / kubelet RBAC

### ISSUE THREAD

**Issue by aceeric** [kubernetes/website#37085]
This is about Kubernetes 1.25.0

Folks - as recently as less than a year ago (I think) there was a document https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/. I know because I cited it in my source code in GitHub!

The doc talked about when manually bringing up a Kubernetes cluster - and the doc instructed you to generate a `ClusterRole` and associated binding for the API server:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-apiserver-to-kubelet
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
      - nodes/stats
      - nodes/log
      - nodes/spec
      - nodes/metrics
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kube-apiserver
  namespace: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-apiserver-to-kubelet
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kubernetes
```
If you didn't  do this, then when the cluster was up:
```
$ kubectl -n kube-system logs kube-apiserver-zzz
Error from server (Forbidden): Forbidden (user=kubernetes, verb=get, resource=nodes, subresource=proxy) ( pods/log kube-apiserver-doc)
```
Well - it seems to be the case today that this RBAC *appears* to still be needed. To correct the above error, apply the RBAC and instantly the log statement works.

Problem is - the aforementioned doc went away. Possibly, some new combo of `kube-apiserver` command-line options deprecated this? Anyway - if there is a new canonical way to configure kube-apiserver - can you please point me to it? Thank you.
