### ISSUE TITLE
Warn about passwords in kubeconfig

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#37132]
**This is a Feature Request**

**What would you like to be added**
Add a comment to the example Kubernetes client config in https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

```yaml
users:
- name: developer
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
- name: experimenter
  user:
    password: some-password # ADD A WARNING HERE!
    username: exp
```

**Why is this needed**
Storing a password in a Kubernetes client config is risky, and we have an opportunities to call out other options.

**Comments**
A good alternative is a [credential plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) and separate secret storage.

/language en
/sig security
