### ISSUE TITLE
Configure a Pod to Use a PersistentVolume for Storage shows wrong config description

### ISSUE THREAD

**Issue by XANi** [kubernetes/website#37137]
This config is described wrong:

```
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

the `storage: 10Gi` suggests there is a limit placed on storage. That is **not** the case, this snippet will "just" mount `/mnt/data` on host on the pod, it will not set any limit on amount of storage that pod can use

See Red hat docs about it: https://docs.openshift.com/container-platform/4.7/storage/persistent_storage/persistent-storage-hostpath.html
