### ISSUE TITLE
Pod Horizontal automatic expansion

### ISSUE THREAD

**Issue by wangsao5566** [kubernetes/website#37241]
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-yhz
  namespace: test
spec:
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
       name: cpu
       target:
          type: Utilization
          averageUtilization: 40
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
```

Question:
Stop the pressure test after making the CPU utilization of the Pod unstable through the pressure test. Why does the HPA continue to expand and shrink the number of Pods when the CPU utilization is 0 ?

<img width="457" alt="lQLPJxbDFTIneYXNAtjNA5Gwgpqa5yO-DvoDQLChXQA2AA_913_728" src="https://user-images.githubusercontent.com/59693618/194805372-e5daa4f7-35fa-4ce7-8385-fa63df824e52.png">
