### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

### ISSUE THREAD

**Issue by tback** [kubernetes/website#37503]
It'd be really great if the page about liveness, readiness & startup would clarify the behavior for failureThreshoulds.
Consider the following livenessProbe:
```yaml
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 30
  failureThreshold: 3
```

What is the minimal/maximal amount of time until the pod will restart?

Maximal case:
Will the kubelet spawn probes while it's waiting for a probe to respond? (restart after 3failures * 5s + 30s => 45s)? 
Will it wait for the the first probe to fail and then spawn the next probe immediately after (restart after 3failuress * 30s => 90s)?

Minimal case should be clear (restart after 3failures * 5s => 15s).
