### ISSUE TITLE
Network Policies

### ISSUE THREAD

**Issue by erdogancel** [kubernetes/website#37708]
The documentation for Network Policies has an indentation error unless I miss the point here. While I was preparing for my CKAD exam I realized that under the `--from` block for ingress and `-to` section for egress. 

```
ingress:
  - from:
      - ipBlock:
          cidr: 172.17.0.0/16
          except:
            - 172.17.1.0/24
      - namespaceSelector:
          matchLabels:
            project: myproject
      - podSelector:
          matchLabels:
            role: frontend
```         
```
egress:
  - to:
      - ipBlock:
          cidr: 10.0.0.0/24
    ports:
      - protocol: TCP
        port: 5978     
```

This is the page - https://kubernetes.io/docs/concepts/services-networking/network-policies/
The file name is [service/networking/networkpolicy.yaml](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/networking/networkpolicy.yaml)
