### ISSUE TITLE
Advice on setting up audit logging for Kubernetes

### ISSUE THREAD

**Issue by kavita1205** [kubernetes/website#37958]
**This is a Bug Report**

**Problem:**
Hi Team,

I am trying to get k8 audit for level "Metadata" and within metadata I don't want if user and group is system*. To achieve the same I am using below audit policy configurations. But I am still getting below output where "groups": ["system:serviceaccounts",      "system:serviceaccounts:kube-system", "system:authenticated"]

Can someone help me here how to avoid system logs for group and user if level is metadata.
```
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  #Don't log request by system
  - level: None
    users: ["system:node", "system:kube-scheduler", "system:kube-proxy", "system:apiserver", "system:kube-controller-manager", "system:authenticated", "system:anonymous"]
    resources:
    - group: ["system:node", "system:kube-scheduler", "system:kube-proxy", "system:apiserver", "system:kube-controller-manager", "system:authenticated", "system:anonymous"]

  - level: None
    verbs: ["get", "watch", "list"]
  
  # Don't log authenticated requests  
  - level: None
    userGroups: ["system:node", "system:kube-scheduler", "system:kube-proxy", "system:apiserver", "system:kube-controller-manager", "system:authenticated", "system:anonymous"]
    nonResourceURLs:
    - "/api*" # Wildcard matching.
    - "/version"

  # Log "pods/log", "pods/status" at Metadata level
  - level: Metadata
    resources:
    - group: ""
      resources: ["pods/log", "pods/status", "secrets", "configmaps"]
```

Output 
```
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "Metadata",
  "auditID": "7907fd95-bc44-4ad5-bc42-ae67f16dd106",
  "stage": "ResponseComplete",
  "requestURI": "/apis/events.k8s.io/v1",
  "verb": "get",
  "user": {
    "username": "system:serviceaccount:kube-system:resourcequota-controller",
    "uid": "b41228b6-6d95-4434-bee0-5d8d05b530db",
    **"groups": [
      "system:serviceaccounts",
      "system:serviceaccounts:kube-system",
      "system:authenticated"
    ]**
  },
  "sourceIPs": [
    "10.150.136.133"
  ],
  "userAgent": "kube-controller-manager/v1.24.6 (linux/amd64) kubernetes/b39bf14/system:serviceaccount:kube-system:resourcequota-controller",
  "responseStatus": {
    "metadata": {},
    "code": 200

```
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...
