### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/job/: pod failure policy

### ISSUE THREAD

**Issue by amosshapira** [kubernetes/website#38150]
Not sure what was meant to be said in https://kubernetes.io/docs/concepts/workloads/controllers/job/#:~:text=When%20specified%2C%20it%20should%20match%20one%20the%20container%20or%20initContainer%20names%20in%20the%20Pod%20template.

```
When specified, it should match one the container or initContainer names in the Pod template.
```

**Comment by utkarsh-singh1** [comment]
/language en

related doc - https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-failure-policy

Hi @amosshapira, here as doc stated pod failure policy can be applied to all containers if container name is not specified 
here `spec.podFailurePolicy.rules[*].containerName`, but it can be applied to certain container in case if you specify a name that should be match with container name you have mention in pod template under job-pod-failure-policy-example.yaml.

Example - 

```yaml
template:
    spec:
      restartPolicy: Never
      containers:
      - name: main
        image: docker.io/library/bash:5
        command: ["bash"]        # example command simulating a bug which triggers the FailJob action
        args:
        - -c
        - echo "Hello world!" && sleep 5 && exit 42
```

As stated here, container name is `main`, that should be matching with the container name you will be mentioning.
