### ISSUE TITLE
Service Internal Traffic Policy

### ISSUE THREAD

**Issue by sysarch-repo** [kubernetes/website#38232]
I am running K8S v1.23 to benefit from the internalTrafficPolicy feature. The goal is using "cluster" policy for the internal traffic and "local" policy for the external traffic. This should basically be possible even before v1.23 but anyway:

I am initiating traffic from a K8S pod to another pod on the same K8S cluster. 

According to:
https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/
**`The "internal" traffic here refers to traffic originated from Pods in the current cluster.`**
The documentation does not mention any other criteria, does it?

The traffic originated from the K8S pod goes to a K8S service that is assigned **an external IP**. The K8S pod originating the traffic is using the external IP as the destination IP. The NodePort service type is used to allow the externalTrafficPolicy parameter to be defined but the traffic always goes to the external IP and the service port, and NEVER to the node IP and the node port.

```
spec:
  clusterIP: 10.233.1.107
  clusterIPs:
    - 10.233.1.107
  externalIPs:
    - 192.168.56.100
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - appProtocol: https
      name: proxy
      nodePort: 30823
      port: 443
      protocol: TCP
      targetPort: 8084
  selector:
    app.kubernetes.io/instance: hsr-ipx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

Calico IPPool is defined for the external IP CIDR to disable SNAT for the traffic routed internally.
For the external traffic (originated from a Cumulus BGP router deployed outside the K8S cluster), Calico CNI is used to advertise routes to the external IPs via the K8S nodes. The externalTrafficPolicy setting is observed and works as expected.

**The problem:**
I still believe to see the "local" policy applied to the traffic originated from the K8S pod that should only apply for traffic NOT originated from Pods in the current cluster. I am using kube-proxy in IPVS mode with strict ARP enabled (necessary so that the external BGP router is not receiving routes from the Calico CNI advertising all K8S nodes; instead, only the K8S nodes the endpoints are scheduled on are included in the route advertisement).

Either my observation is wrong, or the documentation is wrong, or something else is wrong.
Could you please clarify? Thanks a lot!
