### ISSUE TITLE
Link to v1.25 docs, in the version selector, is wrong

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#38411]
**This is a Bug Report**

**Problem:**
Link to v1.25 docs, in top nav 'Versions' menu, is wrong

![image](https://user-images.githubusercontent.com/46767780/206942391-7bbb022b-3801-4dcd-ad76-2aab77b20df5.png)

**Proposed Solution:**

Update https://github.com/kubernetes/website/blob/main/config.toml#L190-L216 to:

```toml
[[params.versions]]
fullversion = "v1.25.5"
version = "v1.25"
githubbranch = "v1.25.5"
docsbranch = "release-1.25"
url = "https://v1-25.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.24.9"
version = "v1.24"
githubbranch = "v1.24.9"
docsbranch = "release-1.24"
url = "https://v1-24.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.23.15"
version = "v1.23"
githubbranch = "v1.23.15"
docsbranch = "release-1.23"
url = "https://v1-23.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.22.17"
version = "v1.22"
githubbranch = "v1.22.17"
docsbranch = "release-1.22"
url = "https://v1-22.docs.kubernetes.io"
```

**File to Update:**
https://github.com/kubernetes/website/blob/main/config.toml#L190-L216

/good-first-issue
