### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/encrypt-data/

### ISSUE THREAD

**Issue by Daxcor69** [kubernetes/website#38583]
The documentation doesn't make it clear that you need to have the identity: {} in the config file.  So 
```
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
      - configmaps
      - pandas.awesome.bears.example
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: <BASE 64 ENCODED SECRET>
      - identity: {}
    ```

If you don't have the `identity: {}' in the file, the api server will no work properly as it can't decode existing secrets etc.
