### ISSUE TITLE
Query about how Kubernetes interpolates environment variables for container entrypoint processes

### ISSUE THREAD

**Issue by chainhead** [kubernetes/website#38680]
In [this](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config), shouldn't the environment variables be surrounded with curly braces? Else, it is interpreted as command execution.

I didn't see any errors while using the following. However, upon `kubectl logs print-greeting`, there is no output seen.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: print-greeting
spec:
  containers:
  - name: env-print-demo
    image: bash
    env:
    - name: GREETING
      value: "Warm greetings to"
    - name: HONORIFIC
      value: "The Most Honorable"
    - name: NAME
      value: "Kubernetes"
    command: ["echo"]
    args: ["${GREETING} ${HONORIFIC} ${NAME}"]
```
