### ISSUE TITLE
Example NetworkPolicy doesn't validate

### ISSUE THREAD

**Issue by amavrogiannis** [kubernetes/website#38780]
I was playing with network policies and a minor issue was the line showing `port`, the test was not validated with the following script:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np
  namespace: space1
  labels:
    svc: policy-sp1
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: space2
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
```

Meanwhile, when I added a "list" `-` line, it was then validated. Please check the below:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np
  namespace: space1
  labels:
    svc: policy-sp1
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: space2
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
```

I copied from this documentation URL >> [here](https://kubernetes.io/docs/concepts/services-networking/network-policies/#allow-all-ingress-traffic)
Assuming to the section, where it is showing: 
```yaml
      ports:
        - protocol: TCP
          port: 6379
```
should then be:
```yaml
    - ports:
        - protocol: TCP
          port: 6379
```

I hope this help. I will be happy for clarifying if I am mistaken. 

Thanks
