### ISSUE TITLE
Interactive Tutorial - Exposing Your App

### ISSUE THREAD

**Issue by guillemlc** [kubernetes/website#38901]
Working with:

```
clientVersion:
  buildDate: "2022-12-08T19:58:30Z"
  compiler: gc
  gitCommit: b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d
  gitTreeState: clean
  gitVersion: v1.26.0
  goVersion: go1.19.4
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-11-18T18:17:40Z"
  compiler: gc
  gitCommit: 0dc63334c0db3e7b99244427615e091909fc486e
  gitTreeState: clean
  gitVersion: v1.25.4+k3s1
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: linux/amd64

```

In the interactive bootcamp tutorial we find:

`kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080`

It will return:

> error: the server doesn't have a resource type "deployment"

But that will not work. This works instead:

` kubectl expose deployment kubernetes-bootcamp --type="NodePort" --port 8080`

It creates the service correctly:

kubernetes-bootcamp       NodePort    10.43.208.248   <none>        8080:31622/TCP   3m57s
