### ISSUE TITLE
Assigning Pods to Nodes: Lack of examples for Gt and Lt

### ISSUE THREAD

**Issue by userbradley** [kubernetes/website#39256]
## Issue overview
* Issue type: Unclear Explanation
* Page: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
* Section: [Operators](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity:~:text=You%20can%20use%20In%2C%20NotIn%2C%20Exists%2C%20DoesNotExist%2C%20Gt%20and%20Lt)

## Describe the issue

I'm studying for the CKA (go me 🥳 ), and am doing the section on Node Affinity.

I refer to the documentation for the types of Operators one can use and am presented with the list below:

* In
* NotIn
* Exists
* DoesNotExist
* Gt
* Lt

The issue is there are not enough examples of how these work, as well as no explanation of `Gt` and `Lt` 

I had a quick google before, and couldn't seem to find anything useful or explaining it.

The closest I found was [This yaml file from Prometheus](https://github.com/prometheus-operator/prometheus-operator/blob/be7ac03166b8fca8db4e23ea69f62b8e65006391/bundle.yaml#L1942)

Let me know if I missed anything

**Comment by sftim** [comment]
This looks like a duplicate of https://github.com/kubernetes/website/issues/33323

What do you think @userbradley - do you agree?

**Comment by userbradley** [comment]
I do agree that is is _technically_ a duplicate, but nothing ever came of that issue sadly.

If you know of any commits or KB's that reference this, I can take a stab at writing the documentation my self?

**Comment by sftim** [comment]
/triage duplicate

Issue https://github.com/kubernetes/website/issues/33323 is still awaiting a volunteer to work on it. You're very welcome to be that volunteer. See https://kubernetes.io/docs/contribute/ for some more tips!

**Comment by userbradley** [comment]
I'd love to, but I can't find any documentation or explanations of this to write it sadly. I think it'll have to come from a maintainer :/ 

Anything I find I'll add. Cheers

**Comment by sftim** [comment]
Those operators and my brief explanations:

- `In`: the label value is contained in the supplied set of strings
- `NotIn`: the label value is not contained in the supplied set of strings
- `Exists`: a label with this key is applied to the object
- `DoesNotExist`: no such label with this key is applied to the object
* `Gt`: the single supplied value can parse as an integer, and that integer is less (sic) than or equal to the integer that results from parsing the value of a label named by this selector
   * Not available for `nodeAffinity` (never implemented; could be added if someone sends in a PR)
* `Lt`: the single supplied value can parse as an integer, and that integer is greater than or equal to the integer that results from parsing the value of a label named by this selector
   * Not available for `nodeAffinity` (never implemented; could be added if someone sends in a PR)

Here's a example manifest that uses some of these operators (I didn't test it)
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
   matchLabels:
      - "kubernetes.io/os": "linux"
   matchExpressions:
      - key: "kubernetes.io/arch"
        operator: In
        values:
         - "amd64"
         - "arm64"
      - key: "secret-of-universe"
        operator: Gt
        values:
        - "41" # only schedule onto nodes labelled secret-of-universe with value 42 or higher
               # specifying a second array entry here isn't allowed BTW
```
