### ISSUE TITLE
Configure a Security Context for a Pod or Container

### ISSUE THREAD

**Issue by enidkal** [kubernetes/website#39250]
add: [ "SYS_TIME" ] there is an additional SPACE required

**Comment by devarsh10** [comment]
Hey @enidkal 
I want to work on this. Can you please elaborate, where the additional space is required?

Regards.

**Comment by sftim** [comment]
I don't see a bug.

/triage not-reproducible

How can you reproduce the bug @enidkal ?

/language en

**Comment by enidkal** [comment]
In the  pods/security/security-context-4.yaml
<https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/security/security-context-4.yaml>
when
I dont give space between square bracket and " it is not taking.
apiVersion: v1

kind: Pod

metadata:

  name: security-context-demo-4

spec:

  containers:

  - name: sec-ctx-4

    image: gcr.io/google-samples/node-hello:1.0

    securityContext:

      capabilities:

*        add: ["NET_ADMIN", "SYS_TIME"]*

**Comment by sftim** [comment]
Here's the manifest from https://github.com/kubernetes/website/issues/39250#issuecomment-1416933682
```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-4
spec:
  containers:
  - name: sec-ctx-4
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
*        add: ["NET_ADMIN", "SYS_TIME"]*
```

I still don't know what the symptoms look like. It'd be good to find out.

**Comment by enidkal** [comment]
capabilities:
*        add: [ "NET_ADMIN", "SYS_TIME" ]

**Comment by Shubham82** [comment]
hi @enidkal I have tried this one and it is working for me.
The following given manifest in docs is correct:

```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-4
spec:
  containers:
  - name: sec-ctx-4
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]

```
