### ISSUE TITLE
Unclear documentation for ValidatingAdmissionPolicy and contents of CEL context

### ISSUE THREAD

**Issue by divanodestiny** [kubernetes/website#39368]
i wonder why it says that
> The apiVersion, kind, metadata.name and metadata.generateName are always accessible from the root of the object. No other metadata properties are accessible. 

i create a ValidatingAdmissionPolicy like 
``` yaml
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: "dp"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments"]
  validations:
    - expression: "object.spec.replicas <= 5 || has(object.metadata.labels.test)"
      reason: Invalid
```
it can reject creating or updating deployments without label `test`.  So `metadata.labels` is accessible.
