### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/tasks/run-application/run-single-instance-stateful-application/

### ISSUE THREAD

**Issue by zhouhuhq** [kubernetes/website#40037]
【Why am I getting a CrashLoopBackOff on this kubernetes example?】
I am following the instruction to create a simple stateful app with mysql following the instructions from kubernetes official documentation, but it does work for me and I wonder if any of you can test it in his own k8s in two minutes and see if I am the only one having problems of the example just does not work:
https://kubernetes.io/zh-cn/docs/tasks/run-application/run-single-instance-stateful-application/

These are the files from the documentation:
[application/mysql/mysql-deployment.yaml](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/mysql/mysql-deployment.yaml)

```
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
```
[application/mysql/mysql-pv.yaml](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/mysql/mysql-pv.yaml)
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```

NOTE: I try a lots of time to build this example,and it always tell me CrashLoopBackOff, here is some logs:
```
[root@master:/home/workspace/bc_repo/test]# kubectl apply -f https://k8s.io/examples/application/mysql/mysql-pv.yaml
persistentvolume/mysql-pv-volume created
persistentvolumeclaim/mysql-pv-claim created
[root@master:/home/workspace/bc_repo/test]# kubectl apply -f https://k8s.io/examples/application/mysql/mysql-deployment.yaml
service/mysql created
deployment.apps/mysql created
[root@master:/home/workspace/bc_repo/test]# kubectl describe deployment mysql
Name:               mysql
Namespace:          default
CreationTimestamp:  Thu, 16 Mar 2023 16:43:57 +0800
Labels:             <none>
Annotations:        deployment.kubernetes.io/revision: 1
Selector:           app=mysql
Replicas:           1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:  app=mysql
  Containers:
   mysql:
    Image:      mysql:5.6
    Port:       3306/TCP
    Host Port:  0/TCP
    Environment:
      MYSQL_ROOT_PASSWORD:  password
    Mounts:
      /var/lib/mysql from mysql-persistent-storage (rw)
  Volumes:
   mysql-persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mysql-pv-claim
    ReadOnly:   false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      False   MinimumReplicasUnavailable
OldReplicaSets:  <none>
NewReplicaSet:   mysql-68579b78bb (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  6s    deployment-controller  Scaled up replica set mysql-68579b78bb to 1
[root@master:/home/workspace/bc_repo/test]# kubectl get pods -l app=mysql
NAME                     READY   STATUS             RESTARTS      AGE
mysql-68579b78bb-l6sdg   0/1     CrashLoopBackOff   1 (10s ago)   15s
[root@master:/home/workspace/bc_repo/test]# kubectl describe mysql-68579b78bb-l6sdg
error: the server doesn't have a resource type "mysql-68579b78bb-l6sdg"
[root@master:/home/workspace/bc_repo/test]# kubectl describe pod mysql-68579b78bb-l6sdg
Name:         mysql-68579b78bb-l6sdg
Namespace:    default
Priority:     0
Node:         node2/10.1.160.76
Start Time:   Thu, 16 Mar 2023 16:43:57 +0800
Labels:       app=mysql
              pod-template-hash=68579b78bb
Annotations:  <none>
Status:       Running
IP:           10.32.0.2
IPs:
  IP:           10.32.0.2
Controlled By:  ReplicaSet/mysql-68579b78bb
Containers:
  mysql:
    Container ID:   docker://6a4a18bade223dc1c3bd9c98588a53ebb94a50a7b6ca998d057c50d79519ed03
    Image:          mysql:5.6
    Image ID:       docker-pullable://mysql@sha256:20575ecebe6216036d25dab5903808211f1e9ba63dc7825ac20cb975e34cfcae
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 16 Mar 2023 16:44:19 +0800
      Finished:     Thu, 16 Mar 2023 16:44:20 +0800
    Ready:          False
    Restart Count:  2
    Environment:
      MYSQL_ROOT_PASSWORD:  password
    Mounts:
      /var/lib/mysql from mysql-persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-p7tgm (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  mysql-persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mysql-pv-claim
    ReadOnly:   false
  kube-api-access-p7tgm:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  38s                default-scheduler  Successfully assigned default/mysql-68579b78bb-l6sdg to node2
  Normal   Pulled     16s (x3 over 37s)  kubelet            Container image "mysql:5.6" already present on machine
  Normal   Created    16s (x3 over 36s)  kubelet            Created container mysql
  Normal   Started    16s (x3 over 36s)  kubelet            Started container mysql
  Warning  BackOff    3s (x4 over 32s)   kubelet            Back-off restarting failed container
[root@master:/home/workspace/bc_repo/test]# kubectl logs mysql-68579b78bb-l6sdg
2023-03-16 09:20:51+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.51-1debian9 started.
2023-03-16 09:20:51+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-03-16 09:20:51+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.51-1debian9 started.
2023-03-16 09:20:52 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2023-03-16 09:20:52 0 [Note] mysqld (mysqld 5.6.51) starting as process 1 ...
2023-03-16 09:20:52 1 [Note] Plugin 'FEDERATED' is disabled.
mysqld: Table 'mysql.plugin' doesn't exist
2023-03-16 09:20:52 1 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
2023-03-16 09:20:52 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
2023-03-16 09:20:52 1 [Note] InnoDB: The InnoDB memory heap is disabled
2023-03-16 09:20:52 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2023-03-16 09:20:52 1 [Note] InnoDB: Memory barrier is not used
2023-03-16 09:20:52 1 [Note] InnoDB: Compressed tables use zlib 1.2.11
2023-03-16 09:20:52 1 [Note] InnoDB: Using Linux native AIO
2023-03-16 09:20:52 1 [Note] InnoDB: Not using CPU crc32 instructions
2023-03-16 09:20:52 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2023-03-16 09:20:52 1 [Note] InnoDB: Completed initialization of buffer pool
2023-03-16 09:20:52 1 [Note] InnoDB: Highest supported file format is Barracuda.
2023-03-16 09:20:52 1 [Note] InnoDB: The log sequence numbers 19065500 and 19065500 in ibdata files do not match the log sequence number 19065868 in the ib_logfiles!
2023-03-16 09:20:52 1 [Note] InnoDB: Database was not shutdown normally!
2023-03-16 09:20:52 1 [Note] InnoDB: Starting crash recovery.
2023-03-16 09:20:52 1 [Note] InnoDB: Reading tablespace information from the .ibd files...
2023-03-16 09:20:52 7fcc70a28040  InnoDB: Assertion failure in thread 140516039753792 in file fil0fil.cc line 1252
InnoDB: Failing assertion: fsp_flags_is_valid(flags)
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.6/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
09:20:52 UTC - mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.

key_buffer_size=8388608
read_buffer_size=131072
max_used_connections=0
max_threads=151
thread_count=0
connection_count=0
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 68109 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0 thread_stack 0x40000
mysqld(my_print_stacktrace+0x2c)[0x55d186c7fadc]
mysqld(handle_fatal_signal+0x4b1)[0x55d186a1a5f1]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0)[0x7fcc706010e0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf)[0x7fcc6f19dfff]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fcc6f19f42a]
mysqld(+0x8d7720)[0x55d186e0c720]
mysqld(+0x8dbab1)[0x55d186e10ab1]
mysqld(+0x7bdf21)[0x55d186cf2f21]
mysqld(+0x834977)[0x55d186d69977]
mysqld(+0x777d08)[0x55d186cacd08]
mysqld(_Z24ha_initialize_handlertonP13st_plugin_int+0x46)[0x55d1869688d6]
mysqld(+0x569bc1)[0x55d186a9ebc1]
mysqld(_Z11plugin_initPiPPci+0x76c)[0x55d186aa4d6c]
mysqld(+0x42bb9b)[0x55d186960b9b]
mysqld(_Z11mysqld_mainiPPc+0x3d8)[0x55d186961ac8]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fcc6f18b2e1]
mysqld(_start+0x2a)[0x55d18695584a]
The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.
```
