### ISSUE TITLE
Advice on setting environment variables for a process in a container

### ISSUE THREAD

**Issue by xlouba** [kubernetes/website#40394]
kubernetes can define environment variable for container with name and value.
`
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
`
How can I define the variable by executing command like this:
`
    env:
    - name: DEMO_GREETING
      value: "$(cat demo_greeting.md)"
`

**Comment by utkarsh-singh1** [comment]
Hey @xlouba, you can find about setting env variables and use them with the bash commands here - 
https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config

**Comment by utkarsh-singh1** [comment]
You can also try like this - 

> In terminal -
1. Setting environment varible - 

```bash
export hello="cat demo_greeting.md"
```

2. Invoking it - 

```bash
$hello
```
 


> In k8s Yaml - 
```yaml

# setting env variable
env:
    - name: DEMO_GREETING
      value: "cat demo_greeting.md"

# Invoking it
command: [$DEMO_GREETING]
 ```
