### ISSUE TITLE
Communicate Between Containers in the Same Pod Using a Shared Volume

### ISSUE THREAD

**Issue by gaurav-dubey-gitspace** [kubernetes/website#40450]
Document says "Notice that the second container writes the index.html file in the root directory of the nginx server". But it is not. It writes to /pod-data/index.html whereas the root dir for nginx should be /usr/share/nginx/html

**Comment by kundan2707** [comment]
@gaurav-dubey-gitspace  can you describe which page you are taking about

**Comment by gaurav-dubey-gitspace** [comment]
https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/

**Comment by kundan2707** [comment]
```
  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
```
mountPath for second container is pod-data it means on machine base directory for pod is located at /pod-data
