### ISSUE TITLE
ci: add dependabot

### ISSUE THREAD

**Issue by priyankarpal** [kubernetes/website#40612]
we should consider adding Dependabot to this project. Dependabot is a tool that automates dependency updates by monitoring a project's dependencies and notifying us when updates are available. Dependabot can also create pull requests to update our dependencies automatically, saving us time and effort.

code demo 

```
# dependabot.yml
version: 2
updates:
  # Update all npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Update to the latest version
    version: "latest"


```

I would like to work on this issue.
