### ISSUE TITLE
Improvement for k8s.io/docs/concepts/workloads/controllers/statefulset/

### ISSUE THREAD

**Issue by carlospalmaroldan** [kubernetes/website#40618]
Please provide a yaml example to create a stateful set that actually works. As it stands now the current example 
```yaml
volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
```
&hellip;references a `storageClassName` that does not exist. This makes it very difficult for newbies to see the stateful set actually deployed in the cluster (I am trying to deploy to minikube on my local machine but always end up with a message 1 pod has unbound immediate PersistentVolumeClaims).
