### ISSUE TITLE
Improvement for k8s.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config

### ISSUE THREAD

**Issue by tuxxi** [kubernetes/website#40857]
The "Using environment variables inside of your config" feature is great and has been very useful. Thanks!

I have two minor suggestions:

1. It would also be useful to document which fields of a container spec this interpolation applies (or if it applies to almost all fields, what the exceptions are.)

2. IMHO, the example is slightly confusing / misleading. The key feature that is documented here is the ability to *statically* use env vars defined in the config in other config fields.

While the example is calling `/bin/echo` with a single string, it may look at a glance like a shell command which would do the interpolation itself (note `$(VAR)` notation and not `$VAR` or `${VAR}`). 

Perhaps a clearer example would be using env vars inside of other env vars:

```
spec:
  containers:
  - name: env-print-demo
    image: bash
    env:
    - name: GREETING
      value: "Warm greetings to"
    - name: HONORIFIC
      value: "The Most Honorable"
    - name: NAME
      value: "Kubernetes"
    - name: MESSAGE
      value: "$(GREETING) $(HONORIFIC) $(NAME)"
    command: ["echo"]
    args: ["$(MESSAGE)"]


```

This shows more clearly that `MESSAGE` environment variable is configured statically from previously set environment variables - before the Pod is created, no shell interpolation involved.
