### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/network-policies/

### ISSUE THREAD

**Issue by EricBuist** [kubernetes/website#40858]
The page is not covering a pretty common case of targeting multiple namespaces by name. I need an egress policy allowing to send to pods in two namespaces, cannot find any way of doing it, will have to search on Google and hit tons of StackOverflow posts suggesting random solutions that may or may not work. I don't have enough privileges on the Kubernetes cluster to add labels to namespaces in order to search by label. This could be a lack of flexibility of network policies, or something missing from the documentation.

**Comment by mrgiles** [comment]
Hello, @EricBuist. unfortunately, it is not possible to directly specify the names of the namespaces in a `NetworkPolicy`. You must use a `namespaceSelector` with `matchLabels` or `matchExpressions` to select the namespaces based on their labels. 

Here is an example using labels:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-network-policy
spec:
  podSelector:
    matchLabels:
      app: my-app
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          namespace: namespace-1
    - namespaceSelector:
        matchLabels:
          namespace: namespace-2
```

You will have to find somebody in your organization with enough privileges to add the labels for you, if you don't have access to do it yourself.

Thanks! 

FYI: @tengqm
