### ISSUE TITLE
[bug] An error in the scheduler document

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes/website#41316]
There is a mistake in the scheduler framework configuration example website.
https://kubernetes.io/zh-cn/docs/reference/scheduling/config/#scheduler-configuration-migrations

```
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: multipoint-scheduler
    plugins:
      multiPoint:
        enabled:
        - name: 'CustomQueueSort'
        - name: 'CustomPlugin1'
          weight: 3
        - name: 'CustomPlugin2'
        disabled:
        - name: 'DefaultQueueSort'
      filter:
        disabled:
        - name: 'DefaultPlugin1'
      score:
        enabled:
        - name: 'DefaultPlugin2'
```
equals to 
```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: multipoint-scheduler
    plugins:
      # Disable the default QueueSort plugin
      queueSort:
        enabled:
        - name: 'CustomQueueSort'
        disabled:
        - name: 'DefaultQueueSort'
      # Enable custom Filter plugins
      filter:
        enabled:
        - name: 'CustomPlugin1'
        - name: 'CustomPlugin2'
        - name: 'DefaultPlugin2'
        disabled:
        - name: 'DefaultPlugin1'
      # Enable and reorder custom score plugins
      score:
        enabled:
        - name: 'DefaultPlugin2'
          weight: 1
        - name: 'DefaultPlugin1'
          weight: 1
        - name: 'CustomPlugin1'
          weight: 3
        - name: 'CustomPlugin2'
          weight: 1
```

Besides, extensions of default plugins will be called before the extensions of custom plugins before v1beta3, right?
This is also a change between v1beta2 and v1beta3 which is not been mentioned.

![image](https://github.com/kubernetes/website/assets/30817980/1ddf66bb-eeac-4b1e-a502-471a6c9c71af)
