### ISSUE TITLE
YAML AdmissionReview example in Dynamic Admission Control page is misleading and does not match wire format

### ISSUE THREAD

**Issue by eram** [kubernetes/website#41542]
example requests on this page should be in json format. not in yaml.
ref:
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#request

**Comment by dipesh-rawat** [comment]
/retitle Specify JSON format instead of YAML for example requests on `Dynamic Admission Control` page

**Comment by sftim** [comment]
If you mean the example following _This example shows the data contained in an AdmissionReview object for a request to update the scale subresource of an apps/v1 Deployment:_, then it's IMO much more readable expressed as YAML.

If we switch it to JSON, we'll need to delete all the comments.

However, we should make it very clear that the example is _not_ the wire format.

**Comment by rukundob451** [comment]
Hey @sftim, how would you want to make it very clear that the example is not the wire format?

**Comment by sftim** [comment]
Try this:
```yaml
## This shows an example AdmissionReview request.
## The example is encoded as YAML so that there can be explanatory comments.
## However, this is not the format you should expect for your own webhook.
## The HTTP body of an AdmissionReview request to an admission webhook is typically encoded as JSON.

apiVersion: admission.k8s.io/v1
kind: AdmissionReview
request:
  # Random uid uniquely identifying this admission call
  uid: 705ab4f5-6393-11e8-b7cc-42010a800002
```
