### ISSUE TITLE
Discrepancies in comments and explanation for 'omitStages' rule in example audit-policy yaml

### ISSUE THREAD

**Issue by choshitautetsu** [kubernetes/website#41622]
[audit/audit-policy.yaml](https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/#audit-policy)

```yaml
apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"
rules:
...
  # A catch-all rule to log all other requests at the Metadata level.
  - level: Metadata
    # Long-running requests like watches that fall under this rule will not
    # generate an audit event in RequestReceived.
    omitStages:
      - "RequestReceived"
 ```

[Policy](https://kubernetes.io/docs/reference/config-api/apiserver-audit.v1/#audit-k8s-io-v1-Policy)
> OmitStages is a list of stages for which no events are created.   

So the comment of the first `omitstages` is `Don't generate audit events for all requests in RequestReceived stage`

But in the end the comment of `omitstages` under the rule is `generate an audit event in RequestReceived`

So I wonder whether the explanation about `omitstages` under the rule is incorrect, 

whether it should be `A catch-all rule to log all other requests at the Metadata level besides RequestReceived stage`
