### ISSUE TITLE
Issue with k8s.io/docs/concepts/scheduling-eviction/taint-and-toleration/

### ISSUE THREAD

**Issue by mofarook** [kubernetes/website#41748]
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"
```

---

where is value ???
" "==> is not working
