### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/statefulset/

### ISSUE THREAD

**Issue by diepes** [kubernetes/website#41755]
After reading the documentation i am still not sure how i would configure a statefullset to ensure the deployment to specific availability zones using node affinity.

goal fix db statefullset instances in separate availability zone's using labels on nodes.
e.g.
```
db-0 -> zone-1
db-1 -> zone-2
db-2 -> zone-3
```

This is to ensure that the same $(ordinal) lands in the same zone where it can access it's PVC.

I tried something like this, but my understand is it will not achieve the mapping required above.
need something like '- "australiaeast-${ordinal}"'
```
    affinity:  # db
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          preference:
            matchExpressions:
            - key: "topology.kubernetes.io/zone"
              operator: In
              values:
              - "australiaeast-1"
              - "australiaeast-2"
              - "australiaeast-3"
```

Is this possible (just not in documentation) or something k8s can't do currently ?
