### ISSUE TITLE
Enhance description of StorageClass resource to reflect update capability in "Storage Classes" page

### ISSUE THREAD

**Issue by chenzhiwei** [kubernetes/website#41821]
**This is a Feature Request**

**What would you like to be added**

https://kubernetes.io/docs/concepts/storage/storage-classes/#the-storageclass-resource

The document said:

> The name of a StorageClass object is significant, and is how users can request a particular class. Administrators set the name and other parameters of a class when first creating StorageClass objects, and **the objects cannot be updated once they are created.**

But for some use cases, the labels, annotations and parameters are required to be updated, and they actually can be updated.

Such as adding more storage pools to a storage class through parameters.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-name
provisioner: example.com/storage
parameters:
  pools: pool1,pool2,pool3
```

**Why is this needed**

The description of storage class is not accurate.

**Comments**
