### ISSUE TITLE
Configure Service Accounts for Pods

### ISSUE THREAD

**Issue by ghost** [kubernetes/website#42005]

**Comment by spilankar** [comment]
I haved perfomed following steps
1. Created a service account with following content
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intelinotion-bot
automountServiceAccountToken: false
```
2. then created secret with following file
```
apiVersion: v1
kind: Secret
metadata:
  name: intelinotion-bot
  annotations:
    kubernetes.io/service-account.name: intelinotion-bot
type: kubernetes.io/service-account-token
```
3. added that secrets in my deployment file to get token inide my pod
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelinotion-monitor
  namespace: intelinotion-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      service: intelinotion-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: intelinotion-bot
        networking/allow-email-server: "true"
        networking/allow-internet-access: "true"
        service: intelinotion-monitor
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - /bin/sh
        - -c
        - EMAIL_PASSWORD=$(cat /mnt/.kv-secrets/IN-EMAIL-PASSWORD) sh ./build/shell-scripts/intelinotion-utilization-GraphDB.sh
        env:
        - name: EMAIL_HOST
          value: smtp.office365.com
        - name: EMAIL_ID
          value: service@intelinotiondev.onmicrosoft.com
        - name: EMAIL_PORT
          value: "587"
        - name: NAMESPACE
          value: intelinotion
        - name: RECIPIENTS
          value: spilankar@intelinotion.com
        image: inaksdevacr.azurecr.io/intelinotion-bot:2023r2bot-p1
        imagePullPolicy: IfNotPresent
        name: intelinotion-monitor
        resources: {}
        securityContext:
          capabilities:
            drop:
            - all
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount/token
          name: intelinotion-bot
        - mountPath: /mnt/.kv-secrets
          name: intelinotion-graphdb-kv-secrets
        - mountPath: /mnt/monitor
          name: intelinotion-bot-pv
          subPath: intelinotion-bot
        - mountPath: /usr/src/app/attachments
          name: tmpfs-1
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-auth
      nodeSelector:
        agentpool: apppool
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: intelinotion-bot
      serviceAccountName: intelinotion-bot
      terminationGracePeriodSeconds: 30
      volumes:
      - name: intelinotion-bot
         secret:
           secretName: intelinotion-bot
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: intelinotion-graphdb-kv-secrets
        name: intelinotion-graphdb-kv-secrets
      - emptyDir: {}
        name: tmpfs-1
      - name: intelinotion-bot-pv
        persistentVolumeClaim:
          claimName: intelinotion-bot-pvc
```
But after excuting all the steps pod isup and running but not able to run kubectl command if I allow to automount the api credential  then kubectl command works as expected.
