### ISSUE TITLE
Copy To Clipboard breaks YAML format

### ISSUE THREAD

**Issue by andreygoran** [kubernetes/website#42179]
#### Description

YAML code examples have a Copy To Clipboard function. This function is broken on several pages. Example: `service/networking/example-ingress.yaml` code example in [/docs/tasks/access-application-cluster/ingress-minikube/](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/)
 
When you click the Copy To Clipboard icon, the following code is copied:
```
apiVersion: networking.k8s.io/v1
   kind: Ingress
   metadata:
     name: example-ingress
     annotations:
       nginx.ingress.kubernetes.io/rewrite-target: /$1
   spec:
     rules:
       - host: hello-world.info
         http:
           paths:
             - path: /
               pathType: Prefix
               backend:
                 service:
                   name: web
                   port:
                     number: 8080
```

which is not correct YAML because of extra indentation on all lines except of the first line:

```
$ kubectl apply -f ingress.yaml
error: error parsing ingress.yaml: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context
```

#### Root cause

Indentation is broken when `codenew` element responsible for rendering of code is itself indented, for example when it's part of ordered or unordered list:

```
1. Create `example-ingress.yaml` from the following file:

   {{< codenew file="service/networking/example-ingress.yaml" >}}
```

There are several places like this:
* https://github.com/kubernetes/website/blob/ff6d646409052bc001ae101faf1ca2817fbf9392/content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md?plain=1#L550
* https://github.com/kubernetes/website/blob/ff6d646409052bc001ae101faf1ca2817fbf9392/content/en/docs/tasks/job/pod-failure-policy.md?plain=1#L88
* and more
