### ISSUE TITLE
Secrets: section "Use case: Pods with prod / test credentials» is a bit confusing

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42235]
The example in [this section](https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pods-with-prod-test-credentials) is confusing. The way to shorten the specification is unclear because something is missing.

Consider to add information about "service account — secret" relationship, e.g:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-db-client
imagePullSecrets:
- name: prod-db-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-db-client
imagePullSecrets:
- name: test-db-secret
```

Also, the secrets destination directory is going to be different (default `/run/secrets/kubernetes.io/`) since no volume is specified.

<br>

> You could further simplify the base Pod specification by using two service accounts:
>  - prod-user with the prod-db-secret
>  - test-user with the test-db-secret
> The Pod specification is shortened to:
> ```yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   name: prod-db-client-pod
>   labels:
>     name: prod-db-client
> spec:
>   serviceAccount: prod-db-client
>   containers:
>     - name: db-client-container
>       image: myClientImage
> ```
