### ISSUE TITLE
kubelet does not reload recreated immutable configmap, unclear documentation

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes/website#42359]
### What happened?

With immutable configmaps and secrets are not watched by the kubelet. This also means it does not refresh the loaded content when they are deleted and recreated.

The documentation of immutable configmaps though is misleading on how this needs to be handled by pods:
https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable

> Once a ConfigMap is marked as immutable, it is not possible to revert this change nor to mutate the contents of the data or the binaryData field. You can only delete and recreate the ConfigMap. Because existing Pods maintain a mount point to the deleted ConfigMap, it is recommended to recreate these pods.

This to me implies deleting and recreating the configmap and restarting the pods using it is sufficient, but it is not as the kublet will still have the old version loaded and won't update it until it is restarted.

This behavior is more or less expected but the documentation should be more explicit about this pitfall.

### What did you expect to happen?

The documentation should state that immutable objects mounted into pods need to be deleted and recreated with a **different name** in order for the (recreated) pods to see the new version reliably.

### How can we reproduce it (as minimally and precisely as possible)?

Start a deployment with an immutable configmap mounted. Change it, delete and recreate it with the same name and restart the deployment.
Pods on the kubelet will still have the old version until the kubelet is restarted.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

```
</details>

### Cloud provider

bare metall

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
I believe from the evidence here that we may be able build a test case where, starting from a namespace that contains:
- no ConfigMaps
- no Pods

can create a ConfigMap and a Pod that references the ConfigMap, and (because of what was _previously_ in that namespace) see the old ConfigMap loaded into that Pod. Even if the new ConfigMap is not marked as immutable.

The period where that's possible might be quite short though.

---

This sounds more plausible;  starting from a namespace that contains:
- no ConfigMaps
- some running Pods that reference a previous immutable ConfigMaps

create a new ConfigMap (same name) and a new Pod. You may observe that the new Pod appears to have loaded the wrong data, from the old ConfigMap.

We might need to define that you should delete _every object_ that could have had a reference to that old ConfigMap - potentially including cluster-scoped objects such as IngressClasses and ValidatingAdmissionPolicies.

Advising people to create the replacement ConfigMap with a different name is not enough; we cannot assume that a different user is aware of the potential problems around use of the old name.

**Comment by sftim** [comment]
We _might_ be able to detect in-use immutable ConfigMaps (within the control plane), and do something around finalizing them. That mechanism could eventually enable sending a [warning](https://kubernetes.io/blog/2020/09/03/warnings/) when an immutable ConfigMap is deleted whilst still in use.

**Comment by sftim** [comment]
I recommend that SIG Architecture chip in here.

/sig architecture

**Comment by pegasas** [comment]
Hi, @sftim , 
I do the test case that you mentioned in Azure Kubernetes 1.25.11,
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  special.how: test
immutable: true
```
and
```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "3650d"
    env:
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.how
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
```
and I create these 2 in k8s cluster, and echo the key:
```
kubectl exec -it ubuntu -- /bin/sh
# echo $SPECIAL_LEVEL_KEY
very
```
and after I delete the cm, it keeps the same value:
```
kubectl exec -it ubuntu -- /bin/sh
# echo $SPECIAL_LEVEL_KEY
very
```

**Comment by tengqm** [comment]
The motivation for Immutable ConfigMap/Secret is to avoid watching them. Since they are immutable, you get what is in it, and treat it as constant. You don't care about the future changes to them, they are immutable after all. If you want to watch them, especially for updates, you won't use immutable ConfigMap/Secret.

Protecting ConfigMap/Secret in use is another topic. See [KEP 2840](https://github.com/kubernetes/enhancements/pull/2840).

**Comment by sftim** [comment]
The test case explained in https://github.com/kubernetes/website/issues/42359#issuecomment-1663073555 covers already documented behavior; if that's the test case, I don't think we need to make a docs change.

I thought you were concerned about ConfigMap removal _and recreation with a new `uid`_ @juliantaylor, where a _new_ Pod might see the old ConfigMap.

**Comment by juliantaylor** [comment]
Protecting a configmap from being deleted while it is in use is not sufficient, a configmap or secret name cannot be reused after it has been deleted until all kubelets have been restarted or you risk a pod seeing old content.

This likely also happens long after all pods using the old version are long gone (create deployment and cm, delete it, wait some time redeploy with different configmap), though I have not explicitly verified longer timescales.

The practical solution to this is to have immutable configmaps and secrets name contain the checksum of its content. That way it is almost impossible for wrong data to end in a pod even when the kubelet runs for a long time.
This practice should be mentioned in the documentation.

If you can fix the underlying issue all the better, but as stated the point of immutable is to reduce api requests and watches, so watching for deletes is not an sensible option.

Possibly you could have the kubelet refetch the object when it is required but only if it already exists as immutable in its caches.

**Comment by sftim** [comment]
> The practical solution to this is to have immutable configmaps and secrets name contain the checksum of its content. 

Let's make sure we know what (replicable) problem we're helping people to avoid, before we triage this as accepted.

**Comment by juliantaylor** [comment]
ok here the reproducer I stated in the beginning written out:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: cm-test
spec:
  replicas: 7
  selector:
    matchLabels:
      app: cm-test
  template:
    metadata:
      labels:
        app: cm-test
    spec:
      terminationGracePeriodSeconds: 1
      volumes:
        - name: cm
          configMap:
            name: testcm
      containers:
      - image: debian:bookworm
        command:
          - bash
          - "-c"
          - 'while true; do echo -n "$NODENAME "; md5sum /cm/script.py || true; sleep 20; done'
        imagePullPolicy: Always
        name: test
        securityContext:
          runAsUser: 1000
        volumeMounts:
          - name: cm
            mountPath: /cm
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testcm
data:
  script.py: "content7"
immutable: true
```

```
kubectl apply -f deployment.yaml
logs:
kworker-be-sandbox-iz2-bap004 f4a40d590cbb53290e7ba914e24a346c  /cm/script.py
kubectl delete cm testcm
sed -i -e "s/content7/content8/" deployment.yaml
kubectl apply -f deployment.yaml
logs (same checksum)
kworker-be-sandbox-iz2-bap004 f4a40d590cbb53290e7ba914e24a346c  /cm/script.py
```

restart the kubelet or launch on a node teh pod was not on yet and you get the new content
