### ISSUE TITLE
Incorrect example for 'Services without selectors' in "Service" page

### ISSUE THREAD

**Issue by yujianet** [kubernetes/website#42405]
```
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-service-1 # by convention, use the name of the Service
………………omit………the following part is wrong………
endpoints:
  - addresses:
      - "10.4.5.6" # the IP addresses in this list can appear in any order
      - "10.1.2.3"
```
The correct is:
```
endpoints:
  - addresses:
      - "10.4.5.6"
  - addresses:
      - "10.1.2.3"
```
