### ISSUE TITLE
Unclear documentation about sidecar containers

### ISSUE THREAD

**Issue by parimaljanagithub** [kubernetes/website#42762]
restartPolicy under initContainers is not allowing to create Jobs specified into the below documents

Error Message: 
Job in version "v1" cannot be handled as a Job: strict decoding error: unknown field "spec.template.spec.initContainers[0].restartPolicy"

Document Link:
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#pod-restart-reasons

**Comment by thisisharrsh** [comment]
Hi @parimaljanagithub, I believe the error message you are getting is because you might have used `restartpolicy` feild under the  `initcontainers` section. But it is not allowed under the `initcontainers`. 

/language en

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#pod-restart-reasons_ 
/sig docs 
/sig node

**Comment by thisisharrsh** [comment]
Could you please provide the code block with proper indentation?

**Comment by parimaljanagithub** [comment]
updated above section

**Comment by tamilselvan1102** [comment]
The indentation should be corrected as below
```
initContainers:
      - name: logshipper
        image: alpine:latest
        restartPolicy: Always
        command: ['sh', '-c', 'tail -F /opt/logs.txt']
        volumeMounts:
          - name: data
            mountPath: /opt
        restartPolicy: Never
```

**Comment by sftim** [comment]
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#api-for-sidecar-containers mentions a feature gate, but doesn't make it explicitly clear that you need to enable it. The feature gate is named `SidecarContainers`.

The fix I recommend:
- add a brand new page https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
- edit https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#api-for-sidecar-containers to direct readers to that new page

/remove-kind bug

I don't think there is anything actually incorrect.
/triage accepted
/retitle Unclear documentation about sidecar containers

**Comment by T-Lakshmi** [comment]
Is anybody working to fix this issue? If no, i can take it.

**Comment by kumarankit999** [comment]
Feel free to involve me, if you need any help.

**Comment by T-Lakshmi** [comment]
@kumarankit999 Sure, Thank you.

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/43610

**Comment by sftim** [comment]
To learn more, you can read (but **_not_** plagiarize) https://loft.sh/blog/kubernetes-init-containers/

**Comment by Sivakajan-tech** [comment]
Hi, I also having this problem I tried to add restartPolicy as `Always` to under containers and init containers, but I get the same error.
```
Error from server (BadRequest): error when creating "MakeChunks/hello.yaml": Deployment in version "v1" cannot be handled as a Deployment: strict decoding error: unknown field "spec.template.spec.containers[0].restartPolicy", unknown field "spec.template.spec.initContainers[0].restartPolicy"
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash
spec:
  selector:
    matchLabels:
      app: bash
  template:
    metadata:
      labels:
        app: bash
    spec:
      restartPolicy: Always  #1
      containers: # List of containers, not another list within spec
        - name: bash
          image: ubuntu:latest
          resources:
            limits:
              cpu: "700m"
              memory: "200Mi"
            requests:
              cpu: "700m"
              memory: "200Mi"
          resizePolicy:
            - resourceName: "cpu"
              restartPolicy: "NotRequired"
            - resourceName: "memory"
              restartPolicy: "RestartContainer"
          command: ["tail", "-f", "/dev/null"]
          restartPolicy: Always  #2
      initContainers: # Optional init containers, not nested in another list
        - name: init-1
          image: ubuntu:latest
          command:
            - sh
            - "-c"
            - "sleep 1s \n"
          restartPolicy: Always  #3
```
I do not got any errors for the `# 1` restartPolicy, but `#2` and `#3` are gave the error mentioned at the top. 

Im using Minikube, and my 
```
 % kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.0-rc.0", GitCommit:"cf60ee25590ac79334f823b7f03cf33105a442c1", GitTreeState:"clean", BuildDate:"2023-03-23T18:59:06Z", GoVersion:"go1.20.2", Compiler:"gc", Platform:"linux/arm64"}

```

CC: @tamilselvan1102 @thisisharrsh @T-Lakshmi Your suggestions highly appriciatable
