### ISSUE TITLE
Namespace not specified in example yaml on 'Configure Default Memory Requests and Limits for a Namespace' page

### ISSUE THREAD

**Issue by WolfgangKrueger** [kubernetes/website#42772]
Hello,
 in the examples the namespace is missing:

memory-defaults.yaml
```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: default-mem-example
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
```

pod-memory-defaults.yaml 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: default-mem-demo
  namespace: default-mem-example
spec:
  containers:
  - name: default-mem-demo-ctr
    image: nginx
```

and others...

best regards
