### ISSUE TITLE
Documentation lacks clarity on adding control-plane nodes with external etcd using kubeadm

### ISSUE THREAD

**Issue by LoRKaa** [kubernetes/website#42782]
### What happened:
When attempting to add a new control-plane node to a Kubernetes cluster with an external etcd, using the default kubeadm command resulted in the external etcd cluster's certificate being overwritten or corrupted.

### What you expected to happen:
The documentation on setting up a highly available Kubernetes cluster with kubeadm and an external etcd should provide clear warnings or guidance on this potential issue. I followed the instructions from the following links:

[Setting up a HA etcd cluster with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/)
[Setting up HA Kubernetes with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/)

### Steps to reproduce:
Set up a Kubernetes cluster with an external etcd following the official documentation linked above.
Attempt to add a new control-plane node using the default kubeadm command as suggested in the documentation.

### Solution that worked:
I had to create a custom kubeadm configuration file:

```
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
controlPlane:
  localAPIEndpoint:
    advertiseAddress: "10.1.1.51"
    bindPort: 6443
  certificateKey: "f7b1fd2db6f82731617d32f4991c11d56e49c140aea3f9ea50efc36825725028"
discovery:
  bootstrapToken:
    apiServerEndpoint: "10.1.1.250:6443"
    token: x63wk9.sfxq39oynypxdemf
    caCertHashes:
    - "sha256:d8894fe8ca0eff1928c4ee8bcb7c6d1af323b0ad0f05c7bf583bee6f02243e5f"
  tlsBootstrapToken: x63wk9.sfxq39oynypxdemf
etcd:
  external:
    endpoints:
      - https://10.1.1.18:2379
      - https://10.1.1.51:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/etcd/server.crt
    keyFile: /etc/kubernetes/pki/etcd/server.key
```
And then used the following command to join the node:
```
kubeadm join --config=kubeadm-config.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml
```
