### ISSUE TITLE
Documention issue on Using RBAC Authorization page

### ISSUE THREAD

**Issue by virtualkyle378** [kubernetes/website#43118]
While following the docs to create my own RBAC policies, I found an issue under https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-example, specifically with the code block included below it:

```
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
# You can specify more than one "subject"
- kind: User
  name: jane # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: pod-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
```

If I try and apply this, Kubernetes returns an error
```
RoleBinding.rbac.authorization.k8s.io "read-pods" is invalid: subjects[0].apiGroup: Unsupported value: "rbac.authorization.k8s.io": supported values: "".
```

It would appear that 
```
- kind: User
  name: jane # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
```
Should instead just be
```
- kind: User
  name: jane # "name" is case sensitive
  apiGroup: ""
```
