### ISSUE TITLE
Network Policies not properly formatted

### ISSUE THREAD

**Issue by nanachimi** [kubernetes/website#43169]
In the [documentation](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource), shouldn't be the field `ports` specified as item of the `egress` or `ingress`?  To me it looks like `-` is missing

My update version of the file [service/networking/networkpolicy.yaml](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/networking/networkpolicy.yaml) get validated properly on killer.sh and yours is rejected.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
      - ipBlock:
          cidr: 172.17.0.0/16
          except:
            - 172.17.1.0/24
      - namespaceSelector:
          matchLabels:
            project: myproject
      - podSelector:
          matchLabels:
            role: frontend
  - ports:
    - protocol: TCP
      port: 6379
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/24
  - ports:
    - protocol: TCP
      port: 5978

```
