### ISSUE TITLE
Seccomp profile RuntimDefault kind cluster doesn't bootstrap

### ISSUE THREAD

**Issue by dancer1325** [kubernetes/website#43733]
**This is a Bug Report**
* Imposible to make it run the kind cluster, specified in the section [RuntimeDefault as the default seccomp profile for all workloads](https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads)

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            seccomp-default: "true"        
  - role: worker
    image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            seccomp-default: "true" 
```

**Problem:**
* The errors that I am getting
> ERROR: failed to create cluster: failed to join node with kubeadm: command "docker exec --privileged kind-worker kubeadm join --config /kind/kubeadm.conf --skip-phases=preflight --v=6" failed with error: exit status 1
> found NodeName empty; using OS hostname as NodeName
> loading configuration from "/kind/kubeadm.conf"

**Proposed Solution:**

* Not found, yet a solution .. 😢 
* Attempts:
  * Attempt1: `kind: JoinConfiguration \ name: "worker-node"` 
  * Attempt2: `kubeletExtraArgs: \  nodeName: "worker-node"`

**Page to Update:**
https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads

**Note:**
* My setUp is: macOs Ventura v.13.1 arm164, kind v0.20.0
