### ISSUE TITLE
May be it is mistake in affinity operators description 

### ISSUE THREAD

**Issue by ppavelikus** [kubernetes/website#43754]
**This is a Bug Report**
Hello i re-read affinity  documentation and i found mistake in chapter [Operators](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#operators)
Please, fix this.

**Problem:**
I marked it in bold font.

<html>
<body>

Operator | Behaviour
-- | --
**Gt** | The supplied value will be parsed as an integer, and that integer is **less than** the integer that results from parsing the value of a label named by this selector
**Lt** | The supplied value will be parsed as an integer, and that integer is **greater than** the integer that results from parsing the value of a label named by this selector

</body>
</html>

**Proposed Solution:**

<html>
<body>

Operator | Behaviour
-- | --
**Lt** | The supplied value will be parsed as an integer, and that integer is **less than** the integer that results from parsing the value of a label named by this selector
**Gt** | The supplied value will be parsed as an integer, and that integer is **greater than** the integer that results from parsing the value of a label named by this selector

</body>
</html>

**Page to Update:**
[Operators](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#operators)

**Comment by T-Lakshmi** [comment]
/language en
/sig docs
**page:** https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#operators

**Comment by sftim** [comment]
I think the page is correct, but hard to understand. An example might help:

Let's say you have a node labelled as `foo: "800"` and a Pod defined by:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: foo
            operator: Gt
            values:
            - "500" # this this the value that is parsed and compared to a label value
  # more Pod spec here
```

Then the the supplied value (`"500"`) will be parsed as an integer (`500` again), and that integer **is** less than the integer (`800`) that results from parsing the value (`"800"`) of a label (`foo`) named by this selector.
