### ISSUE TITLE
Naming Rule of Dynamic Admission Control Configuration

### ISSUE THREAD

**Issue by hiwayama** [kubernetes/website#43788]
Hi.
I have a question about the information in this document.

There seems to be a specification as follows.

> To register admission webhooks, create MutatingWebhookConfiguration or ValidatingWebhookConfiguration API objects. The name of a MutatingWebhookConfiguration or a ValidatingWebhookConfiguration object must be a valid [DNS subdomain name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names#dns-subdomain-names).

But there is not a restriction to make .metadata.name itself a valid DNS subdomain. 
The constraint seems to be on .webhooks.rules.name.

https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#webhook-configuration

```
# valid example
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: this-is-not-dns-subdomain
webhooks:
  - name: foo.example.com
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "*" ]
        apiVersions: [ "v1alpha2" ]
        resources: [ "*" ]
```

```
# invalid example(error occured)
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: this-is-valid-subdomain.example.com
webhooks:
  - name: this-is-not-subdomain
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "*" ]
        apiVersions: [ "v1alpha2" ]
        resources: [ "*" ]
```

Is this correct as a document?

Thank you.
