### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

### ISSUE THREAD

**Issue by abushoeb** [kubernetes/website#4390]
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
In pod specification, we can use schedulerName to define a custom scheduler but when we use this for Deployment it has an error. 

**Proposed Solution:**
Can we add spec.schedulerName for Deployment as well?

**Page to Update:**
http://kubernetes.io/...

1.6.4

**Comment by zacharysarah** [comment]
@abushoeb Thanks for opening this issue. I've flagged it for technical review.

**Comment by abushoeb** [comment]
I think we need to use pod template under the spec of Deployment in order to use schedulerName for the custom scheduler. I tried this and it looks like working.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      schedulerName: my-custom-scheduler
      containers:
        - name: nginx
          image: "nginx:1.11.1-alpine"
```
