### ISSUE TITLE
Network Policies: label must also be in set to `spec.selector`  in Service resource for egress PodSelector to work

### ISSUE THREAD

**Issue by headyj** [kubernetes/website#43954]
The documentation is mentioning:

_**podSelector**: This selects particular Pods in the same namespace as the NetworkPolicy which should be allowed as ingress sources or egress destinations._

In fact, the label also had to be set to `spec.selector` on the Service resource for the policy to be working:

it's easy to test:

**network-policies.yaml**
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns
spec:
  egress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  podSelector: {}
  policyTypes:
  - Egress
```

**backend.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: network-multitool-orchestrator
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
          protocol: TCP
        command:
          - "/bin/sh"
          - "-c"
        args:
          - "sleep 5000"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: frontend
  podSelector:
    matchLabels:
      app.kubernetes.io/component: backend
  policyTypes:
  - Egress
```

**frontend.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        name: frontend
    spec:
      containers:
      - image: nginx:1.23.3
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: frontend-service-1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: frontend-service-2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: frontend
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/component: frontend
  policyTypes:
  - Egress
  - Ingress
```

**result from the backend:**
```
backend-c645bfb5d-jgpkm:/# nc -v frontend-service-1 80
nc: frontend-service-1 (10.100.23.79:80): Operation timed out

backend-c645bfb5d-jgpkm:/# nc -v frontend-service-2 80
frontend-service-2 (10.100.254.28:80) open
```
