### ISSUE TITLE
[zh]  Incorrect YAML format in `static-web.yaml` example in "Create static Pods" page

### ISSUE THREAD

**Issue by testwill** [kubernetes/website#44071]
```
# Execute the following command on the node where kubelet is running
mkdir -p /etc/kubernetes/manifests/
cat <<EOF >/etc/kubernetes/manifests/static-web.yaml
apiVersion: v1
kind: Pod
metadata:
name: static-web
labels:
 role: myrole
spec:
containers:
 - name: web
   image: nginx
   ports:
     - name: web
       containerPort: 80
       protocol: TCP
EOF
```
There is something wrong with this format

**Comment by T-Lakshmi** [comment]
@testwill,
Please open issue in English language.

**Comment by T-Lakshmi** [comment]
Page: https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

**Comment by T-Lakshmi** [comment]
/language zh

@testwill,
I don't see any format issue in this, please mention what issue you are facing in this.

**Comment by T-Lakshmi** [comment]
```
apiVersion: v1
kind: Pod
metadata:
 name: static-web
 labels:
  role: myrole
spec:
 containers:
  - name: web
    image: nginx
    ports:
      - name: web
        containerPort: 80
        protocol: TCP
```

I am able to create a pod sucessfully with the format mention in the page.

**Comment by T-Lakshmi** [comment]
/kind bug

Below is the correct format:
```
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
```
