### ISSUE TITLE
Example: Deploying PHP Guestbook application with Redis

### ISSUE THREAD

**Issue by selganor74** [kubernetes/website#44190]
The yaml file in "Creating the Guestbook Frontend Deployment" uses an image no more available ( `gcr.io/google_samples/gb-frontend:v5` )

I solved the issue by using `corelab/gb-frontend`

Here is the working version I used!

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: guestbook
        tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: corelab/gb-frontend:v5
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
```
