### ISSUE TITLE
Bug in example NetworkPolicy manifest

### ISSUE THREAD

**Issue by gacunto** [kubernetes/website#44214]
In the code example, a dash "-" is missing before the ports fields bellow the egress and ingress fields.

- egress:
  - ports:

**Comment by tamilselvan1102** [comment]
Egress rules are defined with the following fields.

ports: an array of NetworkPolicyPort (port, endport, protocol)
to: an array of NetworkPolicyPeer (ipBlock, namespaceSelector, podSelector)

so the Egress yaml structure would be
egress:
    - to:
       ports:

**Comment by tamilselvan1102** [comment]
if you understood, please close the issue

**Comment by kumarankit999** [comment]
I would like to work on this! but can you show more evidence for this issue!!

**Comment by gacunto** [comment]
According to kubectl explain:

~ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.7+k3s2", GitCommit:"575bce7689f4be112bd0099362fb8d5f2e39398e", GitTreeState:"clean", BuildDate:"2023-11-08T01:59:21Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/arm64"}

~ kubectl explain netpol.spec.ingress
GROUP:      networking.k8s.io
KIND:       NetworkPolicy
VERSION:    v1

**FIELD: ingress <[]NetworkPolicyIngressRule>**

DESCRIPTION:
    **ingress is a list of ingress rules** to be applied to the selected pods.
    Traffic is allowed to a pod if there are no NetworkPolicies selecting the
    pod (and cluster policy otherwise allows the traffic), OR if the traffic
    source is the pod's local node, OR if the traffic matches at least one
    ingress rule across all of the NetworkPolicy objects whose podSelector
    matches the pod. If this field is empty then this NetworkPolicy does not
    allow any traffic (and serves solely to ensure that the pods it selects are
    isolated by default)
    NetworkPolicyIngressRule describes a particular set of traffic that is
    allowed to the pods matched by a NetworkPolicySpec's podSelector. The
    traffic must match both ports and from.

FIELDS:
  **from	<[]NetworkPolicyPeer>**
    **from is a list of sources** which should be able to access the pods selected
    for this rule. Items in this list are combined using a logical OR operation.
    If this field is empty or missing, this rule matches all sources (traffic
    not restricted by source). If this field is present and contains at least
    one item, this rule allows traffic only if the traffic matches at least one
    item in the from list.

  **ports	<[]NetworkPolicyPort>**
    **ports is a list of ports** which should be made accessible on the pods
    selected for this rule. Each item in this list is combined using a logical
    OR. If this field is empty or missing, this rule matches all ports (traffic
    not restricted by port). If this field is present and contains at least one
    item, then this rule allows traffic only if the traffic matches at least one
    port in the list.

According to my understanding, all of ingress, ports and from are lists so their items must start with a dash.
So the example should be:

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
        - namespaceSelector:
            matchLabels:
              project: myproject
        - podSelector:
            matchLabels:
              role: frontend
    - ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
    - ports:
        - protocol: TCP
          port: 5978

I had a question about a netpol in the simulator of the CKAD certification (egress netpol only) and I copied and pasted this example.
The solution was wrong and I needed to add a "-" before ports in order to make it work.

**Comment by sftim** [comment]
We're confident that the documentation doesn't need a correction.

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
        - namespaceSelector:
            matchLabels:
              project: myproject
        - podSelector:
            matchLabels:
              role: frontend
    - ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
    - ports:
        - protocol: TCP
          port: 5978
```
has two ingress rules and two egress rules.

---

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
        - namespaceSelector:
            matchLabels:
              project: myproject
        - podSelector:
            matchLabels:
              role: frontend
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 5978
```
has one ingress rule where the source IP address range and port specification must both match.
It also has one egress rule where the destination IP address range and port specification must both match.

You could read other web pages about NetworkPolicy to make sure that you have understood your confusion @gacunto. There's nowt to fix.
