### ISSUE TITLE
Is the note about the restriction to proxy selectorless services still valid?

### ISSUE THREAD

**Issue by dancer1325** [kubernetes/website#44398]
**This is Support**

* Maybe I am misreading the next indicated constraint about proxying the service without selectors -- https://kubernetes.io/docs/concepts/services-networking/service/#service-no-selector-access --

> The Kubernetes API server does not allow proxying to endpoints that are not mapped to pods. Actions such as kubectl proxy service-name where the service has no selector will fail due to this constraint. 

But I am not getting any constraint about proxying it .... 🤔 

**How to reproduce:**
* `kind create cluster` -- use simple default kind cluster with 1 node --
* Dummy Service without selectors to create
  * Example:
```
apiVersion: v1
kind: Service
metadata:
  name: external-name-without-selectors
spec:
  type: ExternalName
  externalName: without.selectors
```
* `kubectl proxy external-name-without-selectors`
  * I don't get any restriction and you can access to the Kubernetes API Server through the default port locally -- "Starting to serve on 127.0.0.1:8001" --

**Note:** 
* Tracing the PR and issue about this note
  * https://github.com/kubernetes/website/pull/38617
  * https://github.com/kubernetes/website/pull/29752
  * https://github.com/kubernetes/kubernetes/issues/105092
