### ISSUE TITLE
Rephrase that expressions in matchExpressions are ANDed expressions, without needed to SATISFY ALL

### ISSUE THREAD

**Issue by dancer1325** [kubernetes/website#44582]
**This is a Bug Report**
* Rephrase that multiple expressions in `matchExpressions` are ANDed, but **WITHOUT** indicating that ALL are required to fulfil to assign the pod onto a node, since that depends on the node affinity selected

**Problem:**
In the section https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity , you can read

> If you specify multiple expressions in a single matchExpressions field associated with a term in nodeSelectorTerms, then the Pod can be scheduled onto a node only if all the expressions are satisfied (expressions are ANDed).

which could be misleading the part 

> then the Pod can be scheduled onto a node only if all the expressions are satisfied

since there is no specification about the nodeAffinity's type -> you could misunderstand that they are also REQUIRED to be fulfilled also in case they are used for `preferredDuringSchedulingIgnoredDuringExecution`, that it's not the case AT ALL.

Simple example confirming it:
* `kind create cluster`
* Simple manifest pod with several expressions, saved the manifest as 'pod.yaml' using `preferredDuringSchedulingIgnoredDuringExecution`

```
apiVersion: v1
kind: Pod
metadata:
  name: severalmatchexpressions-2
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: both.severalmatch/2.1            # Node with this label
                operator: In
                values: 
                  - "true"
                  - "yes"
              - key: both.severalmatch/2.2            # Node without this label
                operator: In
                values: 
                  - "true"
                  - "yes"
          weight: 20
  containers:
    - name: severalmatchexpressions-2
      image: busybox:latest
      command:
        - sleep
        - "3600"

```
* `kubectl apply -f pod.yaml`
* `kubectl get pod/severalmatchexpressions-2 -o wide` confirming that it's 'Running' and assigned to a node, **although** there is **NO** node without those labels.

**Proposed Solution:**

"If you specify multiple expressions in a single matchExpressions field associated with a term in nodeSelectorTerms, take into account that the expressions are ANDed."

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
