### ISSUE TITLE
DNS for Services and Pods

### ISSUE THREAD

**Issue by ThatAIXGuy** [kubernetes/website#44799]
Is there a document where the DNS options - options are? 
From the example: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
```yaml
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 192.0.2.1 # this is an example
    searches:
      - ns1.svc.cluster-domain.example
      - my.dns.search.suffix
    options:
      - name: ndots
        value: "2"
      - name: edns0
```

Can I stop AAAA (IPv6 lookups) from the pod, like I can w/coredns?
