### ISSUE TITLE
Incorrect type for 'ports' field in "Network Policies" page examples

### ISSUE THREAD

**Issue by WisePorterCloud** [kubernetes/website#44825]
I'am checking some samples about `NetworkPolicy` object and it seems to be bug in `ports`. According [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#networkpolicyegressrule-v1-networking-k8s-io) it is **array** but in all samples published in https://kubernetes.io/docs/concepts/services-networking/network-policies/ there is **ports** as `NetworkPolicyPort`.

**Example that it does not work properly** (but without error during creation):

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np
  namespace: space1
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: space2
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
```

**Example that it works as expected**:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np
  namespace: space1
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: space2
    - ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
```
