### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by shorif2000** [kubernetes/website#45021]
please add canary example as it is impossible to find in https://kubernetes.io/ . There are good examples here but this is not available to use directly in website https://kubernetes.github.io/ingress-nginx/examples/canary/

There needs to be some examples put on the page

```

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary
  annotations:
    nginx.ingress.kubernetes.io/canary: \"true\"
    nginx.ingress.kubernetes.io/canary-weight: \"50\"
spec:
  ingressClassName: nginx
  rules:
  - host: echo.prod.mydomain.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: canary
            port:
              number: 80
```
