### ISSUE TITLE
CrashLoopBackOff for whatever Alpine Image used

### ISSUE THREAD

**Issue by eliassal** [kubernetes/website#45429]
**This is a Bug Report**

**Problem:**
Hi, I am trying a simple deployment with an alpine image (built by myself as well as using vandot/alpine-bash). Deployment gets created then I have 0/1 ready and see CrashLoopBackOff in the pod details. In spite of the fact that when I use docker run for both images everything works fine and I am able to access the bash in the container.

Here is the the deployment yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
 name: alpine-bash
 namespace: debugservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-bash
  template:
    metadata:
      labels:
        app: alpine-bash
    spec:
      containers:
      - name: openjdk8alpinewithbash
        image: vandot/alpine-bash
```

or 

`image: eliassal/openjdk:8-jdk-alpine-with-bash`

Here is the dockerfile that I used to build the alpine image with bash

```
FROM openjdk:8-jdk-alpine
MAINTAINER baeldung.com
RUN apk update && apk add bash
CMD /bin/bash

```

Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.26.4
