### ISSUE TITLE
Policies > LimitRange Example not Correct..!!

### ISSUE THREAD

**Issue by faizan35** [kubernetes/website#45630]
In the first Pod, Where CPU resource request of `700m`, but not a limit.

**Why will it fail**, it is less than the Max value provided in `LimitRange` which is `1`.??

https://kubernetes.io/docs/concepts/policy/limit-range/#limitrange-and-admission-checks-for-pods

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/policy/limit-range/
/language en

**Comment by adityasamant25** [comment]
Hi @faizan35,
The example described in the documentation is correct.
The max value defined in the LimitRange is the maximum permissible value. However in case the Pod's container does not define a resource limit, the default CPU limit of 500m that is defined in the LimitRange will be applied (not the max value).

As the requested CPU of 700m is greater than the default limit of 500, Kubernetes throws an error.

If you explicitly define CPU limit as 700m, the Pod will be created.

```
apiVersion: v1
kind: Pod
metadata:
  name: example-conflict-with-limitrange-cpu
spec:
  containers:
    - name: demo
      image: registry.k8s.io/pause:2.0
      resources:
        limits:
          cpu: 700m
        requests:
          cpu: 700m
```

Note that if you explicitly define a CPU limit > 1, then Kubernetes will throw an error as the LimitRange defines the maximum permissible value as 1.

Hope this helps in clearly the doubt.
