### ISSUE TITLE
Quotes in `hostPath` path attribute in PersistentVolume example causing PersistentVolumeClaim binding failure

### ISSUE THREAD

**Issue by awoichanksy** [kubernetes/website#46047]
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

when using path: "/mnt/data" with quotes. the PVC cannot be bound to this PV
please remove the quotes from the doc
