### ISSUE TITLE
Automate a reminder to PR authors when their PR contains a large number of commits

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#46638]
This is a discussion of how to solve the following problem:

> The 903 commits in the upstream dev-1.24-bn.1 are not following the SIG-Docs commit squashing policy. dev-1.24-bn.1 contains too many redundant or irrelevant commits. My suggestion was to open another PR with one squashed commit for this first release of the Bengali localization. (https://github.com/kubernetes/website/pull/45009#issuecomment-2102882401)
> Reviewed how we've managed similar cases in the past: https://github.com/kubernetes/website/pull/45009#issuecomment-2103633952

Please disregard the previous obsolete proposal. 

## previous obsolete proposal

**This is a Feature Request**

**Problem**: In some cases, pull requests (PRs) contain a large number of commits. This often occurs in localization PRs when the author accepts multiple suggestions through the GitHub UI, creating a new commit for each suggestion. Consequently, a single PR can add hundreds of commits to the repository's change history. This excessive change history becomes counterproductive if these commits do not provide significant value. Although we encourage PR authors to squash their changes, they occasionally forget, and these PRs, along with their extensive commit histories, sometimes get merged. We rely on training and reminders to address this issue, but these measures are not always effective. Thus, there is a need for a more automated solution to ensure a clean and manageable commit history.

**What would you like to be added**

To address the problem of PRs containing excessive commits, I propose adding a feature that automatically comments on PRs with more than a specified number of commits, reminding authors to squash their commits before merging. This can be implemented using GitHub Actions as follows:

1. **GitHub Action Workflow**:
   - Create a GitHub Action that triggers on pull request events (e.g., when a PR is opened or updated).
   - The Action will check the number of commits in the PR.

2. **Automated Comment**:
   - If the number of commits exceeds a specified threshold (e.g., 10 commits), the Action will automatically post a comment on the PR.
   - The comment will remind the PR author to squash their commits before merging.

3. **Implementation Example**:
   - Below is an example of a GitHub Action workflow that achieves this functionality:

```yaml
name: Comment on PR with Many Commits

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Count commits in the pull request
      id: count_commits
      run: |
        PR_NUMBER=$(echo "${{ github.event.number }}")
        COMMITS=$(gh pr view $PR_NUMBER --json commits --jq '.commits | length')
        echo "commit_count=$COMMITS" >> $GITHUB_ENV

    - name: Post comment if commit count exceeds 10
      if: env.commit_count > 10
      run: |
        PR_NUMBER=$(echo "${{ github.event.number }}")
        gh pr comment $PR_NUMBER --body "This pull request contains more than 10 commits. Please consider squashing some commits."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comments**

This method leverages GitHub Actions for automation, ensuring that your repository maintains a clean and manageable commit history by automatically reminding PR authors to squash their commits when necessary.
