### ISSUE TITLE
Missing Persistent Volume and Storage Class Configuration in MySQL-WordPress Tutorial

### ISSUE THREAD

**Issue by lsdeva** [kubernetes/website#46814]
The current [MySQL-WordPress tutorial](https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/) does not include the necessary steps for creating Persistent Volumes (PVs) and defining the storage class. This can lead to Persistent Volume Claims (PVCs) remaining in a Pending state due to the absence of available PVs with the required storage class. 

**Create Persistent Volumes (PVs) with the Standard Storage Class:**

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/wordpress
```

**Define Persistent Volume Claims (PVCs) with Matching Storage Class:**

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  **storageClassName: standard**
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  **storageClassName: standard**
  resources:
    requests:
      storage: 20Gi

```
