### ISSUE TITLE
Incorrect indentation in network policy example

### ISSUE THREAD

**Issue by Ritikaa96** [kubernetes/website#47788]
**This is a Bug Report**

The example service/networking/networkpolicy-multiport-egress.yaml has some incorrect indentations. seems like it need some corrections. specially for the egress options.

**Problem:**
networkpolicy-multiport-egress.yaml has some incorrect indentations
**Proposed Solution:**
correct indentations
**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-range-of-ports

**Comment by sftim** [comment]
What's wrong about the indentation? It's a bit hard to read but it doesn't look wrong to me @Ritikaa96 

Maybe we can add explanatory comments instead.

@tengqm recently checked our example manifests with a machine tool and nothing got picked up here.

**Comment by Ritikaa96** [comment]
Hi @sftim . I tried this yaml yesterday in a virtual env where it should the problem , but when i try it in local system it ran effortlessly. still if we compare the indentations in [service/networking/networkpolicy-multiport-egress.yaml](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/networking/networkpolicy-multiport-egress.yaml) and targeting multiple namespaces by label one which is given below we can see the egress configurations are slightly right indented. 
```multiport-egress.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: multi-port-egress
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 32000
          endPort: 32768
```
Visually , if someone wants to take reference of the indentations and is looking at this one directly they might get confused
``` yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-namespaces
spec:
  podSelector:
    matchLabels:
      app: myapp
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchExpressions:
        - key: namespace
          operator: In
          values: ["frontend", "backend"]
```
