### ISSUE TITLE
Node-pressure Eviction

### ISSUE THREAD

**Issue by chenxinlong** [kubernetes/website#47817]
According to the documents :  

> The kubelet uses the following parameters to determine the pod eviction order:
>
> 1. Whether the pod's resource usage exceeds requests
> 2. [Pod Priority](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/)
> 3. The pod's resource usage relative to requests

I was wondering will pods like kube-apiserver and kube-controller-manager (`Burstable` qos but `system-node-critical` priority which has the highest priority) still respect rules above ?  If so,  does it means kube-apiserver will be evicted instead of another pod has 0 priority but qos is `Guaranteed`?

**Comment by tamilselvan1102** [comment]
related page: https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#pod-selection-for-kubelet-eviction

**Comment by chenxinlong** [comment]
> related page: https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#pod-selection-for-kubelet-eviction

@tamilselvan1102  This is where my confusion comes from.  

When kubelet decides to evict pods, according to this document, kube-apiserver are more likely to be evicted than a random pod(let say it's a pod runs unimportant programs) has a `Guaranteed` qos. I think it's counterintuitive.

So the answer is "yes" ?

**Comment by tamilselvan1102** [comment]
I think Control-Plane components are treated with some special way than user created pods

**Comment by chenxinlong** [comment]
The problem I'm facing is that I'm using operators to deploy some important components like calico(cni), but those calico pods has `BestEffort` qos and `system-cluster-critical` priority.  

So according to the rules mentioned in document, those cni pods will be evicted first which may cause serious problems. 

```yaml
apiVersion: v1
kind: Pod
metadata:
  ...
  name: calico-kube-controllers-74d8fb767-69bq7
  namespace: calico-system
spec:
  containers:
    image: calico/kube-controllers:v3.26.3
    imagePullPolicy: IfNotPresent
    resources: {}
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  ...
status:
  ...
  qosClass: BestEffort
```

I was wondering if the kubernetes shipped priority class doesn't follow the eviction rules, I woundn't worry about this problem.
