### ISSUE TITLE
Define Environment Variables for a Container

### ISSUE THREAD

**Issue by amitgitz** [kubernetes/website#48273]
Not able to Login to Container

<img width="887" alt="Screenshot 2024-10-10 at 1 29 56 PM" src="https://github.com/user-attachments/assets/44fd434a-f2b6-4117-b0d9-8f1037ee8086">

**Comment by niranjandarshann** [comment]
@amitgitz  can you provide the yaml file you created?

**Comment by niranjandarshann** [comment]
Page related issue https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
/sig docs
/language en

**Comment by tengqm** [comment]
This could be caused by the image used failed to include the `coreutils` package.
We need to use a different image if so.

**Comment by niranjandarshann** [comment]
> This could be caused by the image used failed to include the `coreutils` package. We need to use a different image if so.

Yes we should use the image where printenv command is used like busybox instead of  gcr.io/google-samples/hello-app:2.0

**Comment by amitgitz** [comment]
> @amitgitz can you provide the yaml file you created?

pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/hello-app:2.0
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
      
  ```

**Comment by niranjandarshann** [comment]
@amitgitz  yes the image is not correctly used.
Here we can use different image like `nginx:1.21.6` putting rest yaml as it is will work perfectly.

**Comment by niranjandarshann** [comment]
I am Adding the yaml file here which  run successfully.

```
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: nginx:1.21.6
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
```
