### ISSUE TITLE
Wrong explanation of initialDelaySeconds in configuring Probes

### ISSUE THREAD

**Issue by qiyueyao** [kubernetes/website#48519]
**This is a Bug Report**

Problem: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes mentioned _If the value of `periodSeconds` is greater than `initialDelaySeconds` then the `initialDelaySeconds` will be ignored._ However, in fact, `initialDelaySeconds` will not be ignored, and the first probe happens around `initialDelaySeconds`+`periodSeconds`. [Code Reference](url)

Proposed Solution:
Remove this sentence, or modify the explanation to the correct one.

Page to Update:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

Additional Information:
Affecting all /language.

**Comment by tnqn** [comment]
@qiyueyao The link of "Code Reference" seems wrong. To clarify a bit the observation that "the first probe happens around initialDelaySeconds+periodSeconds": the probe doesn't wait for `initialDelaySeconds` to start; it starts immediately but is canceled if the container hasn’t been running for the duration of `initialDelaySeconds`. Therefore, the 1st probe happens after `initialDelaySeconds` but not necessarily after `initialDelaySeconds`+`periodSeconds`.

**Comment by qiyueyao** [comment]
> @qiyueyao The link of "Code Reference" seems wrong. To clarify a bit the observation that "the first probe happens around initialDelaySeconds+periodSeconds": the probe doesn't wait for `initialDelaySeconds` to start; it starts immediately but is canceled if the container hasn’t been running for the duration of `initialDelaySeconds`. Therefore, the 1st probe happens after `initialDelaySeconds` but not necessarily after `initialDelaySeconds`+`periodSeconds`.

Thanks this explains better, I have updated code reference.

**Comment by T-Lakshmi** [comment]
/assign @qiyueyao

PR working on this issue #48536

**Comment by vaibhav2107** [comment]
/remove-lifecycle stale
As PR is still open

**Comment by Kashemir001** [comment]
Good to see this problem being address, the discrepancies between the docs and what I actually see happening with my pods have been bothering me for some time. I agree with the issue subject, saying that `initialDelaySeconds` is ignored when it is lower than `periodSeconds` is wrong, it definitely has some effect for the readiness probes at least.

Now another point I'd like to bring up for discussion after reading this issue, related PR and doing some personal testing is the way how initial "delay" works. Consider the following example:

<details><summary>probes.yaml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-test
  labels:
    app: probe-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-test
  template:
    metadata:
      labels:
        app: probe-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30

```
</details>

```
2025/04/25 13:18:56 [notice] 1#1: start worker process 30
10.112.133.1 - - [25/Apr/2025:13:19:25 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:19:25 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:19:55 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:19:55 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:20:25 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:20:25 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
```

The pod starts running at about 13:18:56. The readiness probe did not happen right away that moment because `initialDelaySeconds` is set, even though it has a value lower than the `periodSeconds` and should be ignored as per docs (the subject of current issue). I made another comment focusing on that matter [in the proposed PR](https://github.com/kubernetes/website/pull/48536#discussion_r2060218117). What's more important in this example, is the moment when the probes start being executed. Here, it happend at 13:19:25 - let's name the first probe execution moment `t1`. We know that there was a skipped readiness probe execution at the pod start because of `initialDelaySeconds` being non-zero, and that time moment can also be calculated as `t0`=`t1`-`periodSeconds`. In the current example, `t0` is 13:18:55 ≈ 13:18:56, the moment pod turned to the `Running` state. Time distance between entering `Running` state and first probe execution is 30 seconds.

Now let's set `initialDelaySeconds` to something else, but still below `periodSeconds`:

<details><summary>Test case 2</summary>

```yaml
livenessProbe:
  httpGet:
    path: /index.html
    port: 80
  initialDelaySeconds: 29
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 29
  periodSeconds: 30
```

```
2025/04/25 13:31:47 [notice] 1#1: start worker process 31
10.112.133.1 - - [25/Apr/2025:13:32:16 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:32:16 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:32:46 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:32:46 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
```
</details>

Even though `initialDelaySeconds` was changed, increased almost twice, time distance between pod starting and probe execution is still 30 seconds, and `t0` still equals the time moment pod turns to the `Running` state. This case, compared to the first one, somewhat matches the docs' statement that `initialDelaySeconds` is ignored when it is lower than `periodSeconds` - nothing has changed if we keep the value below.

Let's make few more tests with `initialDelaySeconds` being not-lower than `periodSeconds`:

<details><summary>Test case 3</summary>

```yaml
livenessProbe:
  httpGet:
    path: /index.html
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 30
```

```
2025/04/25 13:40:32 [notice] 1#1: start worker process 30
10.112.133.1 - - [25/Apr/2025:13:41:30 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:41:30 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:42:00 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:42:00 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
```
</details>

Test case 3 - probes being skipped at `t0` (here at ~13:40:32) and `t1` (here at 13:41:00) makes sense, only starting at `t2` (`t0`+ 2 *`periodSeconds`), 60 seconds after pod start.

<details><summary>Test case 4</summary>

```yaml
livenessProbe:
  httpGet:
    path: /index.html
    port: 80
  initialDelaySeconds: 45
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 45
  periodSeconds: 30
```

```
2025/04/25 13:50:29 [notice] 1#1: start worker process 31
10.112.133.1 - - [25/Apr/2025:13:51:28 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:51:28 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:51:58 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:51:58 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
```
</details>

Test case 4 - the results are the same as for test case 3, probes are first executed at `t2`, 60 seconds after pod start.

<details><summary>Test case 5</summary>

```yaml
livenessProbe:
  httpGet:
    path: /index.html
    port: 80
  initialDelaySeconds: 59
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 59
  periodSeconds: 30
```

```
2025/04/25 13:53:26 [notice] 1#1: start worker process 30
10.112.133.1 - - [25/Apr/2025:13:54:25 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:54:25 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:54:55 +0000] "GET / HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
10.112.133.1 - - [25/Apr/2025:13:54:55 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "kube-probe/1.30" "-"
```
</details>

Test case 5 - the results are the same as for test cases 3 and 5, probes are first executed at `t2`, 60 seconds after pod start.

What do these cases show us? Even though we changed `initialDelaySeconds`, time distance between pod start and first probe execution stays the same. `t0` - the moment probe schedule timers start ticking - stays the same, the moment pod turns to `Running` state. Setting `initialDelaySeconds` to any value from `[n * periodSeconds; n+1 * periodSeconds - 1]`, n=0,1,2..., has the same effect (exception being n=0, where lower interval boundary should be excluded). The only really meaningfull values for `initialDelaySeconds` would be multiples of `periodSeconds`. Being able to set it to any arbitary integer value does not provide us with extra flexibility for configuration.

Moreover, given that the attribute is named "delay", it creates an illusion that it is an actual delay before timers start ticking. While in fact, it is somewhat a grace period during which probes are not executed on their schedule, which is untouched (see [the post above](https://github.com/kubernetes/website/issues/48519#issuecomment-2434098541)). If it was an actual delay, I'd say it should push the moment `t0` of probe schedule timers starting ticking from the moment of pod start to the moment of "pod start" + `initialDelaySeconds`. 

So I think that while current issue should be accepted, there are more things about `initialDelaySeconds` that create confusion and docs should be made even more verbose on how it works. Or maybe even a change on `initialDelaySeconds` naming, or the way it works?

N.B.: everything said is a result of black box testing and my personal observations. Would be great if someone knowledgeable of the code base would back up or refute all of it.
