### ISSUE TITLE
Invalid example manifest for `.dockercfg` Secret

### ISSUE THREAD

**Issue by Linda-sa** [kubernetes/website#48533]
The yaml specification in creates the following error:
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-dockercfg-4
  namespace: service-namespace
type: kubernetes.io/dockercfg
data:
  .dockercfg: |
    eyJhdXRocyI6eyJodHRwczovL2V4YW1wbGUvdjEvIjp7ImF1dGgiOiJvcGVuc2VzYW1lIn19fQo=
```
**Error from server (BadRequest): error when creating "dock3.yaml": Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 76**

The file yaml specification needs to be updated to the below (removing the pipe | from the yaml): 
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-dockercfg-4
  namespace: service-namespace
type: kubernetes.io/dockercfg
data:
  .dockercfg: 
    eyJhdXRocyI6eyJodHRwczovL2V4YW1wbGUvdjEvIjp7ImF1dGgiOiJvcGVuc2VzYW1lIn19fQo=
```
