### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/network-policies/

### ISSUE THREAD

**Issue by Ostromix** [kubernetes/website#48772]
Need more examples !!!
Remember, some people needed exact in  your documentation for such cases like exam preparation and completeon.
Because, in other cases it is moooooore convinient to use chatgpt instead of documentation, especially so lack on examples like this part.

can you just add some. like from chatgpt?

Allow Traffic from Specific Pods
Permits traffic only from Pods with specific labels (e.g., app: frontend).

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
```

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-namespace
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
```

Allow External Internet Access
Allows Pods to access the internet for updates or external APIs.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internet-access
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
```

Prevents traffic to sensitive subnets like a private network.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-sensitive-cidr
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 192.168.0.0/16
      except:
        - 
```
