### ISSUE TITLE
Missing required config option from `LeaderMigrationConfiguration` object

### ISSUE THREAD

**Issue by igtsekov** [kubernetes/website#48945]
**This is a Bug Report**

**Problem:** The [controller-manager-leader-migration
](https://kubernetes.io/docs/tasks/administer-cluster/controller-manager-leader-migration/) page has an incorrect `LeaderMigrationConfiguration` object definition.

``` yaml
kind: LeaderMigrationConfiguration
apiVersion: controllermanager.config.k8s.io/v1
leaderName: cloud-provider-extraction-migration
controllerLeaders:
  - name: route
    component: kube-controller-manager
  - name: service
    component: kube-controller-manager
  - name: cloud-node-lifecycle
    component: kube-controller-manager
```

**Proposed Solution:**
From the documentation of the [LeaderMigrationConfiguration](https://v1-27.docs.kubernetes.io/docs/reference/config-api/kube-controller-manager-config.v1alpha1/#controllermanager-config-k8s-io-v1alpha1-LeaderMigrationConfiguration), we can see that a `resourceLock` is marked as required.

So the configuration should look like this:

```yaml
kind: LeaderMigrationConfiguration
apiVersion: controllermanager.config.k8s.io/v1
leaderName: cloud-provider-extraction-migration
resourceLock: leases
controllerLeaders:
  - name: route
    component: kube-controller-manager
  - name: service
    component: kube-controller-manager
  - name: cloud-node-lifecycle
    component: kube-controller-manager
```

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/controller-manager-leader-migration/
