### ISSUE TITLE
Inconsistent documentation about featuregate ComponentSLIs

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#48960]
**This is a Bug Report**
**Problem:**
ComponentSLIs feature-gate state mentioned as stable since V1.29 under [Kubernetes Component SLI Metrics](https://kubernetes.io/docs/reference/instrumentation/slis/).
![image](https://github.com/user-attachments/assets/f0a45e24-01f8-4b7e-964f-70df37b3de4f)

But under feature-gate list its still mentaion as Beta state.
![image](https://github.com/user-attachments/assets/2f72274f-4959-4181-aaaa-29b5cb0526b8)

**Proposed Solution:**
Update the docs with accurate information.

**Comment by T-Lakshmi** [comment]
From the code comments its mentioned  ComponentSLIs officially graduated to GA in v1.29 but the gate was not updated until v1.32.

https://github.com/kubernetes/kubernetes/blob/a27498ef42f27e7cddadb2c5b31bc80fed81d964/staging/src/k8s.io/component-base/metrics/features/kube_features.go#L35

> ComponentSLIs: {
> {Version: version.MustParse("1.26"), Default: false, PreRelease: featuregate.Alpha},
> {Version: version.MustParse("1.27"), Default: true, PreRelease: featuregate.Beta},
> // ComponentSLIs officially graduated to GA in v1.29 but the gate was not updated until v1.32.
> // To support emulated versions, keep the gate until v1.35.
> {Version: version.MustParse("1.32"), Default: true, PreRelease: featuregate.GA, LockToDefault: true},
> },

**Comment by T-Lakshmi** [comment]
https://github.com/kubernetes/kubernetes/blob/a27498ef42f27e7cddadb2c5b31bc80fed81d964/test/featuregates_linter/test_data/versioned_feature_list.yaml#L209

```
- name: ComponentSLIs
  versionedSpecs:
  - default: false
    lockToDefault: false
    preRelease: Alpha
    version: "1.26"
  - default: true
    lockToDefault: false
    preRelease: Beta
    version: "1.27"
  - default: true
    lockToDefault: true
    preRelease: GA
    version: "1.32"
```
