### ISSUE TITLE
Containerd configuration needs to show new format version

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/website#48976]
**This is a Feature Request**

Currently documentation only shows the old "v2" format:

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd

In containerd 1.x:
```toml
[plugins."io.containerd.grpc.v1.cri"]
  sandbox_image = "registry.k8s.io/pause:3.2"
```

**What would you like to be added**

It should show **both** the "v2" (1.x) and "v3" (2.x) formats:

https://github.com/containerd/containerd/blob/release/2.0/docs/cri/config.md

In containerd 2.x:
```toml
    [plugins.'io.containerd.cri.v1.images'.pinned_images]
      sandbox = 'registry.k8s.io/pause:3.10'
```

**Why is this needed**

The old format is still supported in containerd 2.0, but in future versions it is deprecated (similar to "v1" today)

For the transitioning period (i.e. before 1.x is EOL), the duplicated documentation needs to shown both versions.

https://containerd.io/releases/#kubernetes-support

Both versions are currently documented upstream.

**Comments**

There is a related bug with kubeadm preflight, that makes it fail to detect the configured version no matter what...

warning: `detected that the sandbox image "" of the container runtime is inconsistent with that used by kubeadm`

But the user can verify the current config with `containerd config dump`, even though it is missing from `crictl info`.

* https://github.com/containerd/containerd/pull/11114
