### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by richarsi** [kubernetes/website#49270]
I am very new to Kubernetes.

I followed the instructions on the following page:
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

After the step "kubectl proxy" I was not able to launch the web UI using the URL: http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

The page displayed:

```yaml
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "services \"kubernetes-dashboard\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "services"
  },
  "code": 404
}
```

I found this article:
https://anirbanbh.medium.com/how-to-run-kubernetes-dashboard-on-with-local-admin-user-57e208f376e8

And used the following command:

kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443

And i was able to launch the login page via this URL https://localhost:8443/

I can't explain why I was unable to access the page using port forwarding but not the proxy command.  I also don't know if i was doing something wrong when using the proxy command.  If you can reproduce this then maybe the docs could be updated?
