### ISSUE TITLE
Stale image in "Configure Liveness, Readiness and Startup Probes"

### ISSUE THREAD

**Issue by harshitsahu2311** [kubernetes/website#49406]
In this document the yaml file for liveness probe using registry.k8s.io/busybox is showing depricated, but as I used busybox official image it is running as expected outputs.

**Comment by sftim** [comment]
/retitle Stale image in "Configure Liveness, Readiness and Startup Probes"
/language en

**Comment by sftim** [comment]
Assuming that we stick with Busybox:

- we should pin to a specific busybox image version
- we should make sure to use a current container image for Busybox (doesn't have to come from `registry.k8s.io`)

**Comment by iheartNathan** [comment]
@harshitsahu2311 where are you getting this deprecated message for registry.k8s.io/busybox?
`image: registry.k8s.io/busybox` is pulling the `lastest tag` for busybox

```
    containerStatuses:
    - containerID: containerd://0c37f27fe26d9746aad3c356540355da531ab52f5a3dea2d49b7cbdc8fa47133
      image: registry.k8s.io/busybox:latest
      imageID: sha256:36a4dca0fe6fb2a5133dc11a6c8907a97aea122613fa3e98be033959a0821a1f
```
```
$ crane ls registry.k8s.io/busybox --full-ref
registry.k8s.io/busybox:1.24
registry.k8s.io/busybox:1.27
registry.k8s.io/busybox:1.27.2
registry.k8s.io/busybox:latest
```
