### ISSUE TITLE
Add note about revocation in structured authentication configuration

### ISSUE THREAD

**Issue by aramase** [kubernetes/website#51015]
Doc to update: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#using-authentication-configuration

- We don't have any plans to add revocation at this time. Because of this the docs will be updated to make sure the tokens are short-lived as they are not revocable.
- While full token revocation is not supported, it is possible to approximate revocation by writing user info validation rules (e.g., via CEL) based on a unique identifier in the token, such as the jti claim (if present). Even without a jti, any claim that uniquely identifies the token can be used to simulate revocation by checking it against a denylist or revocation list. However, we still recommend using short-lived tokens as managing revocation this way can become complex and hard to scale.

Example of a revocation rule using the jti claim:

```yaml
userValidationRules:
  # this example rule expects the jti claim to be present in the token and that credential id is not in the denylist
- expression: `has(user.extra.authentication__dot__x__dash__kubernetes__dot__io__slash__credential__dash__id) && !(user.extra.authentication__dot__x__dash__kubernetes__dot__io__slash__credential__dash__id[0] in ["JTI=e28ed49-2e11-4280-9ec5-bc3d1d84661a"])`,
  message:    "credential id is revoked",
```
