### ISSUE TITLE
Issue with storageClassName attribute

### ISSUE THREAD

**Issue by derberg** [kubernetes/website#5436]
- [ ] Feature Request
- [X] Bug Report

**Problem:**
documentation states in few places:
```
In the past, the annotation volume.beta.kubernetes.io/storage-class was used instead of the storageClassName attribute. This annotation is still working, however it will become fully deprecated in a future Kubernetes release
```
So I tried to use `storageClassName` instead and it works very well in the cluster, persistentVolume is provisioned automatically. Unfortunately it is not working on minikube, on minikube persistentVolumeClaim works only with annotation way of referencing the storage class.

**Proposed Solution:**
Either update documentation and don't write about storageClassName or make it clear that storageClassName is not supported in minikube. Solution is also a bug fix for minikube to support storageClassName

**Page to Update:**
https://kubernetes.io/editdocs/#docs/concepts/storage/persistent-volumes.md

I'm on minikube v0.20.0

this is my configuration that I apply:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-docs-resources
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
  labels:
    app: minio-docs-resources
spec:
  #Below setting will be valid for future when above annotation way of referencing storage class will be deprecated
  #For now blow works only on cluster but not on minikube
  #storageClassName: idefix-tier-4
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-docs-resources
  labels:
    app: minio-docs-resources
spec:
  ports:
  - port: 9000
    name: http
  selector:
    app: minio-docs-resources
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: minio-docs-resources
  name: minio-docs-resources
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio-docs-resources
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-docs-resources
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        ports:
        - containerPort: 9000
          hostPort: 9000
        volumeMounts:
        - name: storage
          mountPath: "/storage"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: minio-docs-resources
  name: minio-docs-resources
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
    - hosts:
      - my-domain.com
      secretName: my-domain-cert
  rules:
  - host: my-domain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: minio-docs-resources
          servicePort: 9000
```

you can remove ingress part and make service of LoadBalancer type to check it without ingress. To check it with ingress you would have to do `minikube addons enable ingress`. HTTPS will obviously not work on local because of missing valid certificate so you can just access the app with HTTP. You also need to edit hosts file (`sudo nano /etc/hosts`) and add map custom domain against your `minikube ip`
