### ISSUE TITLE
Issue with /docs/getting-started-guides/minikube/

### ISSUE THREAD

**Issue by iramsey85** [kubernetes/website#5971]
Issue with /docs/getting-started-guides/minikube/

environment
deskstop running ubuntu 16.04
Virtualbox

Problem Steps
1. minikube install successful
2. kubectl install successful
3. checked cluster-info
Master node Running on localhost:8080

4.check dashboard connection (minikube dashboard)
able to bring up dashboard in browser, but running on a different IP 192.168.x.x (seemed odd)

5. attempted to deploy image (basic alpine linux container), failed
"error: failed to discover supported resources: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: getsockopt: connection refused"

6. attempted to kubectl get nodes, failed
"The connection to the server localhost:8080 was refused - did you specify the right host or port?"

7. checked ufw, ports 80, 8080, and 443 all open

Cannot determine the root cause. Configurations appear to be basic.

**Comment by heckj** [comment]
hi @iramsey85, thanks for the report. That minikube dashboard is running from a different IP than your desktop is normal - minikube is creating a VM with it's own private (internal) network - so you'll see IP addresses referenced from within minikube that aren't directly accessible, and the IP address of the VM running minikube itself will be different from your desktop's IP.

kubectl get nodes failing is troubling, as its indicating that the API server inside your kubernetes cluster isn't available. I have seen the `getsockopt: connection refused` types of errors when something is still setting up. Since you were able to see the dashboard, I would have expected that `kubectl get nodes` would respond easily and immediately. That one is responding and not the other is confusing to me.

The underlying issue appears to be with your installation of minikube over anything (yet) specific in the documentation about how to set up minikube, although I'd love to know if there are improvements we could make here related to what you're seeing.

So a few questions to help debug this:

0) are you accessing any other kubernetes clusters that could be intermixed in your expectations? You can see what kubectl thinks it should be talking to with the command `kubectl config view`. For reference, the output of that command on my laptop (not Ubuntu+Virtualbox, but should be reasonably close to what you have):
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/heckj/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/heckj/.minikube/client.crt
    client-key: /Users/heckj/.minikube/client.key
```
1) does kubectl version return properly (and with a version for the server)?
2) assuming that it does, what does `kubectl get pods --all-namespaces` show you - systems still starting up by chance, or in a crashloop backoff, or something else?
