### ISSUE TITLE
k8s.io/docs/user-guide/jsonpath/ does not document how to deal with complicated keys.

### ISSUE THREAD

**Issue by aknrdureegaesr** [kubernetes/website#6017]
**This is a...** 

- [ ] Feature Request
- [ X ] Bug Report

**Problem:**

In my map, there is a key containing a slash character "/", a dot ".", and a hyphen "-".

The above page does not documented how to write a JSONPath expression that filters for that key. (In fact, I couldn't figure out how to do it.)

Possibly, that isn't even possible because of problems with `kubectl`. This is speculation.

**Proposed Solution:**

Please find out whether it can be done and if so, kindly document what to do in this case. If not, kindly file a pertinent bug.

**Page to Update:**

https://kubernetes.io/docs/user-guide/jsonpath/

## Kubernetes version

```
# kubectl version
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

## Example

The JSON is from `kubectl get nodes` and the interesting parts look like this:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: 2017-10-23T09:59:06Z
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: t2.large
      beta.kubernetes.io/os: linux
    name: example.com
```

From the documentation, one thing I tried (among several), at my `bash` prompt, was

```
kubectl get nodes -o jsonpath="{range .items[*]}{['metadata']['name']},{['metadata']['labels']['beta.kubernetes.io/instance-type']}"'{"\n"}{end}'
```

This refuses to find the `beta.kubernetes.io/instance-type` key. After reading the documentation, I had expected it to find that.
