### ISSUE TITLE
not able to create a pods out out the replication controller

### ISSUE THREAD

**Issue by satyamsah** [kubernetes/website#6125]
I followed , kube deployment from  

https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

 http-rc .yml is replicaiton controller file:
apiVersion: v1

kind: ReplicationController

metadata:

  name: http-rc

spec:

  replicas: 7

  selector:

    app: hello-world

  template:

    metadata:

      labels:

	app: hello-world

    spec:

      containers:

      - name: hello-ctr

        image: httpd

        ports:

        - containerPort: 8080

and started as : kubectl create -f rc.yml 
output is :
replicationcontroller "http-rc" created

But even after few minutes , I am getting no preogres:

NAME       DESIRED   CURRENT   READY     AGE
http-rc    7         0         0         3m

**Comment by tengqm** [comment]
several hints FYI:

- to embed a yaml (or other source code) in a message on github, use the code format for people to better understand what you are using. E.g.

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: http-rc
spec:
  replicas: 7
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-ctr
        image: httpd
        ports:
        - containerPort: 8080
```

- This is obviously not a documentation issue. There could be a thousand reasons which fail your command. If you are not sure it is a bug, go Google and try your luck. If you are sure it is a bug, raise an issue to the github.com/kubernetes/kubernetes project.

Please close this one if this sounds acceptable.
