### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/volumes/

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/website#6141]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
the example does not work.
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  annotations:
        "volume.alpha.kubernetes.io/node-affinity": '{
            "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                    { "matchExpressions": [
                        { "key": "kubernetes.io/hostname",
                          "operator": "In",
                          "values": ["example-node"]
                        }
                    ]}
                 ]}
              }'
spec:
    capacity:
      storage: 100Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-storage
    local:
      path: /mnt/disks/ssd1
```
when i create it. my terminal show:

```shell
[root@controller:~/zxy]$ kubectl create -f example-local-pv.yml
The PersistentVolume "example-pv" is invalid:
* metadata.annotations: Forbidden: Storage node affinity is disabled by feature-gate
* spec.local: Forbidden: Local volumes are disabled by feature-gate
```
**Proposed Solution:**
fix the example.

**Page to Update:**
http://kubernetes.io/...
