### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

### ISSUE THREAD

**Issue by BrunoQuaresma** [kubernetes/website#6908]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The first example throws an error in the console about invalid backoffLimit.
```
error: error validating "./job.yaml": error validating data: found invalid field backoffLimit for v1.JobSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
***job spec***
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

**Proposed Solution:**
Update the example with correct and valid job spec format.

**Page to Update:**
http://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
