### ISSUE TITLE
Glossary _example template is not very descriptive for new contributors

### ISSUE THREAD

**Issue by sdague** [kubernetes/website#7462]
**This is a...** 
- [ x ] Feature Request
- [] Bug Report

**Problem:**

The _example file for the glossary terms shows all the required fields, however the example content isn't very useful for ensuring that you have the correct content in them. Especially with things like tags.

**Proposed Solution:**

The _example.yml could include inline comments that include further instructions and links. For instance:

```yaml
id: _example
name: Example K8s Term
# search on https://kubernetes.io/docs/home/ for relevant pages
full-link: /docs/link-to-long-dedicated-docs-page
aka:
- Slang K8s Term
- Misnomer
- Formerly Known as Prince
related:
- id-of-less-fancy-k8s-term
- id-of-tangential-term
- id-of-commonly-used-with-term
# canonical tag list can be found in _data/canonical-tags 
tags:
- Some Tag
...
```
