### ISSUE TITLE
k8s.io/docs/tasks/administer-cluster/

### ISSUE THREAD

**Issue by sunlintong** [kubernetes/website#7734]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
If I create a namespace,in the *LimitRange* :
```
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
```
Then I create a pod in that namespace : 
```
apiVersion: v1
kind: Pod
metadata:
  name: default-mem-demo-2
spec:
  containers:
  - name: defalt-mem-demo-2-ctr
    image: nginx
    resources:
      limits:
        memory: "1Gi"
```
The Pod's request memory become **1Gi** rather than **256Mi**,why?
And what's the benefit of this feature?

**Proposed Solution:**
Can someone tell me?Thanks so much : )

**Page to Update:**
https://kubernetes.io/...

v1.9
