### ISSUE TITLE
Broken static pod manifest in https://kubernetes.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by Cyclic3** [kubernetes/website#7893]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The manifest given for creating the static etcd pod in https://kubernetes.io/docs/setup/independent/high-availability/ is severely broken. Not only is yaml questionable, but the actual manifest is rejected by kubernetes.

**Proposed Solution:**
I have rewritten the manifest to actually load:
``` Yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
      component: etcd
      tier: control-plane
  name: etcd0
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd --name ${PEER_NAME} \
    - --data-dir=/var/lib/etcd \
    - --listen-client-urls=https://${PRIVATE_IP}:2379 \
    - --advertise-client-urls=https://${PRIVATE_IP}:2379 \
    - --listen-peer-urls=https://${PRIVATE_IP}:2380 \
    - --initial-advertise-peer-urls=https://${PRIVATE_IP}:2380 \
    - --cert-file=/certs/server.pem \
    - --key-file=/certs/server-key.pem \
    - --client-cert-auth \
    - --trusted-ca-file=/certs/ca.pem \
    - --peer-cert-file=/certs/peer.pem \
    - --peer-key-file=/certs/peer-key.pem \
    - --peer-client-cert-auth \
    - --peer-trusted-ca-file=/certs/ca.pem \  
    - --initial-cluster etcd0=https://<etcd0-ip-address>:2380,etcd1=https://<etcd1-ip-address>:2380,etcd2=https://<etcd2-ip-address>:2380 \
    - --initial-cluster-token=my-etcd-token \
    - --initial-cluster-state=new
    image: gcr.io/google_containers/etcd-amd64:3.1.12
    livenessProbe:
      httpGet:
        path: /health
        port: 2379
        scheme: HTTP
    initialDelaySeconds: 15
    timeoutSeconds: 15
    name: etcd
    env:
    - name: PUBLIC_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: PRIVATE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: PEER_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd
    - mountPath: /certs
      name: certs
  hostNetwork: true
  volumes:
  - name: etcd
    hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
  - name: certs
    hostPath:
      path: /etc/kubernetes/pki/etcd
      name: certs
```

When I then follow the rest of the instructions, and then run `kubeadm init --config=config.yaml`, I get the following output

``` Text
[init] Using Kubernetes version: v1.9.6
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 18.03.0-ce. Max validated version: 17.03
	[WARNING FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
	[WARNING FileExisting-crictl]: crictl not found in system path
	[WARNING ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
	[WARNING ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
	[WARNING ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
[certificates] Using the existing ca certificate and key.
[certificates] Using the existing apiserver certificate and key.
[certificates] Using the existing apiserver-kubelet-client certificate and key.
[certificates] Using the existing sa key.
[certificates] Using the existing front-proxy-ca certificate and key.
[certificates] Using the existing front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
	- There is no internet connection, so the kubelet cannot pull the following control plane images:
		- gcr.io/google_containers/kube-apiserver-amd64:v1.9.6
		- gcr.io/google_containers/kube-controller-manager-amd64:v1.9.6
		- gcr.io/google_containers/kube-scheduler-amd64:v1.9.6

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'
```

Running the two commands gives me nothing:
```
# journalctl -xeu kubelet
...
Mar 28 10:42:00 omicron-master systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Mar 28 10:42:00 omicron-master systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit kubelet.service has finished shutting down.
Mar 28 10:42:00 omicron-master systemd[1]: kubelet.service: Unit entered failed state.
Mar 28 10:42:00 omicron-master systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

Which dates from some tests I was doing to get the etcd.yaml file to work.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/

Kubernetes Version: 1.9.6, 1.10.0
