### ISSUE TITLE
Create Deployment instead of Pod (envvar topics)

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#8180]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Several Task topics have the reader create a Pod. It would be better to have the reader create a Deployment.

**Proposed Solution:**
For example, take this topic: [Define Environment Variables for a Container](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/).
The YAML file has a Pod manifest:

```
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
```

Change the YAML file to a Deployment manifest like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonstrate-envars
spec: # DeploymentSpec
  selector:
    matchLabels:
      app: node-hello
  replicas: 2
  template: # PodTemplateSpec
    metadata:
      labels:
        app: node-hello
    spec: # PodSpec
      containers:
      - name: envar-demo-container
        image: gcr.io/google-samples/node-hello:1.0
        env:
        - name: DEMO_GREETING
          value: "Hello from the environment"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
```

Adjust the the text before and after the YAML file.

For example, change "In this exercise, you create a Pod ..." to "In this exercise, you create a Deployment ...".

**Page to Update:**
https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
