### ISSUE TITLE
Create Deployment instead of Pod (credentials tasks)

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#8182]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Several Task topics have the reader create a Pod. It would be better to have the reader create a Deployment.

**Proposed Solution:**
For example, take this topic: [Distribute Credentials Securely Using Secrets](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/).
One of the YAML file has this Pod manifest:

```
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
          # name must match the volume name below
          - name: secret-volume
            mountPath: /etc/secret-volume
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
```

Change the YAML file to a Deployment manifest like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test
spec: # DeploymentSpec
  selector:
    matchLabels:
      purpose: test-secret-access
  replicas: 2
  template: # PodTemplateSpec
    metadata:
      labels:
        purpose: test-secret-access
    spec: # PodSpec
      containers:
        - name: test-container
          image: nginx
          volumeMounts:
              # name must match the volume name below
              - name: secret-volume
                mountPath: /etc/secret-volume
      # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
        - name: secret-volume
          secret:
            secretName: test-secret
```

Adjust the the text before and after any changed YAML files.

For example, change "Here is a configuration file you can use to create a Pod:" to "Here is a configuration file you can use to create a Deployment:".

**Page to Update:**
https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
https://kubernetes.io/docs/tasks/inject-data-application/podpreset/
