### ISSUE TITLE
Issue with k8s.io/docs/tasks/job/automated-tasks-with-cron-jobs/

### ISSUE THREAD

**Issue by Narsail** [kubernetes/website#8593]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

When I try to create a Cronjob with the provided cronjob.yml I get the following error:
```
error: error converting YAML to JSON: yaml: line 1: mapping values are not allowed in this context
```

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by CaoShuFeng** [comment]
This works well in my cluster:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
